<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TemplateFlashcardSeeder extends Seeder
{
    public function run()
    {
        $decks = DB::table('template_decks')->pluck('id', 'name');

        $flashcards = [
            '⌨️ Programming' => [
                ['question' => 'Алгоритм', 'answer' => 'Algorithm', 'weight' => 0],
                ['question' => 'Переменная', 'answer' => 'Variable', 'weight' => 0],
                ['question' => 'Функция', 'answer' => 'Function', 'weight' => 0],
                ['question' => 'Массив', 'answer' => 'Array', 'weight' => 0],
                ['question' => 'Объект', 'answer' => 'Object', 'weight' => 0],
                ['question' => 'Класс', 'answer' => 'Class', 'weight' => 0],
                ['question' => 'Интерфейс', 'answer' => 'Interface', 'weight' => 0],
                ['question' => 'Наследование', 'answer' => 'Inheritance', 'weight' => 0],
                ['question' => 'Полиморфизм', 'answer' => 'Polymorphism', 'weight' => 0],
                ['question' => 'Инкапсуляция', 'answer' => 'Encapsulation', 'weight' => 0],
                ['question' => 'Абстракция', 'answer' => 'Abstraction', 'weight' => 0],
                ['question' => 'Синтаксис', 'answer' => 'Syntax', 'weight' => 0],
                ['question' => 'Компилятор', 'answer' => 'Compiler', 'weight' => 0],
                ['question' => 'Интерпретатор', 'answer' => 'Interpreter', 'weight' => 0],
                ['question' => 'Библиотека', 'answer' => 'Library', 'weight' => 0],
                ['question' => 'Фреймворк', 'answer' => 'Framework', 'weight' => 0],
                ['question' => 'Модуль', 'answer' => 'Module', 'weight' => 0],
                ['question' => 'Пакет', 'answer' => 'Package', 'weight' => 0],
                ['question' => 'Сборка', 'answer' => 'Build', 'weight' => 0],
                ['question' => 'Отладка', 'answer' => 'Debugging', 'weight' => 0],
                ['question' => 'Рефакторинг', 'answer' => 'Refactoring', 'weight' => 0],
                ['question' => 'Тестирование', 'answer' => 'Testing', 'weight' => 0],
                ['question' => 'Версия', 'answer' => 'Version', 'weight' => 0],
                ['question' => 'Репозиторий', 'answer' => 'Repository', 'weight' => 0],
                ['question' => 'Пулл-реквест', 'answer' => 'Pull Request', 'weight' => 0],
                ['question' => 'Контейнеризация', 'answer' => 'Containerization', 'weight' => 0],
                ['question' => 'Виртуализация', 'answer' => 'Virtualization', 'weight' => 0],
                ['question' => 'Микросервис', 'answer' => 'Microservice', 'weight' => 0],
                ['question' => 'Архитектура', 'answer' => 'Architecture', 'weight' => 0],
                ['question' => 'Разработка', 'answer' => 'Development', 'weight' => 0],
            ],
            '💉 Medicine' => [
                ['question' => 'Диагноз', 'answer' => 'Diagnosis', 'weight' => 0],
                ['question' => 'Лекарство', 'answer' => 'Medicine', 'weight' => 0],
                ['question' => 'Врач', 'answer' => 'Doctor', 'weight' => 0],
                ['question' => 'Пациент', 'answer' => 'Patient', 'weight' => 0],
                ['question' => 'Терапия', 'answer' => 'Therapy', 'weight' => 0],
                ['question' => 'Хирургия', 'answer' => 'Surgery', 'weight' => 0],
                ['question' => 'Анализ крови', 'answer' => 'Blood Test', 'weight' => 0],
                ['question' => 'УЗИ', 'answer' => 'Ultrasound', 'weight' => 0],
                ['question' => 'Рентген', 'answer' => 'X-ray', 'weight' => 0],
                ['question' => 'Терапевт', 'answer' => 'Therapist', 'weight' => 0],
                ['question' => 'Операция', 'answer' => 'Operation', 'weight' => 0],
                ['question' => 'Вакцина', 'answer' => 'Vaccine', 'weight' => 0],
                ['question' => 'Иммунитет', 'answer' => 'Immunity', 'weight' => 0],
                ['question' => 'Эпидемия', 'answer' => 'Epidemic', 'weight' => 0],
                ['question' => 'Пандемия', 'answer' => 'Pandemic', 'weight' => 0],
                ['question' => 'Симптом', 'answer' => 'Symptom', 'weight' => 0],
                ['question' => 'Диета', 'answer' => 'Diet', 'weight' => 0],
                ['question' => 'Аллергия', 'answer' => 'Allergy', 'weight' => 0],
                ['question' => 'Инфекция', 'answer' => 'Infection', 'weight' => 0],
                ['question' => 'Воспаление', 'answer' => 'Inflammation', 'weight' => 0],
                ['question' => 'Онкология', 'answer' => 'Oncology', 'weight' => 0],
                ['question' => 'Кардиология', 'answer' => 'Cardiology', 'weight' => 0],
                ['question' => 'Неврология', 'answer' => 'Neurology', 'weight' => 0],
                ['question' => 'Дерматология', 'answer' => 'Dermatology', 'weight' => 0],
                ['question' => 'Педиатрия', 'answer' => 'Pediatrics', 'weight' => 0],
                ['question' => 'Психиатрия', 'answer' => 'Psychiatry', 'weight' => 0],
                ['question' => 'Гинекология', 'answer' => 'Gynecology', 'weight' => 0],
                ['question' => 'Урология', 'answer' => 'Urology', 'weight' => 0],
                ['question' => 'Ревматология', 'answer' => 'Rheumatology', 'weight' => 0],
                ['question' => 'Гастроэнтерология', 'answer' => 'Gastroenterology', 'weight' => 0],
                ['question' => 'Эндокринология', 'answer' => 'Endocrinology', 'weight' => 0],
                ['question' =>  'Сердечный приступ', 'answer' =>  'Heart attack', 'weight' =>  0],
                ['question' =>  'Инсульт', 'answer' =>  'Stroke', 'weight' =>  0],
                ['question' =>  'Гипертония', 'answer' =>  'Hypertension', 'weight' =>  0],
                ['question' =>  'Астма', 'answer' =>  'Asthma', 'weight' =>  0],
                ['question' =>  'Диабет', 'answer' =>  'Diabetes', 'weight' =>  0],
                ['question' =>  'Хроническая болезнь', 'answer' =>  'Chronic disease', 'weight' =>  0],
                ['question' =>  'Ожирение', 'answer' =>  'Obesity', 'weight' =>  0],
                ['question' =>  'Артрит', 'answer' =>  'Arthritis', 'weight' =>  0],
                ['question' =>  'Мигрень', 'answer' =>  'Migraine', 'weight' =>  0],
                ['question' =>  'Рак легких', 'answer' =>  'Lung cancer', 'weight' =>  0],
                ['question' =>  'Рак груди', 'answer' =>  'Breast cancer', 'weight' =>  0],
                ['question' =>  'Туберкулез', 'answer' =>  'Tuberculosis', 'weight' =>  0],
                ['question' =>  'Вирус иммунодефицита человека (ВИЧ)', 'answer' =>  'Human Immunodeficiency Virus (HIV)', 'weight' =>  0],
                ['question' =>  'СПИД', 'answer' =>  'AIDS', 'weight' =>  0],
                ['question' =>  'Малярия', 'answer' =>  'Malaria', 'weight' =>  0],
                ['question' =>  'Прививка', 'answer' =>  'Vaccination', 'weight' =>  0],
                ['question' =>  'Антибиотик', 'answer' =>  'Antibiotic', 'weight' =>  0],
                ['question' =>  'Обезболивающее средство', 'answer' =>  'Painkiller', 'weight' =>  0],
                ['question' =>  'Седативное средство', 'answer' =>  'Sedative', 'weight' =>  0],
                ['question' =>  'Психотропные препараты', 'answer' =>  'Psychotropic drugs', 'weight' =>  0],
                ['question' =>  'Антидепрессанты', 'answer' =>  'Antidepressants', 'weight' =>  0],
                ['question' =>  'Противовоспалительное средство', 'answer' =>  'Anti-inflammatory', 'weight' =>  0],
                ['question' =>  'Жаропонижающее средство', 'answer' =>  'Antipyretic', 'weight' =>  0],
                ['question' =>  'Гомеопатия', 'answer' =>  'Homeopathy', 'weight' =>  0],
                ['question' =>  'Физиотерапия', 'answer' =>  'Physiotherapy', 'weight' =>  0],
                ['question' =>  'Реабилитация', 'answer' =>  'Rehabilitation', 'weight' =>  0],
                ['question' =>  'Пластическая хирургия', 'answer' =>  'Plastic surgery', 'weight' =>  0],
                ['question' =>  'Экстренная помощь', 'answer' =>  'Emergency care', 'weight' =>  0],
                ['question' =>  'Неотложная помощь', 'answer' =>  'Urgent care', 'weight' =>  0],
                ['question' =>  'Амбулаторная помощь', 'answer' =>  'Outpatient care', 'weight' =>  0],
                ['question' =>  'Стационарная помощь', 'answer' =>  'Inpatient care', 'weight' =>  0],
                ['question' =>  'Диспансеризация', 'answer' =>  'Medical examination', 'weight' =>  0],
                ['question' =>  'Профилактика заболеваний', 'answer' =>  'Disease prevention', 'weight' =>  0],
                ['question' =>  'Инкубационный период', 'answer' =>  'Incubation period', 'weight' =>  0],
                ['question' =>  'Иммунная система', 'answer' =>  'Immune system', 'weight' =>  0],
                ['question' =>  'Лимфатическая система', 'answer' =>  'Lymphatic system', 'weight' =>  0],
                ['question' =>  'Костная система', 'answer' =>  'Skeletal system', 'weight' =>  0],
                ['question' =>  'Мышечная система', 'answer' =>  'Muscular system', 'weight' =>  0],
                ['question' =>  'Нервная система', 'answer' =>  'Nervous system', 'weight' =>  0],
                ['question' =>  'Пищеварительная система', 'answer' =>  'Digestive system', 'weight' =>  0],
                ['question' =>  'Респираторная система', 'answer' =>  'Respiratory system', 'weight' =>  0],
                ['question' =>  'Мочевыделительная система', 'answer' =>  'Urinary system', 'weight' =>  0],
                ['question' =>  'Эндокринная система', 'answer' =>  'Endocrine system', 'weight' =>  0],
                ['question' =>  'Сердечно-сосудистая система', 'answer' =>  'Cardiovascular system', 'weight' =>  0],
                ['question' =>  'Кожная система', 'answer' =>  'Integumentary system', 'weight' =>  0],
                ['question' =>  'Опорно-двигательная система', 'answer' =>  'Musculoskeletal system', 'weight' =>  0],
                ['question' =>  'Биопсия', 'answer' =>  'Biopsy', 'weight' =>  0],
                ['question' =>  'Рентгенография', 'answer' =>  'Radiography', 'weight' =>  0],
                ['question' =>  'КТ (компьютерная томография)', 'answer' =>  'CT (Computed Tomography)', 'weight' =>  0],
                ['question' =>  'МРТ (магнитно-резонансная томография)', 'answer' =>  'MRI (Magnetic Resonance Imaging)', 'weight' =>  0],
                ['question' =>  'ПЭТ (позитронно-эмиссионная томография)', 'answer' =>  'PET (Positron Emission Tomography)', 'weight' =>  0],
                ['question' =>  'Анализ мочи', 'answer' =>  'Urine test', 'weight' =>  0],
                ['question' =>  'ЭКГ (электрокардиограмма)', 'answer' =>  'ECG (Electrocardiogram)', 'weight' =>  0],
                ['question' =>  'ЭЭГ (электроэнцефалограмма)', 'answer' =>  'EEG (Electroencephalogram)', 'weight' =>  0],
                ['question' =>  'Эхокардиограмма', 'answer' =>  'Echocardiogram', 'weight' =>  0],
                ['question' =>  'Спирометрия', 'answer' =>  'Spirometry', 'weight' =>  0],
                ['question' =>  'Флюорография', 'answer' =>  'Fluorography', 'weight' =>  0],
                ['question' =>  'Ультразвуковое исследование', 'answer' =>  'Ultrasonic examination', 'weight' =>  0],
                ['question' =>  'Гастроскопия', 'answer' =>  'Gastroscopy', 'weight' =>  0],
                ['question' =>  'Колоноскопия', 'answer' =>  'Colonoscopy', 'weight' =>  0],
                ['question' =>  'Бронхоскопия', 'answer' =>  'Bronchoscopy', 'weight' =>  0],
                ['question' =>  'Лапароскопия', 'answer' =>  'Laparoscopy', 'weight' =>  0],
                ['question' =>  'Гинекологический осмотр', 'answer' =>  'Gynecological examination', 'weight' =>  0],
                ['question' =>  'Урологический осмотр', 'answer' =>  'Urological examination', 'weight' =>  0],
                ['question' =>  'Дерматологический осмотр', 'answer' =>  'Dermatological examination', 'weight' =>  0],
                ['question' =>  'Кардиологический осмотр', 'answer' =>  'Cardiological examination', 'weight' =>  0],
                ['question' =>  'Неврологический осмотр', 'answer' =>  'Neurological examination', 'weight' =>  0],
                ['question' =>  'Онкологический осмотр', 'answer' =>  'Oncological examination', 'weight' =>  0],
                ['question' =>  'Стоматологический осмотр', 'answer' =>  'Dental examination', 'weight' =>  0],
                ['question' =>  'Офтальмологический осмотр', 'answer' =>  'Ophthalmological examination', 'weight' =>  0],
                ['question' =>  'Отоларингологический осмотр', 'answer' =>  'Otorhinolaryngological examination', 'weight' =>  0],
                ['question' =>  'Педиатрический осмотр', 'answer' =>  'Pediatric examination', 'weight' =>  0],
                ['question' =>  'Психиатрический осмотр', 'answer' =>  'Psychiatric examination', 'weight' =>  0],
                ['question' =>  'Сердечно-сосудистая реанимация', 'answer' =>  'Cardiopulmonary resuscitation (CPR)', 'weight' =>  0],
                ['question' =>  'Дефибриллятор', 'answer' =>  'Defibrillator', 'weight' =>  0],
                ['question' =>  'Искусственная вентиляция легких', 'answer' =>  'Artificial lung ventilation', 'weight' =>  0],
                ['question' =>  'Гемодиализ', 'answer' =>  'Hemodialysis', 'weight' =>  0],
                ['question' =>  'Плазмаферез', 'answer' =>  'Plasmapheresis', 'weight' =>  0],
                ['question' =>  'Переливание крови', 'answer' =>  'Blood transfusion', 'weight' =>  0],
                ['question' =>  'Интубация', 'answer' =>  'Intubation', 'weight' =>  0],
                ['question' =>  'Катетеризация', 'answer' =>  'Catheterization', 'weight' =>  0],
                ['question' =>  'Парентеральное питание', 'answer' =>  'Parenteral nutrition', 'weight' =>  0],
                ['question' =>  'Энтеральное питание', 'answer' =>  'Enteral nutrition', 'weight' =>  0],
                ['question' =>  'Лечебное голодание', 'answer' =>  'Therapeutic fasting', 'weight' =>  0],
                ['question' =>  'Трансплантация органов', 'answer' =>  'Organ transplantation', 'weight' =>  0],
                ['question' =>  'Паллиативная помощь', 'answer' =>  'Palliative care', 'weight' =>  0],
                ['question' =>  'Госпитализация', 'answer' =>  'Hospitalization', 'weight' =>  0],
                ['question' =>  'Выписка из больницы', 'answer' =>  'Discharge from hospital', 'weight' =>  0],
                ['question' =>  'Амбулаторный прием', 'answer' =>  'Outpatient appointment', 'weight' =>  0],
                ['question' =>  'Прием у врача', 'answer' =>  'Doctor\'s appointment', 'weight' =>  0],
                ['question' =>  'Медицинская карта', 'answer' =>  'Medical record', 'weight' =>  0],
                ['question' =>  'История болезни', 'answer' =>  'Medical history', 'weight' =>  0],
                ['question' =>  'Медицинская страховка', 'answer' =>  'Medical insurance', 'weight' =>  0],
                ['question' =>  'Медицинское заключение', 'answer' =>  'Medical certificate', 'weight' =>  0],
                ['question' =>  'Рецепт', 'answer' =>  'Prescription', 'weight' =>  0],
                ['question' =>  'Медицинская справка', 'answer' =>  'Medical note', 'weight' =>  0],
                ['question' =>  'Вакцинация от гриппа', 'answer' =>  'Flu vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от кори', 'answer' =>  'Measles vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от краснухи', 'answer' =>  'Rubella vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от гепатита', 'answer' =>  'Hepatitis vaccination', 'weight' =>  0]

            ],
            '🛠 Technical' => [
                ['question' => 'Розетка', 'answer' => 'Socket', 'weight' => 0],
                ['question' => 'Провод', 'answer' => 'Wire', 'weight' => 0],
                ['question' => 'Аккумулятор', 'answer' => 'Battery', 'weight' => 0],
                ['question' => 'Электричество', 'answer' => 'Electricity', 'weight' => 0],
                ['question' => 'Заземление', 'answer' => 'Grounding', 'weight' => 0],
                ['question' => 'Напряжение', 'answer' => 'Voltage', 'weight' => 0],
                ['question' => 'Ток', 'answer' => 'Current', 'weight' => 0],
                ['question' => 'Сопротивление', 'answer' => 'Resistance', 'weight' => 0],
                ['question' => 'Осциллограф', 'answer' => 'Oscilloscope', 'weight' => 0],
                ['question' => 'Трансформатор', 'answer' => 'Transformer', 'weight' => 0],
                ['question' => 'Конденсатор', 'answer' => 'Capacitor', 'weight' => 0],
                ['question' => 'Резистор', 'answer' => 'Resistor', 'weight' => 0],
                ['question' => 'Диод', 'answer' => 'Diode', 'weight' => 0],
                ['question' => 'Транзистор', 'answer' => 'Transistor', 'weight' => 0],
                ['question' => 'Инвертор', 'answer' => 'Inverter', 'weight' => 0],
                ['question' => 'Преобразователь', 'answer' => 'Converter', 'weight' => 0],
                ['question' => 'Электродвигатель', 'answer' => 'Electric Motor', 'weight' => 0],
                ['question' => 'Генератор', 'answer' => 'Generator', 'weight' => 0],
                ['question' => 'Мультиметр', 'answer' => 'Multimeter', 'weight' => 0],
                ['question' => 'Светодиод', 'answer' => 'LED', 'weight' => 0],
                ['question' => 'Паяльник', 'answer' => 'Soldering Iron', 'weight' => 0],
                ['question' => 'Схема', 'answer' => 'Circuit', 'weight' => 0],
                ['question' => 'Плата', 'answer' => 'Board', 'weight' => 0],
                ['question' => 'Контактор', 'answer' => 'Contactor', 'weight' => 0],
                ['question' => 'Реле', 'answer' => 'Relay', 'weight' => 0],
                ['question' => 'Панель управления', 'answer' => 'Control Panel', 'weight' => 0],
                ['question' => 'Защитное устройство', 'answer' => 'Protective Device', 'weight' => 0],
                ['question' => 'Частотный преобразователь', 'answer' => 'Frequency Converter', 'weight' => 0],
                ['question' => 'Автоматический выключатель', 'answer' => 'Circuit Breaker', 'weight' => 0],
                ['question' => 'Предохранитель', 'answer' => 'Fuse', 'weight' => 0],
                ['question' => 'Стабилизатор напряжения', 'answer' => 'Voltage Stabilizer', 'weight' => 0],
            ],

            '💻 Dart & Flutter Syntax' => [
                ['question' => 'Переменная', 'answer' => 'var myVariable;', 'weight' => 0],
                ['question' => 'Константа', 'answer' => 'const myConst =\n 42;', 'weight' => 0],
                ['question' => 'Тип данных', 'answer' => 'int, double,\n String, bool', 'weight' => 0],
                ['question' => 'Список', 'answer' => 'List<int> numbers =\n [1, 2, 3];', 'weight' => 0],
                ['question' => 'Карта', 'answer' => 'Map<String, int>\n myMap = {\'one\': 1};', 'weight' => 0],
                ['question' => 'Цикл for', 'answer' => 'for (var i = 0; i < 5;\n i++) {}', 'weight' => 0],
                ['question' => 'Цикл while', 'answer' => 'while (condition)\n {}', 'weight' => 0],
                ['question' => 'Функция', 'answer' => 'void myFunction()\n {}', 'weight' => 0],
                ['question' => 'Анонимная функция', 'answer' => '(int x) =>\n x * 2;', 'weight' => 0],
                ['question' => 'Класс', 'answer' => 'class MyClass\n {}', 'weight' => 0],
                ['question' => 'Конструктор', 'answer' => 'MyClass(this.value);', 'weight' => 0],
                ['question' => 'Наследование', 'answer' => 'class Child extends\n Parent {}', 'weight' => 0],
                ['question' => 'Полиморфизм', 'answer' => 'Parent obj =\n Child();', 'weight' => 0],
                ['question' => 'Интерфейс', 'answer' => 'abstract class\n MyInterface {}', 'weight' => 0],
                ['question' => 'Миксин', 'answer' => 'mixin MyMixin\n {}', 'weight' => 0],
                ['question' => 'Асинхронность', 'answer' => 'Future<void>\n fetchData() async {}', 'weight' => 0],
                ['question' => 'Await', 'answer' => 'await\n fetchData();', 'weight' => 0],
                ['question' => 'Замыкание', 'answer' => 'Function add(int x)\n => (int y) => x + y;', 'weight' => 0],
                ['question' => 'Конечный автомат', 'answer' => 'switch (state)\n { case ... }', 'weight' => 0],
                ['question' => 'Провайдер', 'answer' => 'ChangeNotifierProvider(create:\n (_) => MyModel());', 'weight' => 0],
                ['question' => 'Навигация', 'answer' => 'Navigator.push(context,\n route);', 'weight' => 0],
                ['question' => 'Стейт', 'answer' => 'class MyStatefulWidgetState\n extends State<MyWidget> {}', 'weight' => 0],
                ['question' => 'Билд метод', 'answer' => 'Widget build(BuildContext\n context) {}', 'weight' => 0],
                ['question' => 'Контейнер', 'answer' => 'Container(width: 100,\n height: 100);', 'weight' => 0],
                ['question' => 'Стек', 'answer' => 'Stack(children:\n [Widget1(), Widget2()]);', 'weight' => 0],
                ['question' => 'Стрим', 'answer' => 'Stream<int> myStream\n = Stream.value(1);', 'weight' => 0],
                ['question' => 'Асинхронный генератор', 'answer' => 'Stream<int> async*\n myGenerator() {}', 'weight' => 0],
                ['question' => 'Фьючи', 'answer' => 'Future<int> futureValue\n = Future.value(10);', 'weight' => 0],
                ['question' => 'Контекст сборки', 'answer' => 'final context =\n this.context;', 'weight' => 0],
                ['question' => 'Инициализация состояния', 'answer' => '@override void\n initState() {}', 'weight' => 0],
                ['question' => 'Завершение состояния', 'answer' => '@override void\n dispose() {}', 'weight' => 0],
                ['question' => 'Текстовый виджет', 'answer' => 'Text(\'Hello\n World\');', 'weight' => 0],
                ['question' => 'Кнопка', 'answer' => 'ElevatedButton(onPressed:\n () {}, child: Text(\'Press\'));', 'weight' => 0],
                ['question' => 'Диалог', 'answer' => 'showDialog(context:\n context, builder: (_) =>\n AlertDialog());', 'weight' => 0],
                ['question' => 'Локализация', 'answer' => 'MaterialApp(localizationsDelegates:\n ...);', 'weight' => 0],
                ['question' => 'Анимация', 'answer' => 'AnimationController(vsync:\n this, duration:\n Duration(seconds: 1));', 'weight' => 0],
                ['question' => 'Тестирование', 'answer' => 'testWidgets(\'My Widget\n Test\', (WidgetTester tester)\n async {});', 'weight' => 0],
                ['question' => 'HTTP запрос', 'answer' => 'http.get(Uri.parse(\'https://\n example.com\'));', 'weight' => 0],
                ['question' => 'JSON сериализация', 'answer' => 'jsonEncode(myObject);', 'weight' => 0],
                ['question' => 'Локальное хранилище', 'answer' => 'SharedPreferences prefs =\n await SharedPreferences.getInstance();', 'weight' => 0],
                ['question' => 'Медиапроигрыватель', 'answer' => 'VideoPlayerController.network(\'https://\n example.com/video.mp4\');', 'weight' => 0],
                ['question' => 'Пакет', 'answer' => 'import \'package:provider/\n provider.dart\';', 'weight' => 0],
                ['question' => 'Библиотека', 'answer' => 'library\n my_library;', 'weight' => 0],
                
            ],



        ];

        foreach ($flashcards as $deckName => $cards) {
            foreach ($cards as $card) {
                DB::table('template_flashcards')->insert([
                    'deck_id' => $decks[$deckName],
                    'question' => $card['question'],
                    'answer' => $card['answer'],
                    'weight' => $card['weight'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
