<?php

return [
    ['question' => 'Все будет хорошо.', 'answer' => 'Alles wird gut.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы вам помочь.', 'answer' => 'Wir sind hier, um Ihnen zu helfen.', 'weight' => 0],
    ['question' => 'Вы в безопасности.', 'answer' => 'Sie sind in Sicherheit.', 'weight' => 0],
    ['question' => 'Я понимаю, что вы волнуетесь.', 'answer' => 'Ich verstehe, dass Sie besorgt sind.', 'weight' => 0],
    ['question' => 'Старайтесь не беспокоиться.', 'answer' => 'Versuchen Sie, sich keine Sorgen zu machen.', 'weight' => 0],
    ['question' => 'Мы позаботимся о вас.', 'answer' => 'Wir kümmern uns um Sie.', 'weight' => 0],
    ['question' => 'Вы не одиноки.', 'answer' => 'Sie sind nicht allein.', 'weight' => 0],
    ['question' => 'Ваше состояние под контролем.', 'answer' => 'Ihr Zustand ist unter Kontrolle.', 'weight' => 0],
    ['question' => 'Мы сделаем все возможное.', 'answer' => 'Wir werden unser Bestes tun.', 'weight' => 0],
    ['question' => 'Дышите глубже, это поможет.', 'answer' => 'Atmen Sie tief durch, das wird helfen.', 'weight' => 0],
    ['question' => 'Не стесняйтесь говорить о своих чувствах.', 'answer' => 'Scheuen Sie sich nicht, über Ihre Gefühle zu sprechen.', 'weight' => 0],
    ['question' => 'Вы можете на нас положиться.', 'answer' => 'Sie können sich auf uns verlassen.', 'weight' => 0],
    ['question' => 'Я рядом, чтобы помочь вам.', 'answer' => 'Ich bin hier, um Ihnen zu helfen.', 'weight' => 0],
    ['question' => 'Мы всегда на связи.', 'answer' => 'Wir sind immer für Sie da.', 'weight' => 0],
    ['question' => 'Все идет по плану.', 'answer' => 'Alles verläuft nach Plan.', 'weight' => 0],
    ['question' => 'Не волнуйтесь, у нас большой опыт.', 'answer' => 'Keine Sorge, wir haben viel Erfahrung.', 'weight' => 0],
    ['question' => 'Ваше здоровье для нас на первом месте.', 'answer' => 'Ihre Gesundheit hat für uns oberste Priorität.', 'weight' => 0],
    ['question' => 'Мы обсудим все ваши опасения.', 'answer' => 'Wir werden alle Ihre Bedenken besprechen.', 'weight' => 0],
    ['question' => 'Если что-то беспокоит вас, скажите мне.', 'answer' => 'Wenn Sie etwas beunruhigt, sagen Sie es mir bitte.', 'weight' => 0],
    ['question' => 'Мы объясним вам каждый шаг.', 'answer' => 'Wir werden Ihnen jeden Schritt erklären.', 'weight' => 0],
    ['question' => 'Вы можете задавать вопросы в любое время.', 'answer' => 'Sie können jederzeit Fragen stellen.', 'weight' => 0],
    ['question' => 'Я здесь, чтобы вас выслушать.', 'answer' => 'Ich bin hier, um Ihnen zuzuhören.', 'weight' => 0],
    ['question' => 'Вы можете рассчитывать на нашу поддержку.', 'answer' => 'Sie können auf unsere Unterstützung zählen.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы помочь вам пройти через это.', 'answer' => 'Wir sind hier, um Ihnen durch diese Situation zu helfen.', 'weight' => 0],
    ['question' => 'Вы сможете справиться с этим.', 'answer' => 'Sie werden das schaffen.', 'weight' => 0],
    ['question' => 'Мы будем рядом на протяжении всего лечения.', 'answer' => 'Wir werden während der gesamten Behandlung bei Ihnen sein.', 'weight' => 0],
    ['question' => 'Ваше здоровье улучшается.', 'answer' => 'Ihre Gesundheit verbessert sich.', 'weight' => 0],
    ['question' => 'Не стесняйтесь делиться своими переживаниями.', 'answer' => 'Zögern Sie nicht, Ihre Sorgen mitzuteilen.', 'weight' => 0],
    ['question' => 'Все будет хорошо, мы справимся.', 'answer' => 'Alles wird gut, wir schaffen das.', 'weight' => 0],
    ['question' => 'Вы можете говорить с нами о любых проблемах.', 'answer' => 'Sie können mit uns über alle Probleme sprechen.', 'weight' => 0],


    ['question' => 'болезнь', 'answer' => 'Krankheit', 'weight' => 0],
    ['question' => 'болезнь Альцгеймера', 'answer' => 'Alzheimer-Krankheit', 'weight' => 0],
    ['question' => 'боль', 'answer' => 'Schmerz', 'weight' => 0],
    ['question' => 'бронхи', 'answer' => 'Bronchien', 'weight' => 0],
    ['question' => 'вакцина', 'answer' => 'Impfstoff', 'weight' => 0],
    ['question' => 'воспаление', 'answer' => 'Entzündung', 'weight' => 0],
    ['question' => 'вывих', 'answer' => 'Luxation', 'weight' => 0],
    ['question' => 'геморрой', 'answer' => 'Hämorrhoiden', 'weight' => 0],
    ['question' => 'гепатит', 'answer' => 'Hepatitis', 'weight' => 0],
    ['question' => 'гиперемия', 'answer' => 'Hyperämie', 'weight' => 0],
    ['question' => 'гипертензия', 'answer' => 'Hypertonie', 'weight' => 0],
    ['question' => 'гипертиреоз', 'answer' => 'Hyperthyreose', 'weight' => 0],
    ['question' => 'гипогликемия', 'answer' => 'Hypoglykämie', 'weight' => 0],
    ['question' => 'гипоксия', 'answer' => 'Hypoxie', 'weight' => 0],
    ['question' => 'гипотермия', 'answer' => 'Hypothermie', 'weight' => 0],
    ['question' => 'глаукома', 'answer' => 'Glaukom', 'weight' => 0],
    ['question' => 'грипп', 'answer' => 'Grippe', 'weight' => 0],
    ['question' => 'дезинфекция', 'answer' => 'Desinfektion', 'weight' => 0],
    ['question' => 'дегидратация', 'answer' => 'Dehydration', 'weight' => 0],
    ['question' => 'диарея', 'answer' => 'Durchfall', 'weight' => 0],
    ['question' => 'дыхание', 'answer' => 'Atmung', 'weight' => 0],
    ['question' => 'желудок', 'answer' => 'Magen', 'weight' => 0],
    ['question' => 'желудочная язва', 'answer' => 'Magengeschwür', 'weight' => 0],
    ['question' => 'желтуха', 'answer' => 'Gelbsucht', 'weight' => 0],
    ['question' => 'заболевание', 'answer' => 'Erkrankung', 'weight' => 0],
    ['question' => 'зрение', 'answer' => 'Sehvermögen', 'weight' => 0],
    ['question' => 'инфаркт', 'answer' => 'Infarkt', 'weight' => 0],
    ['question' => 'инсульт', 'answer' => 'Schlaganfall', 'weight' => 0],
    ['question' => 'инфекция', 'answer' => 'Infektion', 'weight' => 0],
    ['question' => 'инъекция', 'answer' => 'Injektion', 'weight' => 0],
    ['question' => 'капилляр', 'answer' => 'Kapillare', 'weight' => 0],
    ['question' => 'кардиолог', 'answer' => 'Kardiologe', 'weight' => 0],
    ['question' => 'кардиология', 'answer' => 'Kardiologie', 'weight' => 0],
    ['question' => 'карцинома', 'answer' => 'Karzinom', 'weight' => 0],
    ['question' => 'катар', 'answer' => 'Katarrh', 'weight' => 0],
    ['question' => 'клетка', 'answer' => 'Zelle', 'weight' => 0],
    ['question' => 'клинический', 'answer' => 'Klinisch', 'weight' => 0],
    ['question' => 'коронарный', 'answer' => 'Koronar', 'weight' => 0],
    ['question' => 'корь', 'answer' => 'Masern', 'weight' => 0],
    ['question' => 'костный мозг', 'answer' => 'Knochenmark', 'weight' => 0],
    ['question' => 'краниальная', 'answer' => 'Kranial', 'weight' => 0],
    ['question' => 'кризис', 'answer' => 'Krise', 'weight' => 0],
    ['question' => 'кровоизлияние', 'answer' => 'Blutung', 'weight' => 0],
    ['question' => 'кровообращение', 'answer' => 'Kreislauf', 'weight' => 0],
    ['question' => 'кровотечение', 'answer' => 'Blutung', 'weight' => 0],
    ['question' => 'лихорадка', 'answer' => 'Fieber', 'weight' => 0],
    ['question' => 'лимфа', 'answer' => 'Lymphe', 'weight' => 0],
    ['question' => 'лимфома', 'answer' => 'Lymphom', 'weight' => 0],
    ['question' => 'магнитный резонанс', 'answer' => 'Magnetresonanz', 'weight' => 0],
    ['question' => 'медицинская помощь', 'answer' => 'Medizinische Versorgung', 'weight' => 0],
    ['question' => 'медсестра', 'answer' => 'Krankenschwester', 'weight' => 0],
    ['question' => 'мигрень', 'answer' => 'Migräne', 'weight' => 0],
    ['question' => 'миокард', 'answer' => 'Myokard', 'weight' => 0],
    ['question' => 'миокардит', 'answer' => 'Myokarditis', 'weight' => 0],
    ['question' => 'моча', 'answer' => 'Urin', 'weight' => 0],
    ['question' => 'мочевой пузырь', 'answer' => 'Blase', 'weight' => 0],
    ['question' => 'мышца', 'answer' => 'Muskel', 'weight' => 0],
    ['question' => 'невралгия', 'answer' => 'Neuralgie', 'weight' => 0],
    ['question' => 'неврология', 'answer' => 'Neurologie', 'weight' => 0],
    ['question' => 'некроз', 'answer' => 'Nekrose', 'weight' => 0],
    ['question' => 'обморок', 'answer' => 'Ohnmacht', 'weight' => 0],
    ['question' => 'обследование', 'answer' => 'Untersuchung', 'weight' => 0],
    ['question' => 'обструкция', 'answer' => 'Obstruktion', 'weight' => 0],
    ['question' => 'ожог', 'answer' => 'Verbrennung', 'weight' => 0],
    ['question' => 'опухоль', 'answer' => 'Tumor', 'weight' => 0],
    ['question' => 'органы', 'answer' => 'Organe', 'weight' => 0],
    ['question' => 'острая боль', 'answer' => 'Akuter Schmerz', 'weight' => 0],
    ['question' => 'остеопороз', 'answer' => 'Osteoporose', 'weight' => 0],
    ['question' => 'отеки', 'answer' => 'Ödeme', 'weight' => 0],
    ['question' => 'отек', 'answer' => 'Schwellung', 'weight' => 0],
    ['question' => 'отит', 'answer' => 'Otitis', 'weight' => 0],
    ['question' => 'отравление', 'answer' => 'Vergiftung', 'weight' => 0],
    ['question' => 'отсутствие аппетита', 'answer' => 'Appetitlosigkeit', 'weight' => 0],
    ['question' => 'отсутствие дыхания', 'answer' => 'Atemstillstand', 'weight' => 0],
    ['question' => 'панкреатит', 'answer' => 'Pankreatitis', 'weight' => 0],
    ['question' => 'паралич', 'answer' => 'Lähmung', 'weight' => 0],
    ['question' => 'параноидальный', 'answer' => 'Paranoid', 'weight' => 0],
    ['question' => 'пародонтит', 'answer' => 'Parodontitis', 'weight' => 0],
    ['question' => 'патоген', 'answer' => 'Pathogen', 'weight' => 0],
    ['question' => 'патология', 'answer' => 'Pathologie', 'weight' => 0],
    ['question' => 'пациент', 'answer' => 'Patient', 'weight' => 0],
    ['question' => 'перелом', 'answer' => 'Bruch', 'weight' => 0],
    ['question' => 'перикардит', 'answer' => 'Perikarditis', 'weight' => 0],
    ['question' => 'пищевод', 'answer' => 'Speiseröhre', 'weight' => 0],
    ['question' => 'пневмония', 'answer' => 'Pneumonie', 'weight' => 0],
    ['question' => 'пневмоторакс', 'answer' => 'Pneumothorax', 'weight' => 0],
    ['question' => 'позвоночник', 'answer' => 'Wirbelsäule', 'weight' => 0],
    ['question' => 'помощь', 'answer' => 'Hilfe', 'weight' => 0],
    ['question' => 'почки', 'answer' => 'Nieren', 'weight' => 0],
    ['question' => 'прививка', 'answer' => 'Impfung', 'weight' => 0],
    ['question' => 'пролежни', 'answer' => 'Dekubitus', 'weight' => 0],
    ['question' => 'простуда', 'answer' => 'Erkältung', 'weight' => 0],
    ['question' => 'противовирусное средство', 'answer' => 'Antivirales Mittel', 'weight' => 0],
    ['question' => 'профилактика', 'answer' => 'Prävention', 'weight' => 0],
    ['question' => 'пульс', 'answer' => 'Puls', 'weight' => 0],
    ['question' => 'пульмонология', 'answer' => 'Pneumologie', 'weight' => 0],
    ['question' => 'пульмонолог', 'answer' => 'Pneumologe', 'weight' => 0],
    ['question' => 'рак', 'answer' => 'Krebs', 'weight' => 0],
    ['question' => 'рвота', 'answer' => 'Erbrechen', 'weight' => 0],
    ['question' => 'реанимация', 'answer' => 'Reanimation', 'weight' => 0],
    ['question' => 'ревматизм', 'answer' => 'Rheumatismus', 'weight' => 0],
    ['question' => 'рентген', 'answer' => 'Röntgen', 'weight' => 0],
    ['question' => 'риноскопия', 'answer' => 'Rhinoskopie', 'weight' => 0],
    ['question' => 'сердце', 'answer' => 'Herz', 'weight' => 0],
    ['question' => 'сердечно-сосудистая система', 'answer' => 'Kardiovaskuläres System', 'weight' => 0],
    ['question' => 'синкопа', 'answer' => 'Synkope', 'weight' => 0],
    ['question' => 'сканирование', 'answer' => 'Scanning', 'weight' => 0],
    ['question' => 'склероз', 'answer' => 'Sklerose', 'weight' => 0],
    ['question' => 'сколиоз', 'answer' => 'Skoliose', 'weight' => 0],
    ['question' => 'слепота', 'answer' => 'Blindheit', 'weight' => 0],
    ['question' => 'смерть', 'answer' => 'Tod', 'weight' => 0],
    ['question' => 'спазм', 'answer' => 'Krampf', 'weight' => 0],
    ['question' => 'спинной мозг', 'answer' => 'Rückenmark', 'weight' => 0],
    ['question' => 'судороги', 'answer' => 'Krämpfe', 'weight' => 0],
    ['question' => 'сустав', 'answer' => 'Gelenk', 'weight' => 0],
    ['question' => 'сухость', 'answer' => 'Trockenheit', 'weight' => 0],
    ['question' => 'сыпь', 'answer' => 'Ausschlag', 'weight' => 0],
    ['question' => 'температура', 'answer' => 'Temperatur', 'weight' => 0],
    ['question' => 'тестирование', 'answer' => 'Testen', 'weight' => 0],
    ['question' => 'ткань', 'answer' => 'Gewebe', 'weight' => 0],
    ['question' => 'травма', 'answer' => 'Trauma', 'weight' => 0],
    ['question' => 'тромбоз', 'answer' => 'Thrombose', 'weight' => 0],
    ['question' => 'тромбоцит', 'answer' => 'Thrombozyt', 'weight' => 0],
    ['question' => 'тромбофлебит', 'answer' => 'Thrombophlebitis', 'weight' => 0],
    ['question' => 'удушье', 'answer' => 'Erstickung', 'weight' => 0],
    ['question' => 'улучшение', 'answer' => 'Besserung', 'weight' => 0],
    ['question' => 'умеренное обезболивание', 'answer' => 'Mäßige Schmerzmittel', 'weight' => 0],
    ['question' => 'урология', 'answer' => 'Urologie', 'weight' => 0],
    ['question' => 'усталость', 'answer' => 'Müdigkeit', 'weight' => 0],
    ['question' => 'фарингит', 'answer' => 'Pharyngitis', 'weight' => 0],
    ['question' => 'фиброз', 'answer' => 'Fibrose', 'weight' => 0],
    ['question' => 'физиотерапия', 'answer' => 'Physiotherapie', 'weight' => 0],
    ['question' => 'флюорография', 'answer' => 'Fluorografie', 'weight' => 0],
    ['question' => 'фолликулит', 'answer' => 'Follikulitis', 'weight' => 0],
    ['question' => 'челюсть', 'answer' => 'Kiefer', 'weight' => 0],
    ['question' => 'чрезмерное потоотделение', 'answer' => 'Hyperhidrose', 'weight' => 0],
    ['question' => 'щитовидная железа', 'answer' => 'Schilddrüse', 'weight' => 0],
    ['question' => 'язвенный колит', 'answer' => 'Colitis ulcerosa', 'weight' => 0],



    ['question' => 'Вы можете чувствовать боль, но это временно.', 'answer' => 'Sie könnten Schmerzen verspüren, aber das ist vorübergehend.', 'weight' => 0],
    ['question' => 'Не волнуйтесь, я здесь, чтобы помочь вам.', 'answer' => 'Keine Sorge, ich bin hier, um Ihnen zu helfen.', 'weight' => 0],
    ['question' => 'Ваши симптомы могут изменяться со временем.', 'answer' => 'Ihre Symptome können sich im Laufe der Zeit verändern.', 'weight' => 0],
    ['question' => 'Если что-то изменится, сообщите мне.', 'answer' => 'Wenn sich etwas ändert, sagen Sie mir bitte Bescheid.', 'weight' => 0],
    ['question' => 'Мы будем внимательно следить за вашим состоянием.', 'answer' => 'Wir werden Ihren Zustand genau überwachen.', 'weight' => 0],
    ['question' => 'Не торопитесь, мы никуда не спешим.', 'answer' => 'Lassen Sie sich Zeit, wir haben es nicht eilig.', 'weight' => 0],
    ['question' => 'Ваше здоровье в надежных руках.', 'answer' => 'Ihre Gesundheit ist in guten Händen.', 'weight' => 0],
    ['question' => 'Вы сделали всё правильно, продолжайте.', 'answer' => 'Sie haben alles richtig gemacht, machen Sie weiter so.', 'weight' => 0],
    ['question' => 'Мы обеспечим вам необходимый уход.', 'answer' => 'Wir werden Ihnen die nötige Pflege zukommen lassen.', 'weight' => 0],
    ['question' => 'Я помогу вам справиться с болью.', 'answer' => 'Ich werde Ihnen helfen, die Schmerzen zu lindern.', 'weight' => 0],
    ['question' => 'Ваши мысли и переживания важны для нас.', 'answer' => 'Ihre Gedanken und Sorgen sind uns wichtig.', 'weight' => 0],
    ['question' => 'Мы понимаем, как это может быть трудно.', 'answer' => 'Wir verstehen, wie schwer das sein kann.', 'weight' => 0],
    ['question' => 'Ваше здоровье для нас приоритет.', 'answer' => 'Ihre Gesundheit hat für uns Priorität.', 'weight' => 0],
    ['question' => 'Мы работаем вместе, чтобы улучшить ваше состояние.', 'answer' => 'Wir arbeiten gemeinsam daran, Ihren Zustand zu verbessern.', 'weight' => 0],
    ['question' => 'Если вам станет хуже, немедленно сообщите.', 'answer' => 'Wenn es Ihnen schlechter geht, sagen Sie uns sofort Bescheid.', 'weight' => 0],
    ['question' => 'Ваше доверие для нас очень важно.', 'answer' => 'Ihr Vertrauen ist für uns sehr wichtig.', 'weight' => 0],
    ['question' => 'Мы делаем всё возможное, чтобы вам стало лучше.', 'answer' => 'Wir tun unser Bestes, damit es Ihnen besser geht.', 'weight' => 0],
    ['question' => 'Если вы чувствуете себя некомфортно, дайте знать.', 'answer' => 'Wenn Sie sich unwohl fühlen, lassen Sie es uns wissen.', 'weight' => 0],
    ['question' => 'Ваше состояние стабильно.', 'answer' => 'Ihr Zustand ist stabil.', 'weight' => 0],
    ['question' => 'Мы всегда рядом, если вам нужно поговорить.', 'answer' => 'Wir sind immer da, wenn Sie reden möchten.', 'weight' => 0],
    ['question' => 'Вам нужно будет отдыхать и избегать стресса.', 'answer' => 'Sie müssen sich ausruhen und Stress vermeiden.', 'weight' => 0],
    ['question' => 'Мы обсудим план лечения с вами.', 'answer' => 'Wir werden den Behandlungsplan mit Ihnen besprechen.', 'weight' => 0],
    ['question' => 'Вы можете задать любые вопросы о вашем лечении.', 'answer' => 'Sie können alle Fragen zu Ihrer Behandlung stellen.', 'weight' => 0],
    ['question' => 'Вам будет оказана вся необходимая помощь.', 'answer' => 'Ihnen wird alle notwendige Hilfe zuteil.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы облегчить ваши страдания.', 'answer' => 'Wir sind hier, um Ihr Leiden zu lindern.', 'weight' => 0],
    ['question' => 'Не стесняйтесь говорить о своих проблемах.', 'answer' => 'Scheuen Sie sich nicht, über Ihre Probleme zu sprechen.', 'weight' => 0],
    ['question' => 'Мы подберем для вас наилучшее лечение.', 'answer' => 'Wir werden die beste Behandlung für Sie auswählen.', 'weight' => 0],
    ['question' => 'Я покажу вам, как принимать лекарства.', 'answer' => 'Ich werde Ihnen zeigen, wie Sie die Medikamente einnehmen.', 'weight' => 0],
    ['question' => 'Мы будем проводить регулярные осмотры.', 'answer' => 'Wir werden regelmäßige Untersuchungen durchführen.', 'weight' => 0],
    ['question' => 'Пожалуйста, сообщите нам, если что-то изменится.', 'answer' => 'Bitte informieren Sie uns, wenn sich etwas ändert.', 'weight' => 0],
    ['question' => 'Вы можете рассчитывать на нашу поддержку.', 'answer' => 'Sie können auf unsere Unterstützung zählen.', 'weight' => 0],
    ['question' => 'Мы подробно объясним все этапы лечения.', 'answer' => 'Wir werden Ihnen alle Behandlungsschritte ausführlich erklären.', 'weight' => 0],
    ['question' => 'Ваше самочувствие очень важно для нас.', 'answer' => 'Ihr Wohlbefinden ist uns sehr wichtig.', 'weight' => 0],
    ['question' => 'Мы позаботимся, чтобы вы чувствовали себя комфортно.', 'answer' => 'Wir sorgen dafür, dass Sie sich wohl fühlen.', 'weight' => 0],
    ['question' => 'Мы будем с вами на протяжении всего процесса.', 'answer' => 'Wir werden während des gesamten Prozesses bei Ihnen sein.', 'weight' => 0],
    ['question' => 'Вы не одиноки в этом.', 'answer' => 'Sie sind damit nicht allein.', 'weight' => 0],
    ['question' => 'Мы будем работать вместе, чтобы улучшить ваше здоровье.', 'answer' => 'Wir werden gemeinsam daran arbeiten, Ihre Gesundheit zu verbessern.', 'weight' => 0],
    ['question' => 'Вам не нужно ничего бояться.', 'answer' => 'Sie müssen keine Angst haben.', 'weight' => 0],
    ['question' => 'Мы с вами на каждом этапе вашего лечения.', 'answer' => 'Wir sind bei jedem Schritt Ihrer Behandlung bei Ihnen.', 'weight' => 0],
    ['question' => 'Всё идет по плану, не беспокойтесь.', 'answer' => 'Alles verläuft nach Plan, keine Sorge.', 'weight' => 0],
    ['question' => 'Мы уделим вам столько времени, сколько нужно.', 'answer' => 'Wir nehmen uns so viel Zeit, wie Sie brauchen.', 'weight' => 0],
    ['question' => 'Мы будем помогать вам столько, сколько потребуется.', 'answer' => 'Wir werden Ihnen so lange helfen, wie es nötig ist.', 'weight' => 0],
    ['question' => 'Вы можете рассчитывать на наше полное внимание.', 'answer' => 'Sie können sich auf unsere volle Aufmerksamkeit verlassen.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы поддержать вас во всем.', 'answer' => 'Wir sind hier, um Sie in allem zu unterstützen.', 'weight' => 0],
    ['question' => 'Ваши усилия не останутся незамеченными.', 'answer' => 'Ihre Bemühungen bleiben nicht unbemerkt.', 'weight' => 0],
    ['question' => 'Мы уверены, что вы справитесь.', 'answer' => 'Wir sind sicher, dass Sie das schaffen.', 'weight' => 0],
    ['question' => 'Если у вас есть вопросы, всегда спрашивайте.', 'answer' => 'Wenn Sie Fragen haben, fragen Sie jederzeit.', 'weight' => 0],
    ['question' => 'Мы будем здесь, когда вам понадобимся.', 'answer' => 'Wir sind hier, wenn Sie uns brauchen.', 'weight' => 0],



    ['question' => 'гипертония, заболевание, при котором кровяное давление в артериях хронически повышено', 'answer' => 'Bluthochdruck, eine Erkrankung, bei der der Blutdruck in den Arterien chronisch erhöht ist', 'weight' => 0],
    ['question' => 'диабет, хроническое заболевание, характеризующееся высоким уровнем сахара в крови', 'answer' => 'Diabetes, eine chronische Erkrankung, die durch hohen Blutzuckerspiegel gekennzeichnet ist', 'weight' => 0],
    ['question' => 'сепсис, угрожающее жизни состояние, вызванное реакцией организма на инфекцию', 'answer' => 'Sepsis, eine lebensbedrohliche Reaktion des Körpers auf eine Infektion', 'weight' => 0],
    ['question' => 'перелом, нарушение целостности кости', 'answer' => 'Bruch, eine Unterbrechung der Kontinuität eines Knochens', 'weight' => 0],
    ['question' => 'инфаркт миокарда, сердечный приступ, вызванный блокировкой кровоснабжения сердечной мышцы', 'answer' => 'Myokardinfarkt, ein Herzinfarkt, verursacht durch eine Blockade der Blutversorgung des Herzmuskels', 'weight' => 0],
    ['question' => 'биопсия, забор образца ткани для диагностики заболеваний', 'answer' => 'Biopsie, die Entnahme von Gewebeproben zur Diagnose von Krankheiten', 'weight' => 0],
    ['question' => 'эндоскоп, гибкий инструмент для осмотра внутренних органов', 'answer' => 'Endoskop, ein flexibles Instrument zur Betrachtung des Inneren des Körpers', 'weight' => 0],
    ['question' => 'стетоскоп, инструмент для прослушивания звуков сердца и легких', 'answer' => 'Stethoskop, ein Instrument zum Abhören von Herz- und Lungengeräuschen', 'weight' => 0],
    ['question' => 'внутривенное введение, введение жидкостей или медикаментов непосредственно в вену', 'answer' => 'intravenöse Verabreichung, die Verabreichung von Flüssigkeiten oder Medikamenten direkt in eine Vene', 'weight' => 0],
    ['question' => 'DNR, распоряжение не проводить реанимационные мероприятия в случае остановки сердца', 'answer' => 'DNR, eine Anweisung, keine Wiederbelebungsmaßnahmen im Falle eines Herzstillstands durchzuführen', 'weight' => 0],
    ['question' => 'анемия, состояние, при котором в крови снижено количество эритроцитов', 'answer' => 'Anämie, ein Zustand, bei dem das Blut eine verringerte Anzahl roter Blutkörperchen aufweist', 'weight' => 0],
    ['question' => 'гипогликемия, состояние, характеризующееся аномально низким уровнем сахара в крови', 'answer' => 'Hypoglykämie, ein abnorm niedriger Blutzuckerspiegel', 'weight' => 0],
    ['question' => 'аритмия, нарушение ритма сердечных сокращений', 'answer' => 'Arrhythmie, eine Unregelmäßigkeit des Herzschlags', 'weight' => 0],
    ['question' => 'остеопороз, заболевание, при котором кости теряют плотность и становятся хрупкими', 'answer' => 'Osteoporose, eine Erkrankung, bei der die Knochen an Dichte verlieren und brüchig werden', 'weight' => 0],
    ['question' => 'глаукома, заболевание глаз, которое повреждает зрительный нерв и может привести к слепоте', 'answer' => 'Glaukom, eine Augenerkrankung, die den Sehnerv schädigt und zur Erblindung führen kann', 'weight' => 0],
    ['question' => 'пневмония, воспаление легких, часто вызванное инфекцией', 'answer' => 'Pneumonie, eine Entzündung der Lunge, oft durch Infektion verursacht', 'weight' => 0],
    ['question' => 'гепатит, воспаление печени, вызванное вирусами или другими факторами', 'answer' => 'Hepatitis, eine Entzündung der Leber, die durch Viren oder andere Faktoren verursacht wird', 'weight' => 0],
    ['question' => 'инсульт, медицинская чрезвычайная ситуация, вызванная нарушением кровоснабжения мозга', 'answer' => 'Schlaganfall, ein medizinischer Notfall, der durch eine Unterbrechung der Blutversorgung des Gehirns verursacht wird', 'weight' => 0],
    ['question' => 'гипотония, состояние, характеризующееся аномально низким кровяным давлением', 'answer' => 'Hypotonie, ein Zustand, bei dem der Blutdruck ungewöhnlich niedrig ist', 'weight' => 0],
    ['question' => 'отит, воспаление уха, часто вызванное инфекцией', 'answer' => 'Otitis, eine Entzündung des Ohrs, oft durch Infektion verursacht', 'weight' => 0],





    ['question' => 'астма, хроническое воспалительное заболевание дыхательных путей, характеризующееся приступами одышки и кашля', 'answer' => 'Asthma, eine chronisch entzündliche Erkrankung der Atemwege, gekennzeichnet durch Atemnot und Hustenanfälle', 'weight' => 0],
    ['question' => 'ревматоидный артрит, аутоиммунное заболевание, вызывающее воспаление суставов', 'answer' => 'Rheumatoide Arthritis, eine Autoimmunerkrankung, die Entzündungen in den Gelenken verursacht', 'weight' => 0],
    ['question' => 'желудочная язва, открытая рана на слизистой оболочке желудка или двенадцатиперстной кишки', 'answer' => 'Magengeschwür, eine offene Wunde auf der Magenschleimhaut oder im Zwölffingerdarm', 'weight' => 0],
    ['question' => 'аневризма, расширение и истончение стенки артерии, что может привести к разрыву', 'answer' => 'Aneurysma, eine Ausdehnung und Verdünnung der Arterienwand, die zum Bruch führen kann', 'weight' => 0],
    ['question' => 'геморрой, воспаленные вены в нижней части прямой кишки, вызывающие боль и кровотечение', 'answer' => 'Hämorrhoiden, entzündete Venen im unteren Teil des Rektums, die Schmerzen und Blutungen verursachen', 'weight' => 0],
    ['question' => 'конъюнктивит, воспаление слизистой оболочки глаза, часто вызванное инфекцией', 'answer' => 'Konjunktivitis, eine Entzündung der Bindehaut des Auges, oft durch eine Infektion verursacht', 'weight' => 0],
    ['question' => 'панкреатит, воспаление поджелудочной железы, которое может привести к серьезным осложнениям', 'answer' => 'Pankreatitis, eine Entzündung der Bauchspeicheldrüse, die zu ernsthaften Komplikationen führen kann', 'weight' => 0],
    ['question' => 'гипертиреоз, состояние, при котором щитовидная железа вырабатывает избыточное количество гормонов', 'answer' => 'Hyperthyreose, ein Zustand, bei dem die Schilddrüse eine übermäßige Menge an Hormonen produziert', 'weight' => 0],
    ['question' => 'цирроз, хроническое заболевание печени, характеризующееся замещением нормальной ткани фиброзной', 'answer' => 'Zirrhose, eine chronische Lebererkrankung, die durch den Ersatz von normalem Gewebe durch fibröses Gewebe gekennzeichnet ist', 'weight' => 0],
    ['question' => 'грыжа, выхождение органа или его части через отверстие в мышечной или тканевой стенке', 'answer' => 'Hernie, das Austreten eines Organs oder eines Teils davon durch eine Öffnung in der Muskel- oder Gewebewand', 'weight' => 0],
    ['question' => 'апноэ, временная остановка дыхания, особенно во время сна', 'answer' => 'Apnoe, eine vorübergehende Unterbrechung der Atmung, besonders während des Schlafs', 'weight' => 0],
    ['question' => 'менингит, воспаление оболочек головного и спинного мозга, часто вызванное инфекцией', 'answer' => 'Meningitis, eine Entzündung der Hirn- und Rückenmarkshäute, oft durch eine Infektion verursacht', 'weight' => 0],
    ['question' => 'псориаз, хроническое аутоиммунное заболевание, вызывающее быстрое накопление клеток кожи', 'answer' => 'Psoriasis, eine chronische Autoimmunerkrankung, die eine schnelle Ansammlung von Hautzellen verursacht', 'weight' => 0],
    ['question' => 'анорексия, расстройство питания, характеризующееся страхом перед набором веса и отказом от пищи', 'answer' => 'Anorexie, eine Essstörung, die durch Angst vor Gewichtszunahme und Nahrungsverweigerung gekennzeichnet ist', 'weight' => 0],
    ['question' => 'глаукома, повышенное давление в глазу, которое может привести к повреждению зрительного нерва и слепоте', 'answer' => 'Glaukom, ein erhöhter Druck im Auge, der zu Schäden am Sehnerv und Blindheit führen kann', 'weight' => 0],
    ['question' => 'остеоартрит, дегенеративное заболевание суставов, вызывающее боль и скованность', 'answer' => 'Osteoarthritis, eine degenerative Gelenkerkrankung, die Schmerzen und Steifheit verursacht', 'weight' => 0],
    ['question' => 'эпилепсия, неврологическое расстройство, характеризующееся повторяющимися судорогами', 'answer' => 'Epilepsie, eine neurologische Störung, die durch wiederkehrende Anfälle gekennzeichnet ist', 'weight' => 0],
    ['question' => 'холецистит, воспаление желчного пузыря, часто вызванное желчными камнями', 'answer' => 'Cholezystitis, eine Entzündung der Gallenblase, oft durch Gallensteine verursacht', 'weight' => 0],
    ['question' => 'синдром раздраженного кишечника, хроническое заболевание желудочно-кишечного тракта, вызывающее боль и дискомфорт в животе', 'answer' => 'Reizdarmsyndrom, eine chronische Erkrankung des Verdauungstrakts, die Bauchschmerzen und Unwohlsein verursacht', 'weight' => 0],
    ['question' => 'варикозное расширение вен, увеличение и извилистость вен, часто на ногах, вызывающие дискомфорт и боль', 'answer' => 'Krampfadern, eine Erweiterung und Schlangenbildung der Venen, oft in den Beinen, die Unbehagen und Schmerzen verursacht', 'weight' => 0],


    ['question' => 'артериосклероз, заболевание, при котором артерии утолщаются и теряют эластичность', 'answer' => 'Arteriosklerose, eine Krankheit, bei der die Arterien verdicken und ihre Elastizität verlieren', 'weight' => 0],
    ['question' => 'анемия, состояние, характеризующееся низким уровнем гемоглобина в крови', 'answer' => 'Anämie, ein Zustand, der durch einen niedrigen Hämoglobinspiegel im Blut gekennzeichnet ist', 'weight' => 0],
    ['question' => 'бронхит, воспаление бронхов, вызывающее кашель и затрудненное дыхание', 'answer' => 'Bronchitis, eine Entzündung der Bronchien, die Husten und Atembeschwerden verursacht', 'weight' => 0],
    ['question' => 'цистит, воспаление мочевого пузыря, часто сопровождающееся болезненным мочеиспусканием', 'answer' => 'Zystitis, eine Entzündung der Blase, die oft von schmerzhaftem Wasserlassen begleitet wird', 'weight' => 0],
    ['question' => 'флебит, воспаление вены, часто сопровождаемое болью и покраснением', 'answer' => 'Phlebitis, eine Entzündung einer Vene, die oft mit Schmerzen und Rötung einhergeht', 'weight' => 0],
    ['question' => 'гиперемия, повышенное кровенаполнение ткани или органа, вызывающее покраснение', 'answer' => 'Hyperämie, eine erhöhte Blutfüllung eines Gewebes oder Organs, die Rötung verursacht', 'weight' => 0],
    ['question' => 'инфаркт, омертвение участка ткани из-за прекращения кровоснабжения', 'answer' => 'Infarkt, das Absterben eines Gewebebereichs aufgrund unterbrochener Blutversorgung', 'weight' => 0],
    ['question' => 'железодефицитная анемия, анемия, вызванная недостатком железа в организме', 'answer' => 'Eisenmangelanämie, eine Anämie, die durch Eisenmangel im Körper verursacht wird', 'weight' => 0],
    ['question' => 'гепатит B, вирусная инфекция, поражающая печень и вызывающая воспаление', 'answer' => 'Hepatitis B, eine Virusinfektion, die die Leber befällt und eine Entzündung verursacht', 'weight' => 0],
    ['question' => 'остеомиелит, воспаление костного мозга, часто вызванное инфекцией', 'answer' => 'Osteomyelitis, eine Entzündung des Knochenmarks, oft durch eine Infektion verursacht', 'weight' => 0],
    ['question' => 'перитонит, воспаление брюшины, оболочки, выстилающей брюшную полость', 'answer' => 'Peritonitis, eine Entzündung des Peritoneums, der Membran, die die Bauchhöhle auskleidet', 'weight' => 0],
    ['question' => 'ревматизм, хроническое воспалительное заболевание суставов и соединительных тканей', 'answer' => 'Rheumatismus, eine chronische entzündliche Erkrankung der Gelenke und des Bindegewebes', 'weight' => 0],
    ['question' => 'сколиоз, искривление позвоночника вбок, которое может вызывать боль и нарушения осанки', 'answer' => 'Skoliose, eine seitliche Verkrümmung der Wirbelsäule, die Schmerzen und Haltungsschäden verursachen kann', 'weight' => 0],
    ['question' => 'стенокардия, боль в груди, вызванная недостатком кровоснабжения сердечной мышцы', 'answer' => 'Angina pectoris, Schmerzen in der Brust, verursacht durch unzureichende Blutversorgung des Herzmuskels', 'weight' => 0],
    ['question' => 'тахикардия, ускоренное сердцебиение, которое может быть вызвано различными факторами', 'answer' => 'Tachykardie, ein beschleunigter Herzschlag, der durch verschiedene Faktoren verursacht werden kann', 'weight' => 0],
    ['question' => 'тромбофлебит, воспаление вены с образованием тромба, вызывающее боль и отек', 'answer' => 'Thrombophlebitis, eine Entzündung einer Vene mit Blutgerinnselbildung, die Schmerzen und Schwellungen verursacht', 'weight' => 0],
    ['question' => 'ушиб, повреждение ткани с кровоизлиянием, не сопровождающееся нарушением целостности кожи', 'answer' => 'Prellung, eine Gewebeverletzung mit Bluterguss, die nicht mit Hautbruch einhergeht', 'weight' => 0],
    ['question' => 'фибромиалгия, хроническое заболевание, характеризующееся болью в мышцах и мягких тканях по всему телу', 'answer' => 'Fibromyalgie, eine chronische Erkrankung, die durch Schmerzen in den Muskeln und Weichteilen im ganzen Körper gekennzeichnet ist', 'weight' => 0],
    ['question' => 'холецистит, воспаление желчного пузыря, часто вызванное желчными камнями', 'answer' => 'Cholezystitis, eine Entzündung der Gallenblase, oft durch Gallensteine verursacht', 'weight' => 0],
    ['question' => 'цирроз, тяжелое хроническое заболевание печени, приводящее к разрушению ткани печени', 'answer' => 'Zirrhose, eine schwere chronische Lebererkrankung, die zum Abbau von Lebergewebe führt', 'weight' => 0],



    ['question' => 'Мы с вами, и вы справитесь.', 'answer' => 'Wir sind bei Ihnen, und Sie werden das schaffen.', 'weight' => 0],
    ['question' => 'Все, что вы чувствуете, это нормально.', 'answer' => 'Alles, was Sie fühlen, ist normal.', 'weight' => 0],
    ['question' => 'Вы имеете право испытывать эти эмоции.', 'answer' => 'Sie haben das Recht, diese Emotionen zu fühlen.', 'weight' => 0],
    ['question' => 'Вы можете на нас положиться в любой момент.', 'answer' => 'Sie können sich jederzeit auf uns verlassen.', 'weight' => 0],
    ['question' => 'Мы будем поддерживать вас на каждом шагу.', 'answer' => 'Wir werden Sie bei jedem Schritt unterstützen.', 'weight' => 0],
    ['question' => 'Вы сильнее, чем вам кажется.', 'answer' => 'Sie sind stärker, als Sie denken.', 'weight' => 0],
    ['question' => 'Мы вас не оставим.', 'answer' => 'Wir werden Sie nicht allein lassen.', 'weight' => 0],
    ['question' => 'Ваше благополучие для нас на первом месте.', 'answer' => 'Ihr Wohlbefinden steht für uns an erster Stelle.', 'weight' => 0],
    ['question' => 'Мы понимаем, через что вы проходите.', 'answer' => 'Wir verstehen, was Sie durchmachen.', 'weight' => 0],
    ['question' => 'Ваши чувства важны.', 'answer' => 'Ihre Gefühle sind wichtig.', 'weight' => 0],
    ['question' => 'Вам не нужно проходить через это в одиночку.', 'answer' => 'Sie müssen das nicht alleine durchstehen.', 'weight' => 0],
    ['question' => 'Мы сделаем все возможное, чтобы помочь вам.', 'answer' => 'Wir werden alles tun, um Ihnen zu helfen.', 'weight' => 0],
    ['question' => 'Вы можете говорить о том, что вас беспокоит.', 'answer' => 'Sie können über das sprechen, was Sie beunruhigt.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы поддержать вас.', 'answer' => 'Wir sind hier, um Sie zu unterstützen.', 'weight' => 0],
    ['question' => 'Ваши переживания важны для нас.', 'answer' => 'Ihre Sorgen sind uns wichtig.', 'weight' => 0],
    ['question' => 'Не стесняйтесь выражать свои эмоции.', 'answer' => 'Scheuen Sie sich nicht, Ihre Emotionen auszudrücken.', 'weight' => 0],
    ['question' => 'Ваше здоровье улучшится, мы вместе справимся.', 'answer' => 'Ihre Gesundheit wird sich verbessern, wir schaffen das zusammen.', 'weight' => 0],
    ['question' => 'Вы не должны держать все в себе.', 'answer' => 'Sie müssen nicht alles in sich hineinfressen.', 'weight' => 0],
    ['question' => 'Мы гордимся вашей силой и мужеством.', 'answer' => 'Wir sind stolz auf Ihre Stärke und Ihren Mut.', 'weight' => 0],
    ['question' => 'Не спешите, все идет своим чередом.', 'answer' => 'Lassen Sie sich Zeit, alles wird seinen Lauf nehmen.', 'weight' => 0],
    ['question' => 'Вы делаете отличную работу, продолжайте в том же духе.', 'answer' => 'Sie machen großartige Fortschritte, machen Sie weiter so.', 'weight' => 0],
    ['question' => 'Мы рады, что вы открыты с нами.', 'answer' => 'Wir freuen uns, dass Sie offen mit uns sprechen.', 'weight' => 0],
    ['question' => 'Каждый день приносит улучшения.', 'answer' => 'Jeden Tag gibt es Fortschritte.', 'weight' => 0],
    ['question' => 'Вы не одиноки в этом.', 'answer' => 'Sie sind nicht allein damit.', 'weight' => 0],
    ['question' => 'Мы вас поддержим на каждом этапе.', 'answer' => 'Wir werden Sie in jeder Phase unterstützen.', 'weight' => 0],
    ['question' => 'Ваши страхи вполне понятны.', 'answer' => 'Ihre Ängste sind vollkommen verständlich.', 'weight' => 0],
    ['question' => 'Мы здесь, чтобы разделить вашу ношу.', 'answer' => 'Wir sind hier, um Ihre Last zu teilen.', 'weight' => 0],
    ['question' => 'Не бойтесь задавать вопросы.', 'answer' => 'Scheuen Sie sich nicht, Fragen zu stellen.', 'weight' => 0],
    ['question' => 'Мы будем рядом столько, сколько потребуется.', 'answer' => 'Wir werden so lange bei Ihnen bleiben, wie es nötig ist.', 'weight' => 0],
    ['question' => 'Вы справитесь с этим, и мы будем рядом.', 'answer' => 'Sie werden das schaffen, und wir werden an Ihrer Seite sein.', 'weight' => 0],



    ['question' => 'головной мозг, центральный орган нервной системы, управляющий всеми функциями организма', 'answer' => 'Gehirn, das zentrale Organ des Nervensystems, das alle Funktionen des Körpers steuert', 'weight' => 0],
    ['question' => 'позвоночник, столб костей, поддерживающий туловище и защищающий спинной мозг', 'answer' => 'Wirbelsäule, eine Reihe von Knochen, die den Rumpf stützt und das Rückenmark schützt', 'weight' => 0],
    ['question' => 'сердце, мышечный орган, перекачивающий кровь по всему организму', 'answer' => 'Herz, ein muskuläres Organ, das Blut durch den ganzen Körper pumpt', 'weight' => 0],
    ['question' => 'легкие, парные органы, обеспечивающие газообмен между воздухом и кровью', 'answer' => 'Lungen, paarige Organe, die den Gasaustausch zwischen Luft und Blut ermöglichen', 'weight' => 0],
    ['question' => 'печень, крупная железа, играющая важную роль в обмене веществ и детоксикации организма', 'answer' => 'Leber, eine große Drüse, die eine wichtige Rolle im Stoffwechsel und in der Entgiftung des Körpers spielt', 'weight' => 0],
    ['question' => 'почки, парные органы, фильтрующие кровь и образующие мочу', 'answer' => 'Nieren, paarige Organe, die das Blut filtern und Urin bilden', 'weight' => 0],
    ['question' => 'желудок, орган пищеварительной системы, в котором начинается переваривание пищи', 'answer' => 'Magen, ein Organ des Verdauungssystems, in dem die Verdauung der Nahrung beginnt', 'weight' => 0],
    ['question' => 'кишечник, длинная трубка, по которой пища движется от желудка к анальному отверстию, где происходит всасывание питательных веществ', 'answer' => 'Darm, ein langer Schlauch, durch den sich Nahrung vom Magen zum Anus bewegt, wo Nährstoffe aufgenommen werden', 'weight' => 0],
    ['question' => 'селезенка, орган, играющий роль в иммунной системе и кроветворении', 'answer' => 'Milz, ein Organ, das eine Rolle im Immunsystem und bei der Blutbildung spielt', 'weight' => 0],
    ['question' => 'поджелудочная железа, орган, вырабатывающий инсулин и другие важные ферменты для пищеварения', 'answer' => 'Bauchspeicheldrüse, ein Organ, das Insulin und andere wichtige Verdauungsenzyme produziert', 'weight' => 0],
    ['question' => 'костный мозг, мягкая ткань внутри костей, которая производит клетки крови', 'answer' => 'Knochenmark, weiches Gewebe im Inneren der Knochen, das Blutzellen produziert', 'weight' => 0],
    ['question' => 'лимфатические узлы, небольшие образования, которые фильтруют лимфу и помогают организму бороться с инфекциями', 'answer' => 'Lymphknoten, kleine Strukturen, die Lymphe filtern und dem Körper helfen, Infektionen zu bekämpfen', 'weight' => 0],
    ['question' => 'аорта, основная артерия, несущая кровь от сердца ко всем органам и тканям тела', 'answer' => 'Aorta, die Hauptarterie, die Blut vom Herzen zu allen Organen und Geweben des Körpers transportiert', 'weight' => 0],
    ['question' => 'гортань, орган, участвующий в голосообразовании и защите дыхательных путей', 'answer' => 'Kehlkopf, ein Organ, das an der Stimmbildung und dem Schutz der Atemwege beteiligt ist', 'weight' => 0],
    ['question' => 'пищевод, трубка, по которой пища перемещается из глотки в желудок', 'answer' => 'Speiseröhre, ein Schlauch, durch den Nahrung vom Rachen zum Magen gelangt', 'weight' => 0],
    ['question' => 'мышцы, ткани, способные сокращаться и обеспечивающие движение частей тела', 'answer' => 'Muskeln, Gewebe, die sich zusammenziehen können und die Bewegung von Körperteilen ermöglichen', 'weight' => 0],
    ['question' => 'сухожилия, соединительные ткани, связывающие мышцы с костями', 'answer' => 'Sehnen, Bindegewebe, die Muskeln mit Knochen verbinden', 'weight' => 0],
    ['question' => 'нервы, волокна, передающие электрические импульсы между мозгом и другими частями тела', 'answer' => 'Nerven, Fasern, die elektrische Impulse zwischen dem Gehirn und anderen Körperteilen übertragen', 'weight' => 0],
    ['question' => 'артерии, кровеносные сосуды, переносящие кровь от сердца к органам и тканям', 'answer' => 'Arterien, Blutgefäße, die Blut vom Herzen zu den Organen und Geweben transportieren', 'weight' => 0],
    ['question' => 'вены, кровеносные сосуды, возвращающие кровь от органов и тканей к сердцу', 'answer' => 'Venen, Blutgefäße, die Blut von den Organen und Geweben zum Herzen zurückführen', 'weight' => 0],


    ['question' => 'брюшная полость, пространство в теле, содержащее органы пищеварения и другие внутренние органы', 'answer' => 'Bauchhöhle, der Raum im Körper, der die Verdauungsorgane und andere innere Organe enthält', 'weight' => 0],
    ['question' => 'гипофиз, маленькая железа в мозгу, регулирующая множество важных функций организма', 'answer' => 'Hypophyse, eine kleine Drüse im Gehirn, die viele wichtige Körperfunktionen reguliert', 'weight' => 0],
    ['question' => 'эпидермис, внешний слой кожи, защищающий организм от окружающей среды', 'answer' => 'Epidermis, die äußere Schicht der Haut, die den Körper vor der Umwelt schützt', 'weight' => 0],
    ['question' => 'коронарные артерии, артерии, снабжающие кровью сердечную мышцу', 'answer' => 'Koronararterien, die Arterien, die den Herzmuskel mit Blut versorgen', 'weight' => 0],
    ['question' => 'гипоталамус, область мозга, контролирующая важные функции, такие как температура тела и чувство голода', 'answer' => 'Hypothalamus, ein Bereich des Gehirns, der wichtige Funktionen wie Körpertemperatur und Hunger kontrolliert', 'weight' => 0],
    ['question' => 'желчный пузырь, орган, в котором хранится и концентрируется желчь для переваривания жиров', 'answer' => 'Gallenblase, ein Organ, das Galle zur Verdauung von Fetten speichert und konzentriert', 'weight' => 0],
    ['question' => 'надпочечники, железы, расположенные над почками, которые выделяют гормоны стресса', 'answer' => 'Nebennieren, Drüsen über den Nieren, die Stresshormone ausschütten', 'weight' => 0],
    ['question' => 'связки, плотные соединительные ткани, соединяющие кости между собой и стабилизирующие суставы', 'answer' => 'Bänder, dichte Bindegewebe, die Knochen miteinander verbinden und die Gelenke stabilisieren', 'weight' => 0],
    ['question' => 'чревный нерв, крупный нерв, идущий от спинного мозга к внутренним органам и контролирующий их функции', 'answer' => 'Solarplexus, ein großer Nerv, der vom Rückenmark zu den inneren Organen verläuft und deren Funktionen steuert', 'weight' => 0],
    ['question' => 'базальные ганглии, структуры в мозге, участвующие в координации движений', 'answer' => 'Basalganglien, Strukturen im Gehirn, die an der Bewegungskoordination beteiligt sind', 'weight' => 0],
    ['question' => 'вилочковая железа, орган иммунной системы, важный для развития Т-клеток', 'answer' => 'Thymusdrüse, ein Organ des Immunsystems, das wichtig für die Entwicklung der T-Zellen ist', 'weight' => 0],
    ['question' => 'чревная артерия, основная артерия, снабжающая кровью органы брюшной полости', 'answer' => 'Zöliakiearterie, die Hauptarterie, die die Organe der Bauchhöhle mit Blut versorgt', 'weight' => 0],
    ['question' => 'селезенка, орган, фильтрующий кровь и участвующий в иммунной защите организма', 'answer' => 'Milz, ein Organ, das Blut filtert und am Immunschutz des Körpers beteiligt ist', 'weight' => 0],
    ['question' => 'межпозвоночные диски, хрящевые структуры, действующие как амортизаторы между позвонками', 'answer' => 'Bandscheiben, knorpelige Strukturen, die als Stoßdämpfer zwischen den Wirbeln fungieren', 'weight' => 0],
    ['question' => 'эпителий, слой клеток, покрывающий поверхности тела и внутренних органов, обеспечивающий защиту и абсорбцию', 'answer' => 'Epithel, eine Zellschicht, die die Oberflächen des Körpers und der inneren Organe bedeckt und Schutz und Absorption bietet', 'weight' => 0],
    ['question' => 'плевра, оболочка, покрывающая легкие и выстилающая грудную полость, обеспечивающая их плавное движение при дыхании', 'answer' => 'Pleura, die Membran, die die Lungen bedeckt und die Brusthöhle auskleidet und für eine reibungslose Bewegung beim Atmen sorgt', 'weight' => 0],
    ['question' => 'спинной мозг, часть центральной нервной системы, проходящая через позвоночник и передающая сигналы между мозгом и телом', 'answer' => 'Rückenmark, ein Teil des zentralen Nervensystems, der durch die Wirbelsäule verläuft und Signale zwischen Gehirn und Körper überträgt', 'weight' => 0],
    ['question' => 'лимфа, бесцветная жидкость, циркулирующая в лимфатической системе и играющая важную роль в иммунной защите', 'answer' => 'Lymphe, eine farblose Flüssigkeit, die im Lymphsystem zirkuliert und eine wichtige Rolle im Immunschutz spielt', 'weight' => 0],
    ['question' => 'перикард, оболочка, окружающая сердце и защищающая его', 'answer' => 'Perikard, die Membran, die das Herz umgibt und schützt', 'weight' => 0],
    ['question' => 'гортанные мышцы, мышцы, участвующие в движении голосовых связок и образовании звуков', 'answer' => 'Kehlkopfmuskeln, Muskeln, die an der Bewegung der Stimmbänder und der Bildung von Lauten beteiligt sind', 'weight' => 0],


    ['question' => 'Как вы себя чувствуете?', 'answer' => 'Wie fühlen Sie sich?', 'weight' => 0],
    ['question' => 'Пожалуйста, расслабьтесь.', 'answer' => 'Bitte entspannen Sie sich.', 'weight' => 0],
    ['question' => 'Я собираюсь сделать вам укол.', 'answer' => 'Ich werde Ihnen eine Spritze geben.', 'weight' => 0],
    ['question' => 'Это может немного болеть.', 'answer' => 'Es könnte ein wenig wehtun.', 'weight' => 0],
    ['question' => 'Сейчас я возьму у вас кровь.', 'answer' => 'Ich werde Ihnen jetzt Blut abnehmen.', 'weight' => 0],
    ['question' => 'Скажите, если почувствуете боль.', 'answer' => 'Sagen Sie mir Bescheid, wenn Sie Schmerzen spüren.', 'weight' => 0],
    ['question' => 'Не волнуйтесь, это безопасно.', 'answer' => 'Keine Sorge, das ist sicher.', 'weight' => 0],
    ['question' => 'Я использую стерильный шприц.', 'answer' => 'Ich benutze eine sterile Spritze.', 'weight' => 0],
    ['question' => 'Сделайте глубокий вдох и выдох.', 'answer' => 'Atmen Sie tief ein und aus.', 'weight' => 0],
    ['question' => 'Вы готовы к инъекции?', 'answer' => 'Sind Sie bereit für die Injektion?', 'weight' => 0],
    ['question' => 'Процедура будет быстрой.', 'answer' => 'Der Eingriff wird schnell sein.', 'weight' => 0],
    ['question' => 'Пожалуйста, держите руку неподвижно.', 'answer' => 'Bitte halten Sie Ihren Arm ruhig.', 'weight' => 0],
    ['question' => 'Если вам станет плохо, скажите мне.', 'answer' => 'Wenn Ihnen schlecht wird, sagen Sie mir bitte Bescheid.', 'weight' => 0],
    ['question' => 'Я сделаю вам обезболивающий укол.', 'answer' => 'Ich werde Ihnen eine schmerzlindernde Injektion geben.', 'weight' => 0],
    ['question' => 'Сейчас я введу лекарство.', 'answer' => 'Ich werde Ihnen jetzt das Medikament verabreichen.', 'weight' => 0],
    ['question' => 'После инъекции вы можете почувствовать легкое жжение.', 'answer' => 'Nach der Injektion könnten Sie ein leichtes Brennen verspüren.', 'weight' => 0],
    ['question' => 'Вам нужно будет остаться в покое несколько минут.', 'answer' => 'Sie müssen ein paar Minuten ruhig bleiben.', 'weight' => 0],
    ['question' => 'Мы закончили, можете отдохнуть.', 'answer' => 'Wir sind fertig, Sie können sich jetzt ausruhen.', 'weight' => 0],
    ['question' => 'Не двигайтесь, пожалуйста, пока я не закончу.', 'answer' => 'Bitte bewegen Sie sich nicht, bis ich fertig bin.', 'weight' => 0],
    ['question' => 'Я проверю вашу реакцию на лекарство.', 'answer' => 'Ich werde Ihre Reaktion auf das Medikament überprüfen.', 'weight' => 0],

    ['question' => 'У меня болит голова.', 'answer' => 'Ich habe Kopfschmerzen.', 'weight' => 0],
    ['question' => 'У меня кружится голова.', 'answer' => 'Mir ist schwindlig.', 'weight' => 0],
    ['question' => 'Мне тяжело дышать.', 'answer' => 'Es fällt mir schwer zu atmen.', 'weight' => 0],
    ['question' => 'Я чувствую слабость.', 'answer' => 'Ich fühle mich schwach.', 'weight' => 0],
    ['question' => 'У меня боль в груди.', 'answer' => 'Ich habe Schmerzen in der Brust.', 'weight' => 0],
    ['question' => 'У меня тошнота.', 'answer' => 'Mir ist übel.', 'weight' => 0],
    ['question' => 'У меня озноб.', 'answer' => 'Ich habe Schüttelfrost.', 'weight' => 0],
    ['question' => 'Я чувствую жар.', 'answer' => 'Ich habe Fieber.', 'weight' => 0],
    ['question' => 'Моя рука/нога болит.', 'answer' => 'Mein Arm/Bein tut weh.', 'weight' => 0],
    ['question' => 'У меня болит живот.', 'answer' => 'Ich habe Bauchschmerzen.', 'weight' => 0],
    ['question' => 'Я чувствую покалывание в пальцах.', 'answer' => 'Ich spüre ein Kribbeln in den Fingern.', 'weight' => 0],
    ['question' => 'У меня боли в суставах.', 'answer' => 'Ich habe Gelenkschmerzen.', 'weight' => 0],
    ['question' => 'Моё сердце сильно бьется.', 'answer' => 'Mein Herz schlägt stark.', 'weight' => 0],
    ['question' => 'У меня зуд.', 'answer' => 'Ich habe Juckreiz.', 'weight' => 0],
    ['question' => 'Мне очень холодно.', 'answer' => 'Mir ist sehr kalt.', 'weight' => 0],
    ['question' => 'Я не могу уснуть.', 'answer' => 'Ich kann nicht schlafen.', 'weight' => 0],
    ['question' => 'Я часто чувствую усталость.', 'answer' => 'Ich fühle mich oft müde.', 'weight' => 0],
    ['question' => 'У меня нет аппетита.', 'answer' => 'Ich habe keinen Appetit.', 'weight' => 0],
    ['question' => 'Моё зрение ухудшилось.', 'answer' => 'Mein Sehvermögen hat sich verschlechtert.', 'weight' => 0],
    ['question' => 'Я чувствую боль в спине.', 'answer' => 'Ich habe Rückenschmerzen.', 'weight' => 0],

    ['question' => 'У меня сухость во рту.', 'answer' => 'Ich habe Mundtrockenheit.', 'weight' => 0],
    ['question' => 'У меня шум в ушах.', 'answer' => 'Ich habe Ohrgeräusche.', 'weight' => 0],
    ['question' => 'Я чувствую давление в голове.', 'answer' => 'Ich spüre einen Druck im Kopf.', 'weight' => 0],
    ['question' => 'Мне трудно глотать.', 'answer' => 'Es fällt mir schwer zu schlucken.', 'weight' => 0],
    ['question' => 'Моё сердце бьется нерегулярно.', 'answer' => 'Mein Herz schlägt unregelmäßig.', 'weight' => 0],
    ['question' => 'У меня онемение в ногах.', 'answer' => 'Ich habe Taubheitsgefühl in den Beinen.', 'weight' => 0],
    ['question' => 'Я потерял сознание. )))))))', 'answer' => 'Ich bin ohnmächtig geworden.', 'weight' => 0],
    ['question' => 'У меня болят глаза.', 'answer' => 'Meine Augen tun weh.', 'weight' => 0],
    ['question' => 'Я чувствую жжение при мочеиспускании.', 'answer' => 'Es brennt beim Wasserlassen.', 'weight' => 0],
    ['question' => 'У меня нет сил в руках/ногах.', 'answer' => 'Ich habe keine Kraft in den Armen/Beinen.', 'weight' => 0],
    ['question' => 'Мне кажется, что я теряю равновесие.', 'answer' => 'Ich habe das Gefühl, das Gleichgewicht zu verlieren.', 'weight' => 0],
    ['question' => 'Я слышу шумы, которых нет.', 'answer' => 'Ich höre Geräusche, die nicht da sind.', 'weight' => 0],
    ['question' => 'У меня кровь из носа.', 'answer' => 'Ich habe Nasenbluten.', 'weight' => 0],
    ['question' => 'Я потерял аппетит.', 'answer' => 'Ich habe den Appetit verloren.', 'weight' => 0],
    ['question' => 'Мой живот вздут.', 'answer' => 'Mein Bauch ist aufgebläht.', 'weight' => 0],
    ['question' => 'У меня высыпание на коже.', 'answer' => 'Ich habe einen Hautausschlag.', 'weight' => 0],
    ['question' => 'Я чувствую острую боль.', 'answer' => 'Ich fühle einen stechenden Schmerz.', 'weight' => 0],
    ['question' => 'Мне кажется, что у меня жар.', 'answer' => 'Ich glaube, ich habe Fieber.', 'weight' => 0],
    ['question' => 'Мой пульс учащённый.', 'answer' => 'Mein Puls ist beschleunigt.', 'weight' => 0],
    ['question' => 'У меня боль в шее.', 'answer' => 'Ich habe Nackenschmerzen.', 'weight' => 0],
    ['question' => 'Я очень сильно потею.', 'answer' => 'Ich schwitze sehr stark.', 'weight' => 0],
    ['question' => 'У меня проблемы с концентрацией.', 'answer' => 'Ich habe Konzentrationsprobleme.', 'weight' => 0],
    ['question' => 'Моя моча изменила цвет.', 'answer' => 'Mein Urin hat die Farbe verändert.', 'weight' => 0],
    ['question' => 'Я заметил изменение в стуле.', 'answer' => 'Ich habe eine Veränderung im Stuhl bemerkt.', 'weight' => 0],

    ['question' => 'У меня болят кости.', 'answer' => 'Meine Knochen tun weh.', 'weight' => 0],
    ['question' => 'Мне тяжело двигаться.', 'answer' => 'Es fällt mir schwer, mich zu bewegen.', 'weight' => 0],
    ['question' => 'У меня затрудненное мочеиспускание.', 'answer' => 'Ich habe Schwierigkeiten beim Wasserlassen.', 'weight' => 0],
    ['question' => 'Я не чувствую вкуса.', 'answer' => 'Ich habe keinen Geschmackssinn.', 'weight' => 0],
    ['question' => 'Я чувствую усталость после еды.', 'answer' => 'Ich fühle mich nach dem Essen müde.', 'weight' => 0],
    ['question' => 'У меня проблемы с дыханием ночью.', 'answer' => 'Ich habe nachts Atemprobleme.', 'weight' => 0],
    ['question' => 'Мои руки/ноги дрожат.', 'answer' => 'Meine Hände/Beine zittern.', 'weight' => 0],
    ['question' => 'Я не могу сосредоточиться.', 'answer' => 'Ich kann mich nicht konzentrieren.', 'weight' => 0],
    ['question' => 'У меня учащенное сердцебиение.', 'answer' => 'Ich habe Herzklopfen.', 'weight' => 0],
    ['question' => 'Я чувствую, что теряю сознание.', 'answer' => 'Ich habe das Gefühl, das Bewusstsein zu verlieren.', 'weight' => 0],
    ['question' => 'У меня болит горло.', 'answer' => 'Mein Hals tut weh.', 'weight' => 0],
    ['question' => 'Я часто просыпаюсь ночью.', 'answer' => 'Ich wache nachts oft auf.', 'weight' => 0],
    ['question' => 'У меня боль в ушах.', 'answer' => 'Ich habe Ohrenschmerzen.', 'weight' => 0],
    ['question' => 'У меня чувствительная кожа.', 'answer' => 'Meine Haut ist empfindlich.', 'weight' => 0],
    ['question' => 'Я чувствую усталость даже после отдыха.', 'answer' => 'Ich fühle mich müde, auch nach dem Ausruhen.', 'weight' => 0],
    ['question' => 'Моя кожа изменила цвет.', 'answer' => 'Meine Haut hat die Farbe verändert.', 'weight' => 0],
    ['question' => 'Я чувствую боль при движении.', 'answer' => 'Ich fühle Schmerzen bei der Bewegung.', 'weight' => 0],
    ['question' => 'У меня болит под коленом.', 'answer' => 'Es tut mir unter dem Knie weh.', 'weight' => 0],
    ['question' => 'Я чувствую тяжесть в груди.', 'answer' => 'Ich fühle eine Schwere in der Brust.', 'weight' => 0],
    ['question' => 'Я чувствую слабость после работы.', 'answer' => 'Ich fühle mich schwach nach der Arbeit.', 'weight' => 0],

    ['question' => 'У меня тяжесть в ногах.', 'answer' => 'Ich habe ein Schweregefühl in den Beinen.', 'weight' => 0],
    ['question' => 'Мои глаза слезятся.', 'answer' => 'Meine Augen tränen.', 'weight' => 0],
    ['question' => 'Я чувствую себя очень уставшим.', 'answer' => 'Ich fühle mich sehr erschöpft.', 'weight' => 0],
    ['question' => 'Моя кожа чешется.', 'answer' => 'Meine Haut juckt.', 'weight' => 0],
    ['question' => 'У меня холодные руки и ноги.', 'answer' => 'Meine Hände und Füße sind kalt.', 'weight' => 0],
    ['question' => 'Я чувствую боль при сгибании.', 'answer' => 'Ich fühle Schmerzen beim Beugen.', 'weight' => 0],
    ['question' => 'У меня боль в области поясницы.', 'answer' => 'Ich habe Schmerzen im unteren Rückenbereich.', 'weight' => 0],
    ['question' => 'Мои суставы опухли.', 'answer' => 'Meine Gelenke sind geschwollen.', 'weight' => 0],
    ['question' => 'Я не могу нормально спать из-за боли.', 'answer' => 'Ich kann wegen der Schmerzen nicht gut schlafen.', 'weight' => 0],
    ['question' => 'Мои волосы выпадают.', 'answer' => 'Meine Haare fallen aus.', 'weight' => 0],
    ['question' => 'Я чувствую жар в области лица.', 'answer' => 'Ich fühle Hitze im Gesicht.', 'weight' => 0],
    ['question' => 'У меня затруднено дыхание при нагрузке.', 'answer' => 'Ich habe Atembeschwerden bei Anstrengung.', 'weight' => 0],
    ['question' => 'Я часто чувствую головокружение.', 'answer' => 'Ich fühle mich oft schwindlig.', 'weight' => 0],
    ['question' => 'Мои мышцы болят после физической активности.', 'answer' => 'Meine Muskeln schmerzen nach körperlicher Aktivität.', 'weight' => 0],
    ['question' => 'Я чувствую усталость даже после длительного сна.', 'answer' => 'Ich fühle mich müde, auch nach langem Schlaf.', 'weight' => 0],
    ['question' => 'Мои руки и ноги немеют.', 'answer' => 'Meine Hände und Füße werden taub.', 'weight' => 0],
    ['question' => 'Я часто чувствую себя подавленным.', 'answer' => 'Ich fühle mich oft niedergeschlagen.', 'weight' => 0],
    ['question' => 'Мои губы сухие и потрескавшиеся.', 'answer' => 'Meine Lippen sind trocken und rissig.', 'weight' => 0],
    ['question' => 'Я чувствую боль в животе после еды.', 'answer' => 'Ich habe Bauchschmerzen nach dem Essen.', 'weight' => 0],
    ['question' => 'Мои глаза стали более чувствительными к свету.', 'answer' => 'Meine Augen sind empfindlicher gegenüber Licht geworden.', 'weight' => 0],

    ['question' => 'Где именно у вас болит?', 'answer' => 'Wo genau tut es Ihnen weh?', 'weight' => 0],
    ['question' => 'Как долго у вас эти симптомы?', 'answer' => 'Wie lange haben Sie diese Symptome schon?', 'weight' => 0],
    ['question' => 'Принимали ли вы какие-либо лекарства?', 'answer' => 'Haben Sie irgendwelche Medikamente eingenommen?', 'weight' => 0],
    ['question' => 'Была ли у вас аллергия на лекарства?', 'answer' => 'Haben Sie irgendwelche Allergien gegen Medikamente?', 'weight' => 0],
    ['question' => 'Вы чувствовали головокружение или потерю сознания?', 'answer' => 'Haben Sie Schwindelgefühle oder Bewusstseinsverlust erlebt?', 'weight' => 0],
    ['question' => 'Были ли у вас проблемы с сердцем в прошлом?', 'answer' => 'Hatten Sie in der Vergangenheit Herzprobleme?', 'weight' => 0],
    ['question' => 'Какие заболевания у вас были ранее?', 'answer' => 'Welche Krankheiten hatten Sie in der Vergangenheit?', 'weight' => 0],
    ['question' => 'Вы соблюдали диету или изменили питание?', 'answer' => 'Haben Sie eine Diät eingehalten oder Ihre Ernährung geändert?', 'weight' => 0],
    ['question' => 'У вас были операции?', 'answer' => 'Hatten Sie Operationen?', 'weight' => 0],
    ['question' => 'Были ли у вас проблемы с дыханием?', 'answer' => 'Hatten Sie Atembeschwerden?', 'weight' => 0],
    ['question' => 'Вы ощущаете боль во время движения?', 'answer' => 'Fühlen Sie Schmerzen bei der Bewegung?', 'weight' => 0],
    ['question' => 'Как часто у вас возникают такие симптомы?', 'answer' => 'Wie oft treten diese Symptome bei Ihnen auf?', 'weight' => 0],
    ['question' => 'Вы чувствовали себя хуже после еды?', 'answer' => 'Haben Sie sich nach dem Essen schlechter gefühlt?', 'weight' => 0],
    ['question' => 'Какое у вас давление?', 'answer' => 'Wie ist Ihr Blutdruck?', 'weight' => 0],
    ['question' => 'Были ли у вас нарушения сна?', 'answer' => 'Hatten Sie Schlafstörungen?', 'weight' => 0],
    ['question' => 'Вы чувствовали холод в конечностях?', 'answer' => 'Haben Sie Kälte in den Gliedmaßen gespürt?', 'weight' => 0],
    ['question' => 'У вас было ощущение тяжести в груди?', 'answer' => 'Hatten Sie ein Schweregefühl in der Brust?', 'weight' => 0],
    ['question' => 'Вы испытывали трудности при глотании?', 'answer' => 'Hatten Sie Schwierigkeiten beim Schlucken?', 'weight' => 0],
    ['question' => 'Как долго вы страдаете от этих симптомов?', 'answer' => 'Seit wann leiden Sie unter diesen Symptomen?', 'weight' => 0],
    ['question' => 'Вы принимали что-то для облегчения боли?', 'answer' => 'Haben Sie etwas gegen die Schmerzen eingenommen?', 'weight' => 0],

    ['question' => 'Как вы себя чувствуете сегодня?', 'answer' => 'Wie fühlen Sie sich heute?', 'weight' => 0],
    ['question' => 'Какие симптомы у вас наблюдаются?', 'answer' => 'Welche Symptome haben Sie?', 'weight' => 0],
    ['question' => 'Когда вы впервые заметили эти симптомы?', 'answer' => 'Wann haben Sie diese Symptome zum ersten Mal bemerkt?', 'weight' => 0],
    ['question' => 'У вас есть боль сейчас?', 'answer' => 'Haben Sie jetzt Schmerzen?', 'weight' => 0],
    ['question' => 'Где болит больше всего?', 'answer' => 'Wo tut es am meisten weh?', 'weight' => 0],
    ['question' => 'Вы можете описать, какая это боль?', 'answer' => 'Können Sie beschreiben, was für ein Schmerz es ist?', 'weight' => 0],
    ['question' => 'Как часто возникают эти боли?', 'answer' => 'Wie oft treten diese Schmerzen auf?', 'weight' => 0],
    ['question' => 'У вас есть кашель?', 'answer' => 'Haben Sie Husten?', 'weight' => 0],
    ['question' => 'У вас была температура?', 'answer' => 'Hatten Sie Fieber?', 'weight' => 0],
    ['question' => 'Вы чувствовали слабость или усталость?', 'answer' => 'Haben Sie sich schwach oder müde gefühlt?', 'weight' => 0],
    ['question' => 'Вы испытываете головокружение?', 'answer' => 'Haben Sie Schwindelgefühle?', 'weight' => 0],
    ['question' => 'Вы теряли сознание?', 'answer' => 'Sind Sie jemals ohnmächtig geworden?', 'weight' => 0],
    ['question' => 'Как ваше дыхание?', 'answer' => 'Wie ist Ihr Atem?', 'weight' => 0],
    ['question' => 'У вас была боль в груди?', 'answer' => 'Hatten Sie Schmerzen in der Brust?', 'weight' => 0],
    ['question' => 'Вы чувствуете боль при глубоком дыхании?', 'answer' => 'Fühlen Sie Schmerzen beim tiefen Einatmen?', 'weight' => 0],
    ['question' => 'Вы заметили изменения в стуле?', 'answer' => 'Haben Sie Veränderungen im Stuhl bemerkt?', 'weight' => 0],
    ['question' => 'Какой у вас аппетит?', 'answer' => 'Wie ist Ihr Appetit?', 'weight' => 0],
    ['question' => 'У вас были проблемы с мочеиспусканием?', 'answer' => 'Haben Sie Schwierigkeiten beim Wasserlassen gehabt?', 'weight' => 0],
    ['question' => 'Вы чувствуете боль при мочеиспускании?', 'answer' => 'Haben Sie Schmerzen beim Wasserlassen?', 'weight' => 0],
    ['question' => 'У вас было ощущение тяжести в ногах?', 'answer' => 'Hatten Sie ein Schweregefühl in den Beinen?', 'weight' => 0],
    ['question' => 'У вас были судороги в ногах?', 'answer' => 'Haben Sie Krämpfe in den Beinen gehabt?', 'weight' => 0],
    ['question' => 'Вы ощущаете холод в конечностях?', 'answer' => 'Fühlen Sie Kälte in den Gliedmaßen?', 'weight' => 0],
    ['question' => 'У вас есть проблемы со сном?', 'answer' => 'Haben Sie Schlafprobleme?', 'weight' => 0],
    ['question' => 'Какое у вас давление?', 'answer' => 'Wie ist Ihr Blutdruck?', 'weight' => 0],
    ['question' => 'У вас было повышение температуры?', 'answer' => 'Hatten Sie Fieber?', 'weight' => 0],
    ['question' => 'Вы заметили изменения в коже?', 'answer' => 'Haben Sie Hautveränderungen bemerkt?', 'weight' => 0],
    ['question' => 'У вас была боль в суставах?', 'answer' => 'Hatten Sie Gelenkschmerzen?', 'weight' => 0],
    ['question' => 'Вы испытываете зуд?', 'answer' => 'Haben Sie Juckreiz?', 'weight' => 0],
    ['question' => 'Вы чувствуете боль при движении?', 'answer' => 'Haben Sie Schmerzen bei der Bewegung?', 'weight' => 0],
    ['question' => 'У вас есть аллергия на что-либо?', 'answer' => 'Haben Sie irgendwelche Allergien?', 'weight' => 0],

    ['question' => 'Мы проведем небольшую процедуру.', 'answer' => 'Wir werden einen kleinen Eingriff durchführen.', 'weight' => 0],
    ['question' => 'Вы готовы к этой процедуре?', 'answer' => 'Sind Sie bereit für diesen Eingriff?', 'weight' => 0],
    ['question' => 'Я введу вам местный анестетик.', 'answer' => 'Ich werde Ihnen ein Lokalanästhetikum verabreichen.', 'weight' => 0],
    ['question' => 'Вы почувствуете легкое давление.', 'answer' => 'Sie werden einen leichten Druck spüren.', 'weight' => 0],
    ['question' => 'Процедура будет быстрой.', 'answer' => 'Der Eingriff wird schnell sein.', 'weight' => 0],
    ['question' => 'Вам нужно будет оставаться неподвижным.', 'answer' => 'Sie müssen still bleiben.', 'weight' => 0],
    ['question' => 'Вы можете почувствовать легкое жжение.', 'answer' => 'Sie könnten ein leichtes Brennen verspüren.', 'weight' => 0],
    ['question' => 'Я введу иглу.', 'answer' => 'Ich werde die Nadel einführen.', 'weight' => 0],
    ['question' => 'Это будет немного больно.', 'answer' => 'Das wird ein wenig wehtun.', 'weight' => 0],
    ['question' => 'Скажите, если вам станет плохо.', 'answer' => 'Sagen Sie Bescheid, wenn es Ihnen schlecht geht.', 'weight' => 0],
    ['question' => 'Мы возьмем у вас кровь.', 'answer' => 'Wir werden Ihnen Blut abnehmen.', 'weight' => 0],
    ['question' => 'Я сделаю рентген.', 'answer' => 'Ich werde ein Röntgenbild machen.', 'weight' => 0],
    ['question' => 'Нам нужно сделать УЗИ.', 'answer' => 'Wir müssen einen Ultraschall machen.', 'weight' => 0],
    ['question' => 'Мы проверим ваше сердце.', 'answer' => 'Wir werden Ihr Herz untersuchen.', 'weight' => 0],
    ['question' => 'Я поставлю капельницу.', 'answer' => 'Ich werde eine Infusion legen.', 'weight' => 0],
    ['question' => 'Мы проверим ваш уровень сахара в крови.', 'answer' => 'Wir werden Ihren Blutzuckerspiegel überprüfen.', 'weight' => 0],
    ['question' => 'Вы должны будете пить много воды после процедуры.', 'answer' => 'Sie müssen nach dem Eingriff viel Wasser trinken.', 'weight' => 0],
    ['question' => 'Вы не должны есть перед процедурой.', 'answer' => 'Sie sollten vor dem Eingriff nichts essen.', 'weight' => 0],
    ['question' => 'Вам нужно будет соблюдать покой после процедуры.', 'answer' => 'Sie müssen nach dem Eingriff Ruhe halten.', 'weight' => 0],
    ['question' => 'Я введу лекарство через вену.', 'answer' => 'Ich werde das Medikament intravenös verabreichen.', 'weight' => 0],
    ['question' => 'Мы сделаем вам инъекцию.', 'answer' => 'Wir werden Ihnen eine Injektion geben.', 'weight' => 0],
    ['question' => 'Вы почувствуете легкое давление при введении лекарства.', 'answer' => 'Sie werden einen leichten Druck beim Verabreichen des Medikaments spüren.', 'weight' => 0],
    ['question' => 'Мы проведем анализ на инфекцию.', 'answer' => 'Wir werden einen Test auf Infektionen durchführen.', 'weight' => 0],
    ['question' => 'Я измерю вашу температуру.', 'answer' => 'Ich werde Ihre Temperatur messen.', 'weight' => 0],
    ['question' => 'Вы почувствуете небольшой укол.', 'answer' => 'Sie werden einen kleinen Stich spüren.', 'weight' => 0],
    ['question' => 'Мы установим катетер.', 'answer' => 'Wir werden einen Katheter legen.', 'weight' => 0],
    ['question' => 'Вы должны будете принять лекарство после процедуры.', 'answer' => 'Sie müssen nach dem Eingriff Medikamente einnehmen.', 'weight' => 0],
    ['question' => 'Я поставлю вам компресс.', 'answer' => 'Ich werde Ihnen einen Verband anlegen.', 'weight' => 0],
    ['question' => 'Мы проведем тест на аллергию.', 'answer' => 'Wir werden einen Allergietest durchführen.', 'weight' => 0],

    ['question' => 'Вы должны принимать это лекарство три раза в день.', 'answer' => 'Sie müssen dieses Medikament dreimal täglich einnehmen.', 'weight' => 0],
    ['question' => 'Не забывайте пить достаточно воды.', 'answer' => 'Vergessen Sie nicht, ausreichend Wasser zu trinken.', 'weight' => 0],
    ['question' => 'Избегайте тяжелой физической активности.', 'answer' => 'Vermeiden Sie schwere körperliche Anstrengung.', 'weight' => 0],
    ['question' => 'Отдыхайте как можно больше.', 'answer' => 'Ruhen Sie sich so viel wie möglich aus.', 'weight' => 0],
    ['question' => 'Следите за своим давлением каждый день.', 'answer' => 'Überwachen Sie Ihren Blutdruck täglich.', 'weight' => 0],
    ['question' => 'Не пропускайте приемы пищи.', 'answer' => 'Überspringen Sie keine Mahlzeiten.', 'weight' => 0],
    ['question' => 'Не принимайте лекарства натощак.', 'answer' => 'Nehmen Sie keine Medikamente auf nüchternen Magen ein.', 'weight' => 0],
    ['question' => 'Если у вас появятся побочные эффекты, сообщите нам.', 'answer' => 'Wenn Sie Nebenwirkungen bemerken, informieren Sie uns bitte.', 'weight' => 0],
    ['question' => 'Следуйте назначенной диете.', 'answer' => 'Halten Sie sich an die verordnete Diät.', 'weight' => 0],
    ['question' => 'Не курите и не употребляйте алкоголь.', 'answer' => 'Rauchen Sie nicht und trinken Sie keinen Alkohol.', 'weight' => 0],
    ['question' => 'Вам нужно будет вернуться на повторный осмотр.', 'answer' => 'Sie müssen zur Nachuntersuchung zurückkommen.', 'weight' => 0],
    ['question' => 'Не садитесь за руль в течение 24 часов после процедуры.', 'answer' => 'Fahren Sie 24 Stunden nach dem Eingriff nicht Auto.', 'weight' => 0],
    ['question' => 'Держите рану чистой и сухой.', 'answer' => 'Halten Sie die Wunde sauber und trocken.', 'weight' => 0],
    ['question' => 'Избегайте прямого солнечного света.', 'answer' => 'Vermeiden Sie direkte Sonneneinstrahlung.', 'weight' => 0],
    ['question' => 'Принимайте витамины каждый день.', 'answer' => 'Nehmen Sie täglich Vitamine ein.', 'weight' => 0],
    ['question' => 'Старайтесь не напрягаться.', 'answer' => 'Versuchen Sie, sich nicht zu überanstrengen.', 'weight' => 0],
    ['question' => 'Проверяйте уровень сахара в крови каждый день.', 'answer' => 'Überprüfen Sie Ihren Blutzuckerspiegel täglich.', 'weight' => 0],
    ['question' => 'Следите за своим состоянием и записывайте все изменения.', 'answer' => 'Beobachten Sie Ihren Zustand und notieren Sie alle Veränderungen.', 'weight' => 0],
    ['question' => 'Избегайте соленой пищи.', 'answer' => 'Vermeiden Sie salzige Lebensmittel.', 'weight' => 0],
    ['question' => 'При необходимости используйте обезболивающее.', 'answer' => 'Verwenden Sie bei Bedarf Schmerzmittel.', 'weight' => 0],
    ['question' => 'Следите за дыханием и старайтесь дышать ровно.', 'answer' => 'Achten Sie auf Ihre Atmung und atmen Sie gleichmäßig.', 'weight' => 0],
    ['question' => 'При возникновении новых симптомов, сразу обращайтесь.', 'answer' => 'Wenn neue Symptome auftreten, wenden Sie sich sofort an uns.', 'weight' => 0],
    ['question' => 'Не принимайте душ в течение 48 часов после операции.', 'answer' => 'Duschen Sie 48 Stunden nach der Operation nicht.', 'weight' => 0],
    ['question' => 'Пейте много жидкости после процедуры.', 'answer' => 'Trinken Sie viel Flüssigkeit nach dem Eingriff.', 'weight' => 0],
    ['question' => 'Если почувствуете боль, примите назначенные лекарства.', 'answer' => 'Wenn Sie Schmerzen haben, nehmen Sie die verordneten Medikamente ein.', 'weight' => 0],
    ['question' => 'Не пропускайте приемы лекарства.', 'answer' => 'Lassen Sie keine Medikamentendosis aus.', 'weight' => 0],
    ['question' => 'Принимайте лекарство за 30 минут до еды.', 'answer' => 'Nehmen Sie das Medikament 30 Minuten vor den Mahlzeiten ein.', 'weight' => 0],
    ['question' => 'Следите за своим весом.', 'answer' => 'Beobachten Sie Ihr Gewicht.', 'weight' => 0],
    ['question' => 'Записывайте все, что вы едите и пьете.', 'answer' => 'Notieren Sie alles, was Sie essen und trinken.', 'weight' => 0],
    ['question' => 'Старайтесь избегать стрессовых ситуаций.', 'answer' => 'Versuchen Sie, stressige Situationen zu vermeiden.', 'weight' => 0],

    ['question' => 'Нам нужно действовать быстро.', 'answer' => 'Wir müssen schnell handeln.', 'weight' => 0],
    ['question' => 'Вы можете дышать?', 'answer' => 'Können Sie atmen?', 'weight' => 0],
    ['question' => 'Дышите глубже.', 'answer' => 'Atmen Sie tiefer.', 'weight' => 0],
    ['question' => 'Откройте глаза.', 'answer' => 'Öffnen Sie Ihre Augen.', 'weight' => 0],
    ['question' => 'Вы меня слышите?', 'answer' => 'Können Sie mich hören?', 'weight' => 0],
    ['question' => 'Оставайтесь со мной.', 'answer' => 'Bleiben Sie bei mir.', 'weight' => 0],
    ['question' => 'Я вызову помощь.', 'answer' => 'Ich werde Hilfe holen.', 'weight' => 0],
    ['question' => 'Мы сделаем вам искусственное дыхание.', 'answer' => 'Wir werden Ihnen eine Mund-zu-Mund-Beatmung geben.', 'weight' => 0],
    ['question' => 'Я зафиксирую вашу шею.', 'answer' => 'Ich werde Ihren Hals fixieren.', 'weight' => 0],
    ['question' => 'Не двигайтесь.', 'answer' => 'Bewegen Sie sich nicht.', 'weight' => 0],
    ['question' => 'Я проверю ваш пульс.', 'answer' => 'Ich werde Ihren Puls überprüfen.', 'weight' => 0],
    ['question' => 'Вы чувствуете боль в груди?', 'answer' => 'Haben Sie Schmerzen in der Brust?', 'weight' => 0],
    ['question' => 'Мы сделаем вам инъекцию адреналина.', 'answer' => 'Wir werden Ihnen eine Adrenalinspritze geben.', 'weight' => 0],
    ['question' => 'Вы можете поднять руки?', 'answer' => 'Können Sie Ihre Arme heben?', 'weight' => 0],
    ['question' => 'Постарайтесь дышать медленно.', 'answer' => 'Versuchen Sie, langsam zu atmen.', 'weight' => 0],
    ['question' => 'Мы вызвали скорую помощь.', 'answer' => 'Wir haben einen Krankenwagen gerufen.', 'weight' => 0],
    ['question' => 'Сосредоточьтесь на моем голосе.', 'answer' => 'Konzentrieren Sie sich auf meine Stimme.', 'weight' => 0],
    ['question' => 'Мы остановим кровотечение.', 'answer' => 'Wir werden die Blutung stoppen.', 'weight' => 0],
    ['question' => 'Держитесь, мы вам поможем.', 'answer' => 'Halten Sie durch, wir helfen Ihnen.', 'weight' => 0],
    ['question' => 'Мы перенесем вас на носилки.', 'answer' => 'Wir werden Sie auf die Trage legen.', 'weight' => 0],
    ['question' => 'Оставайтесь спокойны.', 'answer' => 'Bleiben Sie ruhig.', 'weight' => 0],
    ['question' => 'Мы сделаем электрокардиограмму.', 'answer' => 'Wir werden ein Elektrokardiogramm (EKG) machen.', 'weight' => 0],
    ['question' => 'Вы можете говорить?', 'answer' => 'Können Sie sprechen?', 'weight' => 0],
    ['question' => 'Мы проверим ваше давление.', 'answer' => 'Wir werden Ihren Blutdruck überprüfen.', 'weight' => 0],
    ['question' => 'Вы чувствуете онемение?', 'answer' => 'Spüren Sie Taubheit?', 'weight' => 0],
    ['question' => 'Я вызову врача.', 'answer' => 'Ich werde den Arzt rufen.', 'weight' => 0],
    ['question' => 'Мы дадим вам кислород.', 'answer' => 'Wir werden Ihnen Sauerstoff geben.', 'weight' => 0],
    ['question' => 'Скажите, если вы чувствуете боль.', 'answer' => 'Sagen Sie Bescheid, wenn Sie Schmerzen spüren.', 'weight' => 0],
    ['question' => 'Мы будем держать вас в безопасности.', 'answer' => 'Wir werden Sie in Sicherheit bringen.', 'weight' => 0],

    ['question' => 'Я надену на вас манжету для измерения давления.', 'answer' => 'Ich werde Ihnen eine Blutdruckmanschette anlegen.', 'weight' => 0],
    ['question' => 'Мы используем стерильное оборудование.', 'answer' => 'Wir verwenden steriles Equipment.', 'weight' => 0],
    ['question' => 'Я установлю вам катетер.', 'answer' => 'Ich werde Ihnen einen Katheter legen.', 'weight' => 0],
    ['question' => 'Пожалуйста, держите руку неподвижно, я возьму кровь.', 'answer' => 'Bitte halten Sie Ihren Arm ruhig, ich werde Ihnen Blut abnehmen.', 'weight' => 0],
    ['question' => 'Мы подключим вас к монитору.', 'answer' => 'Wir werden Sie an den Monitor anschließen.', 'weight' => 0],
    ['question' => 'Я введу вам шприц.', 'answer' => 'Ich werde Ihnen eine Spritze setzen.', 'weight' => 0],
    ['question' => 'Мы проверим уровень кислорода в крови.', 'answer' => 'Wir werden Ihren Sauerstoffgehalt im Blut überprüfen.', 'weight' => 0],
    ['question' => 'Я надену вам маску для подачи кислорода.', 'answer' => 'Ich werde Ihnen eine Sauerstoffmaske aufsetzen.', 'weight' => 0],
    ['question' => 'Вы почувствуете легкий укол.', 'answer' => 'Sie werden einen kleinen Stich spüren.', 'weight' => 0],
    ['question' => 'Я закреплю вам датчик на пальце.', 'answer' => 'Ich werde Ihnen einen Sensor am Finger befestigen.', 'weight' => 0],
    ['question' => 'Мы поставим капельницу.', 'answer' => 'Wir werden eine Infusion legen.', 'weight' => 0],
    ['question' => 'Я буду наблюдать за вашим пульсом.', 'answer' => 'Ich werde Ihren Puls überwachen.', 'weight' => 0],
    ['question' => 'Мы используем ультразвук для проверки.', 'answer' => 'Wir verwenden Ultraschall für die Untersuchung.', 'weight' => 0],
    ['question' => 'Я измерю вашу температуру.', 'answer' => 'Ich werde Ihre Temperatur messen.', 'weight' => 0],
    ['question' => 'Мы используем ЭКГ для проверки сердца.', 'answer' => 'Wir verwenden ein EKG zur Überprüfung des Herzens.', 'weight' => 0],
    ['question' => 'Я закреплю вам электроды на груди.', 'answer' => 'Ich werde Ihnen Elektroden auf die Brust legen.', 'weight' => 0],
    ['question' => 'Вы услышите звук прибора.', 'answer' => 'Sie werden ein Geräusch vom Gerät hören.', 'weight' => 0],
    ['question' => 'Пожалуйста, расслабьтесь, это будет недолго.', 'answer' => 'Bitte entspannen Sie sich, es wird nicht lange dauern.', 'weight' => 0],
    ['question' => 'Мы возьмем образец для анализа.', 'answer' => 'Wir werden eine Probe zur Analyse nehmen.', 'weight' => 0],
    ['question' => 'Я использую стерильные перчатки.', 'answer' => 'Ich trage sterile Handschuhe.', 'weight' => 0],
    ['question' => 'Мы проведем тест на аллергию.', 'answer' => 'Wir werden einen Allergietest durchführen.', 'weight' => 0],
    ['question' => 'Я закреплю повязку на руке.', 'answer' => 'Ich werde einen Verband am Arm befestigen.', 'weight' => 0],
    ['question' => 'Мы проверим ваш рефлекс.', 'answer' => 'Wir werden Ihren Reflex überprüfen.', 'weight' => 0],
    ['question' => 'Я направлю свет в ваши глаза.', 'answer' => 'Ich werde Ihnen mit einer Lampe in die Augen leuchten.', 'weight' => 0],
    ['question' => 'Вы услышите щелчок, когда мы сделаем снимок.', 'answer' => 'Sie werden ein Klicken hören, wenn wir ein Bild machen.', 'weight' => 0],
    ['question' => 'Мы будем использовать рентген.', 'answer' => 'Wir werden Röntgen verwenden.', 'weight' => 0],
    ['question' => 'Пожалуйста, не двигайтесь во время процедуры.', 'answer' => 'Bitte bewegen Sie sich nicht während des Eingriffs.', 'weight' => 0],
    ['question' => 'Мы используем капельницу для подачи лекарства.', 'answer' => 'Wir verwenden eine Infusion zur Medikamentenverabreichung.', 'weight' => 0],
    ['question' => 'Я закреплю вам зажим на ухе.', 'answer' => 'Ich werde Ihnen eine Klemme am Ohr befestigen.', 'weight' => 0],
];
