<?php


return [
                ['question' => 'Диагноз', 'answer' => 'Diagnosis', 'weight' => 0],
                ['question' => 'Лекарство', 'answer' => 'Medicine', 'weight' => 0],
                ['question' => 'Врач', 'answer' => 'Doctor', 'weight' => 0],
                ['question' => 'Пациент', 'answer' => 'Patient', 'weight' => 0],
                ['question' => 'Терапия', 'answer' => 'Therapy', 'weight' => 0],
                ['question' => 'Хирургия', 'answer' => 'Surgery', 'weight' => 0],
                ['question' => 'Анализ крови', 'answer' => 'Blood Test', 'weight' => 0],
                ['question' => 'УЗИ', 'answer' => 'Ultrasound', 'weight' => 0],
                ['question' => 'Рентген', 'answer' => 'X-ray', 'weight' => 0],
                ['question' => 'Терапевт', 'answer' => 'Therapist', 'weight' => 0],
                ['question' => 'Операция', 'answer' => 'Operation', 'weight' => 0],
                ['question' => 'Вакцина', 'answer' => 'Vaccine', 'weight' => 0],
                ['question' => 'Иммунитет', 'answer' => 'Immunity', 'weight' => 0],
                ['question' => 'Эпидемия', 'answer' => 'Epidemic', 'weight' => 0],
                ['question' => 'Пандемия', 'answer' => 'Pandemic', 'weight' => 0],
                ['question' => 'Симптом', 'answer' => 'Symptom', 'weight' => 0],
                ['question' => 'Диета', 'answer' => 'Diet', 'weight' => 0],
                ['question' => 'Аллергия', 'answer' => 'Allergy', 'weight' => 0],
                ['question' => 'Инфекция', 'answer' => 'Infection', 'weight' => 0],
                ['question' => 'Воспаление', 'answer' => 'Inflammation', 'weight' => 0],
                ['question' => 'Онкология', 'answer' => 'Oncology', 'weight' => 0],
                ['question' => 'Кардиология', 'answer' => 'Cardiology', 'weight' => 0],
                ['question' => 'Неврология', 'answer' => 'Neurology', 'weight' => 0],
                ['question' => 'Дерматология', 'answer' => 'Dermatology', 'weight' => 0],
                ['question' => 'Педиатрия', 'answer' => 'Pediatrics', 'weight' => 0],
                ['question' => 'Психиатрия', 'answer' => 'Psychiatry', 'weight' => 0],
                ['question' => 'Гинекология', 'answer' => 'Gynecology', 'weight' => 0],
                ['question' => 'Урология', 'answer' => 'Urology', 'weight' => 0],
                ['question' => 'Ревматология', 'answer' => 'Rheumatology', 'weight' => 0],
                ['question' => 'Гастроэнтерология', 'answer' => 'Gastroenterology', 'weight' => 0],
                ['question' => 'Эндокринология', 'answer' => 'Endocrinology', 'weight' => 0],
                ['question' =>  'Сердечный приступ', 'answer' =>  'Heart attack', 'weight' =>  0],
                ['question' =>  'Инсульт', 'answer' =>  'Stroke', 'weight' =>  0],
                ['question' =>  'Гипертония', 'answer' =>  'Hypertension', 'weight' =>  0],
                ['question' =>  'Астма', 'answer' =>  'Asthma', 'weight' =>  0],
                ['question' =>  'Диабет', 'answer' =>  'Diabetes', 'weight' =>  0],
                ['question' =>  'Хроническая болезнь', 'answer' =>  'Chronic disease', 'weight' =>  0],
                ['question' =>  'Ожирение', 'answer' =>  'Obesity', 'weight' =>  0],
                ['question' =>  'Артрит', 'answer' =>  'Arthritis', 'weight' =>  0],
                ['question' =>  'Мигрень', 'answer' =>  'Migraine', 'weight' =>  0],
                ['question' =>  'Рак легких', 'answer' =>  'Lung cancer', 'weight' =>  0],
                ['question' =>  'Рак груди', 'answer' =>  'Breast cancer', 'weight' =>  0],
                ['question' =>  'Туберкулез', 'answer' =>  'Tuberculosis', 'weight' =>  0],
                ['question' =>  'Вирус иммунодефицита человека (ВИЧ)', 'answer' =>  'Human Immunodeficiency Virus (HIV)', 'weight' =>  0],
                ['question' =>  'СПИД', 'answer' =>  'AIDS', 'weight' =>  0],
                ['question' =>  'Малярия', 'answer' =>  'Malaria', 'weight' =>  0],
                ['question' =>  'Прививка', 'answer' =>  'Vaccination', 'weight' =>  0],
                ['question' =>  'Антибиотик', 'answer' =>  'Antibiotic', 'weight' =>  0],
                ['question' =>  'Обезболивающее средство', 'answer' =>  'Painkiller', 'weight' =>  0],
                ['question' =>  'Седативное средство', 'answer' =>  'Sedative', 'weight' =>  0],
                ['question' =>  'Психотропные препараты', 'answer' =>  'Psychotropic drugs', 'weight' =>  0],
                ['question' =>  'Антидепрессанты', 'answer' =>  'Antidepressants', 'weight' =>  0],
                ['question' =>  'Противовоспалительное средство', 'answer' =>  'Anti-inflammatory', 'weight' =>  0],
                ['question' =>  'Жаропонижающее средство', 'answer' =>  'Antipyretic', 'weight' =>  0],
                ['question' =>  'Гомеопатия', 'answer' =>  'Homeopathy', 'weight' =>  0],
                ['question' =>  'Физиотерапия', 'answer' =>  'Physiotherapy', 'weight' =>  0],
                ['question' =>  'Реабилитация', 'answer' =>  'Rehabilitation', 'weight' =>  0],
                ['question' =>  'Пластическая хирургия', 'answer' =>  'Plastic surgery', 'weight' =>  0],
                ['question' =>  'Экстренная помощь', 'answer' =>  'Emergency care', 'weight' =>  0],
                ['question' =>  'Неотложная помощь', 'answer' =>  'Urgent care', 'weight' =>  0],
                ['question' =>  'Амбулаторная помощь', 'answer' =>  'Outpatient care', 'weight' =>  0],
                ['question' =>  'Стационарная помощь', 'answer' =>  'Inpatient care', 'weight' =>  0],
                ['question' =>  'Диспансеризация', 'answer' =>  'Medical examination', 'weight' =>  0],
                ['question' =>  'Профилактика заболеваний', 'answer' =>  'Disease prevention', 'weight' =>  0],
                ['question' =>  'Инкубационный период', 'answer' =>  'Incubation period', 'weight' =>  0],
                ['question' =>  'Иммунная система', 'answer' =>  'Immune system', 'weight' =>  0],
                ['question' =>  'Лимфатическая система', 'answer' =>  'Lymphatic system', 'weight' =>  0],
                ['question' =>  'Костная система', 'answer' =>  'Skeletal system', 'weight' =>  0],
                ['question' =>  'Мышечная система', 'answer' =>  'Muscular system', 'weight' =>  0],
                ['question' =>  'Нервная система', 'answer' =>  'Nervous system', 'weight' =>  0],
                ['question' =>  'Пищеварительная система', 'answer' =>  'Digestive system', 'weight' =>  0],
                ['question' =>  'Респираторная система', 'answer' =>  'Respiratory system', 'weight' =>  0],
                ['question' =>  'Мочевыделительная система', 'answer' =>  'Urinary system', 'weight' =>  0],
                ['question' =>  'Эндокринная система', 'answer' =>  'Endocrine system', 'weight' =>  0],
                ['question' =>  'Сердечно-сосудистая система', 'answer' =>  'Cardiovascular system', 'weight' =>  0],
                ['question' =>  'Кожная система', 'answer' =>  'Integumentary system', 'weight' =>  0],
                ['question' =>  'Опорно-двигательная система', 'answer' =>  'Musculoskeletal system', 'weight' =>  0],
                ['question' =>  'Биопсия', 'answer' =>  'Biopsy', 'weight' =>  0],
                ['question' =>  'Рентгенография', 'answer' =>  'Radiography', 'weight' =>  0],
                ['question' =>  'КТ (компьютерная томография)', 'answer' =>  'CT (Computed Tomography)', 'weight' =>  0],
                ['question' =>  'МРТ (магнитно-резонансная томография)', 'answer' =>  'MRI (Magnetic Resonance Imaging)', 'weight' =>  0],
                ['question' =>  'ПЭТ (позитронно-эмиссионная томография)', 'answer' =>  'PET (Positron Emission Tomography)', 'weight' =>  0],
                ['question' =>  'Анализ мочи', 'answer' =>  'Urine test', 'weight' =>  0],
                ['question' =>  'ЭКГ (электрокардиограмма)', 'answer' =>  'ECG (Electrocardiogram)', 'weight' =>  0],
                ['question' =>  'ЭЭГ (электроэнцефалограмма)', 'answer' =>  'EEG (Electroencephalogram)', 'weight' =>  0],
                ['question' =>  'Эхокардиограмма', 'answer' =>  'Echocardiogram', 'weight' =>  0],
                ['question' =>  'Спирометрия', 'answer' =>  'Spirometry', 'weight' =>  0],
                ['question' =>  'Флюорография', 'answer' =>  'Fluorography', 'weight' =>  0],
                ['question' =>  'Ультразвуковое исследование', 'answer' =>  'Ultrasonic examination', 'weight' =>  0],
                ['question' =>  'Гастроскопия', 'answer' =>  'Gastroscopy', 'weight' =>  0],
                ['question' =>  'Колоноскопия', 'answer' =>  'Colonoscopy', 'weight' =>  0],
                ['question' =>  'Бронхоскопия', 'answer' =>  'Bronchoscopy', 'weight' =>  0],
                ['question' =>  'Лапароскопия', 'answer' =>  'Laparoscopy', 'weight' =>  0],
                ['question' =>  'Гинекологический осмотр', 'answer' =>  'Gynecological examination', 'weight' =>  0],
                ['question' =>  'Урологический осмотр', 'answer' =>  'Urological examination', 'weight' =>  0],
                ['question' =>  'Дерматологический осмотр', 'answer' =>  'Dermatological examination', 'weight' =>  0],
                ['question' =>  'Кардиологический осмотр', 'answer' =>  'Cardiological examination', 'weight' =>  0],
                ['question' =>  'Неврологический осмотр', 'answer' =>  'Neurological examination', 'weight' =>  0],
                ['question' =>  'Онкологический осмотр', 'answer' =>  'Oncological examination', 'weight' =>  0],
                ['question' =>  'Стоматологический осмотр', 'answer' =>  'Dental examination', 'weight' =>  0],
                ['question' =>  'Офтальмологический осмотр', 'answer' =>  'Ophthalmological examination', 'weight' =>  0],
                ['question' =>  'Отоларингологический осмотр', 'answer' =>  'Otorhinolaryngological examination', 'weight' =>  0],
                ['question' =>  'Педиатрический осмотр', 'answer' =>  'Pediatric examination', 'weight' =>  0],
                ['question' =>  'Психиатрический осмотр', 'answer' =>  'Psychiatric examination', 'weight' =>  0],
                ['question' =>  'Сердечно-сосудистая реанимация', 'answer' =>  'Cardiopulmonary resuscitation (CPR)', 'weight' =>  0],
                ['question' =>  'Дефибриллятор', 'answer' =>  'Defibrillator', 'weight' =>  0],
                ['question' =>  'Искусственная вентиляция легких', 'answer' =>  'Artificial lung ventilation', 'weight' =>  0],
                ['question' =>  'Гемодиализ', 'answer' =>  'Hemodialysis', 'weight' =>  0],
                ['question' =>  'Плазмаферез', 'answer' =>  'Plasmapheresis', 'weight' =>  0],
                ['question' =>  'Переливание крови', 'answer' =>  'Blood transfusion', 'weight' =>  0],
                ['question' =>  'Интубация', 'answer' =>  'Intubation', 'weight' =>  0],
                ['question' =>  'Катетеризация', 'answer' =>  'Catheterization', 'weight' =>  0],
                ['question' =>  'Парентеральное питание', 'answer' =>  'Parenteral nutrition', 'weight' =>  0],
                ['question' =>  'Энтеральное питание', 'answer' =>  'Enteral nutrition', 'weight' =>  0],
                ['question' =>  'Лечебное голодание', 'answer' =>  'Therapeutic fasting', 'weight' =>  0],
                ['question' =>  'Трансплантация органов', 'answer' =>  'Organ transplantation', 'weight' =>  0],
                ['question' =>  'Паллиативная помощь', 'answer' =>  'Palliative care', 'weight' =>  0],
                ['question' =>  'Госпитализация', 'answer' =>  'Hospitalization', 'weight' =>  0],
                ['question' =>  'Выписка из больницы', 'answer' =>  'Discharge from hospital', 'weight' =>  0],
                ['question' =>  'Амбулаторный прием', 'answer' =>  'Outpatient appointment', 'weight' =>  0],
                ['question' =>  'Прием у врача', 'answer' =>  'Doctor\'s appointment', 'weight' =>  0],
                ['question' =>  'Медицинская карта', 'answer' =>  'Medical record', 'weight' =>  0],
                ['question' =>  'История болезни', 'answer' =>  'Medical history', 'weight' =>  0],
                ['question' =>  'Медицинская страховка', 'answer' =>  'Medical insurance', 'weight' =>  0],
                ['question' =>  'Медицинское заключение', 'answer' =>  'Medical certificate', 'weight' =>  0],
                ['question' =>  'Рецепт', 'answer' =>  'Prescription', 'weight' =>  0],
                ['question' =>  'Медицинская справка', 'answer' =>  'Medical note', 'weight' =>  0],
                ['question' =>  'Вакцинация от гриппа', 'answer' =>  'Flu vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от кори', 'answer' =>  'Measles vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от краснухи', 'answer' =>  'Rubella vaccination', 'weight' =>  0],
                ['question' =>  'Вакцинация от гепатита', 'answer' =>  'Hepatitis vaccination', 'weight' =>  0]
            ];