<?php


return [
    ['question' => '❤️ Сердце', 'answer' => 'Heart \n (харт)', 'weight' => 0],
    ['question' => '⭐️ Звезда', 'answer' => 'Star \n (стар)', 'weight' => 0],
    ['question' => '🔥 Огонь', 'answer' => 'Fire \n (файр)', 'weight' => 0],
    ['question' => '💧 Капля воды', 'answer' => 'Drop \n (дроп)', 'weight' => 0],
    ['question' => '⌨️ Клавиатура', 'answer' => 'Keyboard \n (киборд)', 'weight' => 0],
    ['question' => '👻 Привидение', 'answer' => 'Ghost \n (гоуст)', 'weight' => 0],
    ['question' => '🤡 Клоун', 'answer' => 'Clown \n (клаун)', 'weight' => 0],
    ['question' => '👀 Глаза', 'answer' => 'Eyes \n (айз)', 'weight' => 0],
    ['question' => '🦷 Зуб', 'answer' => 'Tooth \n (туф)', 'weight' => 0],
    ['question' => '👅 Язык', 'answer' => 'Tongue \n (танг)', 'weight' => 0],
    ['question' => '👄 Рот', 'answer' => 'Mouth \n (маус)', 'weight' => 0],
    ['question' => '👣 Следы', 'answer' => 'Footprints \n (футпринтс)', 'weight' => 0],
    ['question' => '👂 Ухо', 'answer' => 'Ear \n (ир)', 'weight' => 0],
    ['question' => '✋ Рука', 'answer' => 'Hand \n (хэнд)', 'weight' => 0],
    ['question' => '👮‍♀️ Полицейская', 'answer' => 'Policewoman \n (полисвумен)', 'weight' => 0],
    ['question' => '🥷 Ниндзя', 'answer' => 'Ninja \n (ниндзя)', 'weight' => 0],
    ['question' => '🩳 Шорты', 'answer' => 'Shorts \n (шортс)', 'weight' => 0],
    ['question' => '👕 Футболка', 'answer' => 'T-shirt \n (ти-щерт)', 'weight' => 0],
    ['question' => '👞 Туфли', 'answer' => 'Shoes \n (шуз)', 'weight' => 0],
    ['question' => '🥾 Ботинки', 'answer' => 'Boots \n (бутс)', 'weight' => 0],
    ['question' => '🧦 Носки', 'answer' => 'Socks \n (сокс)', 'weight' => 0],
    ['question' => '🧤 Перчатки', 'answer' => 'Gloves \n (гловс)', 'weight' => 0],
    ['question' => '🧣 Шарф', 'answer' => 'Scarf \n (скарф)', 'weight' => 0],
    ['question' => '🧢 Кепка', 'answer' => 'Cap \n (кэп)', 'weight' => 0],
    ['question' => '💼 Чемодан', 'answer' => 'Suitcase \n (сюткейс)', 'weight' => 0],
    ['question' => '👜 Сумка', 'answer' => 'Bag \n (бэг)', 'weight' => 0],
    ['question' => '👝 Клатч', 'answer' => 'Clutch \n (клатч)', 'weight' => 0],
    ['question' => '💍 Кольцо', 'answer' => 'Ring \n (ринг)', 'weight' => 0],
    ['question' => '👑 Корона', 'answer' => 'Crown \n (краун)', 'weight' => 0],
    ['question' => '🪖 Шлем', 'answer' => 'Helmet \n (хелмет)', 'weight' => 0],
    ['question' => '🎒 Рюкзак', 'answer' => 'Backpack \n (бэкпэк)', 'weight' => 0],
    ['question' => '👓 Очки', 'answer' => 'Glasses \n (глассес)', 'weight' => 0],
    ['question' => '🕶 Солнцезащитные очки', 'answer' => 'Sunglasses \n (санглассес)', 'weight' => 0],
    ['question' => '🥽 Защитные очки', 'answer' => 'Goggles \n (гоглс)', 'weight' => 0],
    ['question' => '🌂 Зонтик', 'answer' => 'Umbrella \n (амбрелла)', 'weight' => 0],
    ['question' => '🐶 Собака', 'answer' => 'Dog \n (дог)', 'weight' => 0],
    ['question' => '🐱 Кошка', 'answer' => 'Cat \n (кэт)', 'weight' => 0],
    ['question' => '🐭 Мышь', 'answer' => 'Mouse \n (маус)', 'weight' => 0],
    ['question' => '🐹 Хомяк', 'answer' => 'Hamster \n (хэмстер)', 'weight' => 0],
    ['question' => '🐰 Кролик', 'answer' => 'Rabbit \n (рэббит)', 'weight' => 0],
    ['question' => '🦊 Лиса', 'answer' => 'Fox \n (фокс)', 'weight' => 0],
    ['question' => '🐻 Медведь', 'answer' => 'Bear \n (беар)', 'weight' => 0],
    ['question' => '🐼 Панда', 'answer' => 'Panda \n (панда)', 'weight' => 0],
    ['question' => '🐻‍❄️ Белый медведь', 'answer' => 'Polar bear \n (полар беар)', 'weight' => 0],
    ['question' => '🐨 Коала', 'answer' => 'Koala \n (коала)', 'weight' => 0],
    ['question' => '🐯 Тигр', 'answer' => 'Tiger \n (тайгер)', 'weight' => 0],
    ['question' => '🦁 Лев', 'answer' => 'Lion \n (лион)', 'weight' => 0],
    ['question' => '🐮 Корова', 'answer' => 'Cow \n (кау)', 'weight' => 0],
    ['question' => '🐷 Свинья', 'answer' => 'Pig \n (пиг)', 'weight' => 0],
    ['question' => '🐽 Пятачок', 'answer' => 'Snout \n (снаут)', 'weight' => 0],
    ['question' => '🐸 Лягушка', 'answer' => 'Frog \n (фрог)', 'weight' => 0],
    ['question' => '🐵 Обезьяна', 'answer' => 'Monkey \n (манки)', 'weight' => 0],
    ['question' => '🙈 Обезьяна, закрывающая глаза', 'answer' => 'See-no-evil monkey \n (си но ивил манки)', 'weight' => 0],
    ['question' => '🙉 Обезьяна, закрывающая уши', 'answer' => 'Hear-no-evil monkey \n (хиар но ивил манки)', 'weight' => 0],
    ['question' => '🐔 Курица', 'answer' => 'Chicken \n (чикен)', 'weight' => 0],
    ['question' => '🐧 Пингвин', 'answer' => 'Penguin \n (пэнгуин)', 'weight' => 0],
    ['question' => '🐦 Птица', 'answer' => 'Bird \n (бёрд)', 'weight' => 0],
    ['question' => '🐤 Цыпленок', 'answer' => 'Chick \n (чик)', 'weight' => 0],
    ['question' => '🦇 Летучая мышь', 'answer' => 'Bat \n (бат)', 'weight' => 0],
    ['question' => '🪿 Гусь', 'answer' => 'Goose \n (гуз)', 'weight' => 0],
    ['question' => '🦆 Утка', 'answer' => 'Duck \n (дак)', 'weight' => 0],
    ['question' => '🦅 Орел', 'answer' => 'Eagle \n (игл)', 'weight' => 0],
    ['question' => '🐺 Волк', 'answer' => 'Wolf \n (вулф)', 'weight' => 0],
    ['question' => '🦄 Единорог', 'answer' => 'Unicorn \n (юникорн)', 'weight' => 0],
    ['question' => '🫎 Лось', 'answer' => 'Moose \n (муз)', 'weight' => 0],
    ['question' => '🐝 Пчела', 'answer' => 'Bee \n (би)', 'weight' => 0],
    ['question' => '🪱 Червяк', 'answer' => 'Worm \n (ворм)', 'weight' => 0],
    ['question' => '🐛 Гусеница', 'answer' => 'Caterpillar \n (катерпиллар)', 'weight' => 0],
    ['question' => '🦋 Бабочка', 'answer' => 'Butterfly \n (баттерфлай)', 'weight' => 0],
    ['question' => '🐌 Улитка', 'answer' => 'Snail \n (снейл)', 'weight' => 0],
    ['question' => '🐞 Божья коровка', 'answer' => 'Ladybug \n (лейдибаг)', 'weight' => 0],
    ['question' => '🐜 Муравей', 'answer' => 'Ant \n (энт)', 'weight' => 0],
    ['question' => '🪰 Муха', 'answer' => 'Fly \n (флай)', 'weight' => 0],
    ['question' => '🪲 Жук', 'answer' => 'Beetle \n (битл)', 'weight' => 0],
    ['question' => '🪳 Таракан', 'answer' => 'Cockroach \n (кокроуч)', 'weight' => 0],
    ['question' => '🦟 Комар', 'answer' => 'Mosquito \n (москито)', 'weight' => 0],
    ['question' => '🦗 Сверчок', 'answer' => 'Cricket \n (крикет)', 'weight' => 0],
    ['question' => '🕷 Паук', 'answer' => 'Spider \n (спайдер)', 'weight' => 0],
    ['question' => '🕸 Паутинка', 'answer' => 'Web \n (веб)', 'weight' => 0],
    ['question' => '🦂 Скорпион', 'answer' => 'Scorpion \n (скорпион)', 'weight' => 0],
    ['question' => '🐢 Черепаха', 'answer' => 'Turtle \n (тёртл)', 'weight' => 0],
    ['question' => '🦞 Лобстер', 'answer' => 'Lobster \n (лобстер)', 'weight' => 0],
    ['question' => '🦐 Креветка', 'answer' => 'Shrimp \n (шримп)', 'weight' => 0],
    ['question' => '🪼 Медуза', 'answer' => 'Jellyfish \n (джеллифиш)', 'weight' => 0],
    ['question' => '🦑 Кальмар', 'answer' => 'Squid \n (сквид)', 'weight' => 0],
    ['question' => '🐙 Осьминог', 'answer' => 'Octopus \n (октопус)', 'weight' => 0],
    ['question' => '🦕 Динозавр', 'answer' => 'Dinosaur \n (дайносор)', 'weight' => 0],
    ['question' => '🦖 Тираннозавр', 'answer' => 'Tyrannosaurus \n (тираннозор)', 'weight' => 0],
    ['question' => '🦎 Ящерица', 'answer' => 'Lizard \n (лизард)', 'weight' => 0],
    ['question' => '🐍 Змея', 'answer' => 'Snake \n (снэйк)', 'weight' => 0],
    ['question' => '🦀 Краб', 'answer' => 'Crab \n (краб)', 'weight' => 0],
    ['question' => '🐡 Рыба-фугу', 'answer' => 'Pufferfish \n (пафферфиш)', 'weight' => 0],
    ['question' => '🐠 Рыбка', 'answer' => 'Fish \n (фиш)', 'weight' => 0],
    ['question' => '🐟 Рыба', 'answer' => 'Fish \n (фиш)', 'weight' => 0],
    ['question' => '🐬 Дельфин', 'answer' => 'Dolphin \n (долфин)', 'weight' => 0],
    ['question' => '🐳 Кит', 'answer' => 'Whale \n (уэйл)', 'weight' => 0],
    ['question' => '🐋 Синий кит', 'answer' => 'Blue whale \n (блю уэйл)', 'weight' => 0],
    ['question' => '🦈 Акула', 'answer' => 'Shark \n (шарк)', 'weight' => 0],
    ['question' => '🦭 Морской котик', 'answer' => 'Seal \n (сил)', 'weight' => 0],
    ['question' => '🦛 Бегемот', 'answer' => 'Hippopotamus \n (хиппопотамус)', 'weight' => 0],
    ['question' => '🐘 Слон', 'answer' => 'Elephant \n (элефант)', 'weight' => 0],
    ['question' => '🦣 Мамонт', 'answer' => 'Mammoth \n (маммос)', 'weight' => 0],
    ['question' => '🦧 Орангутан', 'answer' => 'Orangutan \n (орангутан)', 'weight' => 0],
    ['question' => '🦍 Горилла', 'answer' => 'Gorilla \n (горилла)', 'weight' => 0],
    ['question' => '🦓 Зебра', 'answer' => 'Zebra \n (зебра)', 'weight' => 0],
    ['question' => '🐆 Леопард', 'answer' => 'Leopard \n (леопард)', 'weight' => 0],
    ['question' => '🐅 Тигр', 'answer' => 'Tiger \n (тайгер)', 'weight' => 0],
    ['question' => '🐊 Крокодил', 'answer' => 'Crocodile \n (крокодайл)', 'weight' => 0],
    ['question' => '🦏 Носорог', 'answer' => 'Rhinoceros \n (риносорос)', 'weight' => 0],
    ['question' => '🐪 Верблюд', 'answer' => 'Camel \n (камел)', 'weight' => 0],
    ['question' => '🐫 Двугорбый верблюд', 'answer' => 'Bactrian camel \n (бактериан камел)', 'weight' => 0],
    ['question' => '🦒 Жираф', 'answer' => 'Giraffe \n (джирафф)', 'weight' => 0],
    ['question' => '🦘 Кенгуру', 'answer' => 'Kangaroo \n (кенгуру)', 'weight' => 0],
    ['question' => '🦬 Бизон', 'answer' => 'Bison \n (байсон)', 'weight' => 0],
    ['question' => '🐃 Буйвол', 'answer' => 'Buffalo \n (баффало)', 'weight' => 0],
    ['question' => '🐂 Бык', 'answer' => 'Ox \n (окс)', 'weight' => 0],
    ['question' => '🐄 Корова', 'answer' => 'Cow \n (кау)', 'weight' => 0],
    ['question' => '🐕 Собака', 'answer' => 'Dog \n (дог)', 'weight' => 0],
    ['question' => '🦌 Олень', 'answer' => 'Deer \n (дир)', 'weight' => 0],
    ['question' => '🐐 Козел', 'answer' => 'Goat \n (гоат)', 'weight' => 0],
    ['question' => '🦙 Лама', 'answer' => 'Llama \n (лама)', 'weight' => 0],
    ['question' => '🐑 Овца', 'answer' => 'Sheep \n (шип)', 'weight' => 0],
    ['question' => '🐏 Баран', 'answer' => 'Ram \n (рэм)', 'weight' => 0],
    ['question' => '🐖 Свинья', 'answer' => 'Pig \n (пиг)', 'weight' => 0],
    ['question' => '🐎 Лошадь', 'answer' => 'Horse \n (хорс)', 'weight' => 0],
    ['question' => '🫏 Осел', 'answer' => 'Donkey \n (донки)', 'weight' => 0],
    ['question' => '🐩 Пудель', 'answer' => 'Poodle \n (пудл)', 'weight' => 0],
    ['question' => '🦮 Собака-поводырь', 'answer' => 'Guide dog \n (гайд дог)', 'weight' => 0],
    ['question' => '🐕‍🦺 Служебная собака', 'answer' => 'Service dog \n (сервис дог)', 'weight' => 0],
    ['question' => '🐈 Кошка', 'answer' => 'Cat \n (кэт)', 'weight' => 0],
    ['question' => '🐈‍⬛ Черная кошка', 'answer' => 'Black cat \n (блэк кэт)', 'weight' => 0],
    ['question' => '🪶 Перо', 'answer' => 'Feather \n (фэзер)', 'weight' => 0],
    ['question' => '🪽 Крыло', 'answer' => 'Wing \n (уинг)', 'weight' => 0],
    ['question' => '🐓 Петух', 'answer' => 'Rooster \n (рустер)', 'weight' => 0],
    ['question' => '🦃 Индюк', 'answer' => 'Turkey \n (терки)', 'weight' => 0],
    ['question' => '🦤 Птица додо', 'answer' => 'Dodo \n (додо)', 'weight' => 0],
    ['question' => '🦚 Павлин', 'answer' => 'Peacock \n (пикок)', 'weight' => 0],
    ['question' => '🦜 Попугай', 'answer' => 'Parrot \n (пэррот)', 'weight' => 0],
    ['question' => '🦢 Лебедь', 'answer' => 'Swan \n (свон)', 'weight' => 0],
    ['question' => '🦩 Фламинго', 'answer' => 'Flamingo \n (фламинго)', 'weight' => 0],
    ['question' => '🕊 Голубь', 'answer' => 'Dove \n (дав)', 'weight' => 0],
    ['question' => '🐇 Кролик', 'answer' => 'Rabbit \n (рэббит)', 'weight' => 0],
    ['question' => '🦝 Енот', 'answer' => 'Raccoon \n (раккун)', 'weight' => 0],
    ['question' => '🦨 Скунс', 'answer' => 'Skunk \n (сканк)', 'weight' => 0],
    ['question' => '🐾 Следы лап', 'answer' => 'Paw prints \n (поу принтс)', 'weight' => 0],
    ['question' => '🦔 Ёжик', 'answer' => 'Hedgehog \n (хеджхог)', 'weight' => 0],
    ['question' => '🐿 Бурундук', 'answer' => 'Chipmunk \n (чипманк)', 'weight' => 0],
    ['question' => '🐀 Крыса', 'answer' => 'Rat \n (рэт)', 'weight' => 0],
    ['question' => '🐁 Мышь', 'answer' => 'Mouse \n (маус)', 'weight' => 0],
    ['question' => '🦥 Ленивец', 'answer' => 'Sloth \n (слот)', 'weight' => 0],
    ['question' => '🦦 Выдра', 'answer' => 'Otter \n (оттер)', 'weight' => 0],
    ['question' => '🦫 Бобр', 'answer' => 'Beaver \n (бивер)', 'weight' => 0],
    ['question' => '🦡 Барсук', 'answer' => 'Badger \n (бэджер)', 'weight' => 0],
    ['question' => '🐉 Дракон', 'answer' => 'Dragon \n (драгон)', 'weight' => 0],
    ['question' => '🐲 Восточный дракон', 'answer' => 'Eastern dragon \n (истерн драгон)', 'weight' => 0],
    ['question' => '🌵 Кактус', 'answer' => 'Cactus \n (кактус)', 'weight' => 0],
    ['question' => '🎄 Рождественская ёлка', 'answer' => 'Christmas tree \n (кристмас три)', 'weight' => 0],
    ['question' => '🌲 Ёлка', 'answer' => 'Pine tree \n (пайн три)', 'weight' => 0],
    ['question' => '🌳 Дерево', 'answer' => 'Tree \n (три)', 'weight' => 0],
    ['question' => '🌴 Пальма', 'answer' => 'Palm tree \n (палм три)', 'weight' => 0],
    ['question' => '🪵 Бревно', 'answer' => 'Log \n (лог)', 'weight' => 0],
    ['question' => '🌱 Росток', 'answer' => 'Seedling \n (сидлинг)', 'weight' => 0],
    ['question' => '🌿 Ветка', 'answer' => 'Herb \n (хёрб)', 'weight' => 0],
    ['question' => '☘️ Трилистник', 'answer' => 'Shamrock \n (шамрок)', 'weight' => 0],
    ['question' => '🍀 Четырёхлистник', 'answer' => 'Four-leaf clover \n (фор лиф кловер)', 'weight' => 0],
    ['question' => '🎍 Бамбук', 'answer' => 'Bamboo \n (бэмбу)', 'weight' => 0],
    ['question' => '🪴 Растение в горшке', 'answer' => 'Potted plant \n (поттед плант)', 'weight' => 0],
    ['question' => '🎋 Танабата', 'answer' => 'Tanabata tree \n (танабата три)', 'weight' => 0],
    ['question' => '🍃 Лист', 'answer' => 'Leaf \n (лиф)', 'weight' => 0],
    ['question' => '🍂 Опавший лист', 'answer' => 'Fallen leaf \n (фоллен лиф)', 'weight' => 0],
    ['question' => '🍁 Кленовый лист', 'answer' => 'Maple leaf \n (мейпл лиф)', 'weight' => 0],
    ['question' => '🪺 Гнездо с яйцами', 'answer' => 'Nest with eggs \n (нест уит эгс)', 'weight' => 0],
    ['question' => '🪹 Пустое гнездо', 'answer' => 'Empty nest \n (эмпти нест)', 'weight' => 0],
    ['question' => '🍄 Гриб', 'answer' => 'Mushroom \n (машрум)', 'weight' => 0],
    ['question' => '🐚 Ракушка', 'answer' => 'Shell \n (шелл)', 'weight' => 0],
    ['question' => '🪸 Кораллы', 'answer' => 'Coral \n (корал)', 'weight' => 0],
    ['question' => '🪨 Камень', 'answer' => 'Rock \n (рок)', 'weight' => 0],
    ['question' => '🌾 Злак', 'answer' => 'Sheaf \n (шиф)', 'weight' => 0],
    ['question' => '💐 Букет', 'answer' => 'Bouquet \n (букей)', 'weight' => 0],
    ['question' => '🌷 Тюльпан', 'answer' => 'Tulip \n (тюлип)', 'weight' => 0],
    ['question' => '🌹 Роза', 'answer' => 'Rose \n (роуз)', 'weight' => 0],
    ['question' => '🥀 Увядшая роза', 'answer' => 'Wilted rose \n (вилтед роуз)', 'weight' => 0],
    ['question' => '🪻 Сирень', 'answer' => 'Lilac \n (лайлак)', 'weight' => 0],
    ['question' => '🪷 Лотос', 'answer' => 'Lotus \n (лотус)', 'weight' => 0],
    ['question' => '🌺 Гибискус', 'answer' => 'Hibiscus \n (хибискус)', 'weight' => 0],
    ['question' => '🌸 Цветок сакуры', 'answer' => 'Cherry blossom \n (черри блоссом)', 'weight' => 0],
    ['question' => '🌼 Цветок', 'answer' => 'Blossom \n (блоссом)', 'weight' => 0],
    ['question' => '🌻 Подсолнух', 'answer' => 'Sunflower \n (санфлауэр)', 'weight' => 0],
    ['question' => '🌞 Солнце с лицом', 'answer' => 'Sun with face \n (сан уит фейс)', 'weight' => 0],
    ['question' => '🌝 Полная луна с лицом', 'answer' => 'Full moon with face \n (фул мун уит фейс)', 'weight' => 0],
    ['question' => '🌎 Планета Земля (Америка)', 'answer' => 'Globe showing Americas \n (глоуб шоувинг америкс)', 'weight' => 0],
    ['question' => '🌍 Планета Земля (Европа и Африка)', 'answer' => 'Globe showing Europe-Africa \n (глоуб шоувинг йоуроп африка)', 'weight' => 0],
    ['question' => '🌏 Планета Земля (Азия и Австралия)', 'answer' => 'Globe showing Asia-Australia \n (глоуб шоувинг эйжа австралия)', 'weight' => 0],
    ['question' => '🌈 Радуга', 'answer' => 'Rainbow \n (рейнбоу)', 'weight' => 0],
    ['question' => '🌪 Торнадо', 'answer' => 'Tornado \n (торнадо)', 'weight' => 0],
    ['question' => '🔥 Огонь', 'answer' => 'Fire \n (файр)', 'weight' => 0],
    ['question' => '☄️ Метеор', 'answer' => 'Comet \n (комет)', 'weight' => 0],
    ['question' => '☀️ Солнце', 'answer' => 'Sun \n (сан)', 'weight' => 0],
    ['question' => '☁️ Облако', 'answer' => 'Cloud \n (клауд)', 'weight' => 0],
    ['question' => '❄️ Снежинка', 'answer' => 'Snowflake \n (сноуфлейк)', 'weight' => 0],
    ['question' => '⛄️ Снеговик', 'answer' => 'Snowman \n (сноумен)', 'weight' => 0],
    ['question' => '💨 Ветер', 'answer' => 'Wind \n (уинд)', 'weight' => 0],
    ['question' => '💧 Капля воды', 'answer' => 'Drop \n (дроп)', 'weight' => 0],
    ['question' => '🫧 Пузырьки', 'answer' => 'Bubbles \n (баблс)', 'weight' => 0],
    ['question' => '☔️ Зонт с дождем', 'answer' => 'Umbrella with rain \n (амбрелла уит рэйн)', 'weight' => 0],
    ['question' => '🌊 Волна', 'answer' => 'Wave \n (вэйв)', 'weight' => 0],
    ['question' => '🌫 Туман', 'answer' => 'Fog \n (фог)', 'weight' => 0],

    ['question' => '🍏 Зелёное яблоко', 'answer' => 'Green apple \n (грин эпл)', 'weight' => 0],
    ['question' => '🍎 Красное яблоко', 'answer' => 'Red apple \n (ред эпл)', 'weight' => 0],
    ['question' => '🍐 Груша', 'answer' => 'Pear \n (пеар)', 'weight' => 0],
    ['question' => '🍊 Апельсин', 'answer' => 'Orange \n (орандж)', 'weight' => 0],
    ['question' => '🍋 Лимон', 'answer' => 'Lemon \n (лемон)', 'weight' => 0],
    ['question' => '🍌 Банан', 'answer' => 'Banana \n (банана)', 'weight' => 0],
    ['question' => '🍉 Арбуз', 'answer' => 'Watermelon \n (уотермелон)', 'weight' => 0],
    ['question' => '🍇 Виноград', 'answer' => 'Grapes \n (грейпс)', 'weight' => 0],
    ['question' => '🍓 Клубника', 'answer' => 'Strawberry \n (строуберри)', 'weight' => 0],
    ['question' => '🍅 Помидор', 'answer' => 'Tomato \n (томейто)', 'weight' => 0],
    ['question' => '🥝 Киви', 'answer' => 'Kiwi \n (киви)', 'weight' => 0],
    ['question' => '🥥 Кокос', 'answer' => 'Coconut \n (коконат)', 'weight' => 0],
    ['question' => '🍍 Ананас', 'answer' => 'Pineapple \n (пайнэппл)', 'weight' => 0],
    ['question' => '🥭 Манго', 'answer' => 'Mango \n (манго)', 'weight' => 0],
    ['question' => '🍑 Персик', 'answer' => 'Peach \n (пич)', 'weight' => 0],
    ['question' => '🍒 Вишня', 'answer' => 'Cherry \n (черри)', 'weight' => 0],
    ['question' => '🍈 Дыня', 'answer' => 'Melon \n (мелон)', 'weight' => 0],
    ['question' => '🫐 Черника', 'answer' => 'Blueberry \n (блюберри)', 'weight' => 0],
    ['question' => '🍆 Баклажан', 'answer' => 'Eggplant \n (эгплант)', 'weight' => 0],
    ['question' => '🥑 Авокадо', 'answer' => 'Avocado \n (авокадо)', 'weight' => 0],
    ['question' => '🫛 Зеленый стручковый горошек', 'answer' => 'Peapod \n (пипод)', 'weight' => 0],
    ['question' => '🥦 Брокколи', 'answer' => 'Broccoli \n (брокколи)', 'weight' => 0],
    ['question' => '🥬 Листовая зелень', 'answer' => 'Leafy green \n (лифи грин)', 'weight' => 0],
    ['question' => '🥒 Огурец', 'answer' => 'Cucumber \n (кьюкамбер)', 'weight' => 0],
    ['question' => '🌶 Перец чили', 'answer' => 'Hot pepper \n (хот пеппер)', 'weight' => 0],
    ['question' => '🫑 Сладкий перец', 'answer' => 'Bell pepper \n (белл пеппер)', 'weight' => 0],
    ['question' => '🌽 Кукуруза', 'answer' => 'Corn \n (корн)', 'weight' => 0],
    ['question' => '🥕 Морковь', 'answer' => 'Carrot \n (кэррот)', 'weight' => 0],
    ['question' => '🫒 Оливка', 'answer' => 'Olive \n (олив)', 'weight' => 0],
    ['question' => '🧄 Чеснок', 'answer' => 'Garlic \n (гарлик)', 'weight' => 0],
    ['question' => '🧅 Лук', 'answer' => 'Onion \n (онион)', 'weight' => 0],
    ['question' => '🥔 Картофель', 'answer' => 'Potato \n (потейто)', 'weight' => 0],
    ['question' => '🍠 Сладкий картофель', 'answer' => 'Sweet potato \n (свит потейто)', 'weight' => 0],
    ['question' => '🍞 Хлеб', 'answer' => 'Bread \n (брэд)', 'weight' => 0],
    ['question' => '🥨 Крендель', 'answer' => 'Pretzel \n (претзел)', 'weight' => 0],
    ['question' => '🍳 Жареное яйцо', 'answer' => 'Fried egg \n (фрайд эг)', 'weight' => 0],
    ['question' => '🥚 Яйцо', 'answer' => 'Egg \n (эг)', 'weight' => 0],
    ['question' => '🧀 Сыр', 'answer' => 'Cheese \n (чиз)', 'weight' => 0],
    ['question' => '🍕 Пицца', 'answer' => 'Pizza \n (питса)', 'weight' => 0],
    ['question' => '🍟 Картофель фри', 'answer' => 'French fries \n (френч фрайс)', 'weight' => 0],
    ['question' => '🍔 Бургер', 'answer' => 'Burger \n (бургер)', 'weight' => 0],
    ['question' => '🌭 Хот-дог', 'answer' => 'Hot dog \n (хот дог)', 'weight' => 0],
    ['question' => '🦴 Кость', 'answer' => 'Bone \n (бон)', 'weight' => 0],
    ['question' => '🍖 Мясо на косточке', 'answer' => 'Meat on the bone \n (мит он зе бон)', 'weight' => 0],
    ['question' => '🍗 Куриное бедро', 'answer' => 'Chicken leg \n (чикен лег)', 'weight' => 0],
    ['question' => '🥩 Стейк', 'answer' => 'Steak \n (стейк)', 'weight' => 0],
    ['question' => '🥓 Бекон', 'answer' => 'Bacon \n (бэйкон)', 'weight' => 0],
    ['question' => '🥪 Сэндвич', 'answer' => 'Sandwich \n (сэндвич)', 'weight' => 0],
    ['question' => '🥄 Ложка', 'answer' => 'Spoon \n (спун)', 'weight' => 0],
    ['question' => '🍽 Столовый прибор', 'answer' => 'Fork and knife \n (форк энд найф)', 'weight' => 0],
    ['question' => '🥢 Палочки для еды', 'answer' => 'Chopsticks \n (чопстикс)', 'weight' => 0],
    ['question' => '🧂 Соль', 'answer' => 'Salt \n (солт)', 'weight' => 0],
    ['question' => '🫖 Чайник', 'answer' => 'Teapot \n (типот)', 'weight' => 0],
    ['question' => '🍩 Пончик', 'answer' => 'Donut \n (доунат)', 'weight' => 0],
    ['question' => '🍰 Пирожное', 'answer' => 'Cake \n (кейк)', 'weight' => 0],


    ['question' => '⚽️ Футбольный мяч', 'answer' => 'Soccer ball \n (соккер бол)', 'weight' => 0],
    ['question' => '🏀 Баскетбольный мяч', 'answer' => 'Basketball \n (баскетбол)', 'weight' => 0],
    ['question' => '🏈 Американский футбольный мяч', 'answer' => 'American football \n (американ футболь)', 'weight' => 0],
    ['question' => '⚾️ Бейсбольный мяч', 'answer' => 'Baseball \n (бейсбол)', 'weight' => 0],
    ['question' => '🥎 Софтбольный мяч', 'answer' => 'Softball \n (софтбол)', 'weight' => 0],
    ['question' => '🪃 Бумеранг', 'answer' => 'Boomerang \n (бумеранг)', 'weight' => 0],
    ['question' => '🛹 Скейтборд', 'answer' => 'Skateboard \n (скейтборд)', 'weight' => 0],
    ['question' => '⛸ Коньки', 'answer' => 'Ice skates \n (айс скейтс)', 'weight' => 0],
    ['question' => '⛷ Лыжи', 'answer' => 'Skis \n (скис)', 'weight' => 0],
    ['question' => '🪂 Парашют', 'answer' => 'Parachute \n (пэрэщут)', 'weight' => 0],
    ['question' => '🏊‍♀️ Плавание', 'answer' => 'Swimming \n (свимминг)', 'weight' => 0],
    ['question' => '🎿 Горные лыжи', 'answer' => 'Skiing \n (скиинг)', 'weight' => 0],
    ['question' => '🤿 Акваланг', 'answer' => 'Diving mask \n (дайвинг маск)', 'weight' => 0],
    ['question' => '🏹 Лук и стрелы', 'answer' => 'Bow and arrow \n (боу энд эроу)', 'weight' => 0],
    ['question' => '🎧 Наушники', 'answer' => 'Headphones \n (хэдфоунс)', 'weight' => 0],
    ['question' => '🥁 Барабан', 'answer' => 'Drum \n (драм)', 'weight' => 0],
    ['question' => '🎯 Дартс', 'answer' => 'Darts \n (дартс)', 'weight' => 0],
    ['question' => '🎮 Видеоигра', 'answer' => 'Video game \n (видео гейм)', 'weight' => 0],
    ['question' => '🏆 Кубок', 'answer' => 'Trophy \n (трофи)', 'weight' => 0],
    ['question' => '🚴 Велосипедист', 'answer' => 'Cyclist \n (сайклист)', 'weight' => 0],
    ['question' => '🚗 Машина', 'answer' => 'Car \n (кар)', 'weight' => 0],
    ['question' => '🚌 Автобус', 'answer' => 'Bus \n (бас)', 'weight' => 0],
    ['question' => '🚓 Полицейская машина', 'answer' => 'Police car \n (полис кар)', 'weight' => 0],
    ['question' => '🚜 Трактор', 'answer' => 'Tractor \n (трактор)', 'weight' => 0],
    ['question' => '🚲 Велосипед', 'answer' => 'Bicycle \n (байсикл)', 'weight' => 0],
    ['question' => '✈️ Самолет', 'answer' => 'Airplane \n (эйрплейн)', 'weight' => 0],
    ['question' => '🚂 Поезд', 'answer' => 'Train \n (трейн)', 'weight' => 0],
    ['question' => '🚋 Трамвай', 'answer' => 'Tram \n (трам)', 'weight' => 0],
    ['question' => '🚅 Скоростной поезд', 'answer' => 'High-speed train \n (хай спид трейн)', 'weight' => 0],
];
