<?php

return [
    ['question' => 'Inheritance', 'answer' => 'Наследование', 'weight' => 0],
    ['question' => 'Encapsulation', 'answer' => 'Инкапсуляция', 'weight' => 0],
    ['question' => 'Polymorphism', 'answer' => 'Полиморфизм', 'weight' => 0],
    ['question' => 'Abstraction', 'answer' => 'Абстракция', 'weight' => 0],
    ['question' => 'Query', 'answer' => 'Запрос', 'weight' => 0],
    ['question' => 'Foreign Key', 'answer' => 'Внешний ключ', 'weight' => 0],
    ['question' => 'Constraint', 'answer' => 'Ограничение', 'weight' => 0],
    ['question' => 'Join', 'answer' => 'Соединение', 'weight' => 0],
    ['question' => 'View', 'answer' => 'Представление', 'weight' => 0],
    ['question' => 'Deadlock', 'answer' => 'Взаимная блокировка', 'weight' => 0],
    ['question' => 'Design Pattern', 'answer' => 'Шаблон проектирования', 'weight' => 0],
    ['question' => 'Singleton Pattern', 'answer' => 'Шаблон одиночка', 'weight' => 0],
    ['question' => 'Factory Pattern', 'answer' => 'Фабричный метод', 'weight' => 0],
    ['question' => 'Observer Pattern', 'answer' => 'Шаблон наблюдатель', 'weight' => 0],
    ['question' => 'Decorator Pattern', 'answer' => 'Шаблон декоратор', 'weight' => 0],
    ['question' => 'Strategy Pattern', 'answer' => 'Шаблон стратегия', 'weight' => 0],
    ['question' => 'Repository Pattern', 'answer' => 'Шаблон репозиторий', 'weight' => 0],
    ['question' => 'Dependency Injection', 'answer' => 'Внедрение зависимости', 'weight' => 0],
    ['question' => 'Inversion of Control', 'answer' => 'Инверсия управления', 'weight' => 0],
    ['question' => 'Single Responsibility Principle', 'answer' => 'Принцип единственной ответственности', 'weight' => 0],
    ['question' => 'Open/Closed Principle', 'answer' => 'Принцип открытости/закрытости', 'weight' => 0],
    ['question' => 'Liskov Substitution Principle', 'answer' => 'Принцип подстановки Лисков', 'weight' => 0],
    ['question' => 'Interface Segregation Principle', 'answer' => 'Принцип разделения интерфейсов', 'weight' => 0],
    ['question' => 'Dependency Inversion Principle', 'answer' => 'Принцип инверсии зависимостей', 'weight' => 0],
];
