<?php

return [
                ['question' => 'Алгоритм', 'answer' => 'Algorithm', 'weight' => 0],
                ['question' => 'Переменная', 'answer' => 'Variable', 'weight' => 0],
                ['question' => 'Функция', 'answer' => 'Function', 'weight' => 0],
                ['question' => 'Массив', 'answer' => 'Array', 'weight' => 0],
                ['question' => 'Объект', 'answer' => 'Object', 'weight' => 0],
                ['question' => 'Класс', 'answer' => 'Class', 'weight' => 0],
                ['question' => 'Интерфейс', 'answer' => 'Interface', 'weight' => 0],
                ['question' => 'Наследование', 'answer' => 'Inheritance', 'weight' => 0],
                ['question' => 'Полиморфизм', 'answer' => 'Polymorphism', 'weight' => 0],
                ['question' => 'Инкапсуляция', 'answer' => 'Encapsulation', 'weight' => 0],
                ['question' => 'Абстракция', 'answer' => 'Abstraction', 'weight' => 0],
                ['question' => 'Синтаксис', 'answer' => 'Syntax', 'weight' => 0],
                ['question' => 'Компилятор', 'answer' => 'Compiler', 'weight' => 0],
                ['question' => 'Интерпретатор', 'answer' => 'Interpreter', 'weight' => 0],
                ['question' => 'Библиотека', 'answer' => 'Library', 'weight' => 0],
                ['question' => 'Фреймворк', 'answer' => 'Framework', 'weight' => 0],
                ['question' => 'Модуль', 'answer' => 'Module', 'weight' => 0],
                ['question' => 'Пакет', 'answer' => 'Package', 'weight' => 0],
                ['question' => 'Сборка', 'answer' => 'Build', 'weight' => 0],
                ['question' => 'Отладка', 'answer' => 'Debugging', 'weight' => 0],
                ['question' => 'Рефакторинг', 'answer' => 'Refactoring', 'weight' => 0],
                ['question' => 'Тестирование', 'answer' => 'Testing', 'weight' => 0],
                ['question' => 'Версия', 'answer' => 'Version', 'weight' => 0],
                ['question' => 'Репозиторий', 'answer' => 'Repository', 'weight' => 0],
                ['question' => 'Пулл-реквест', 'answer' => 'Pull Request', 'weight' => 0],
                ['question' => 'Контейнеризация', 'answer' => 'Containerization', 'weight' => 0],
                ['question' => 'Виртуализация', 'answer' => 'Virtualization', 'weight' => 0],
                ['question' => 'Микросервис', 'answer' => 'Microservice', 'weight' => 0],
                ['question' => 'Архитектура', 'answer' => 'Architecture', 'weight' => 0],
                ['question' => 'Разработка', 'answer' => 'Development', 'weight' => 0],
            ];