<?php


return [
                ['question' => 'Возможно, может быть', 'answer' => 'Might, may', 'weight' => 0],
                ['question' => 'Совпадение', 'answer' => 'Coincidence', 'weight' => 0],
                ['question' => 'Ниже', 'answer' => 'Below', 'weight' => 0],
                ['question' => 'Выше', 'answer' => 'Above', 'weight' => 0],
                ['question' => 'Время, грамматическое время', 'answer' => 'Tense', 'weight' => 0],
                ['question' => 'Предлог', 'answer' => 'Preposition', 'weight' => 0],
                ['question' => 'Преимущества', 'answer' => 'Advantages, benefits', 'weight' => 0],
                ['question' => 'Приносить пользу, быть полезным', 'answer' => 'To benefit, to be beneficial', 'weight' => 0],
                ['question' => 'Настойчивый, постоянный', 'answer' => 'Persistent', 'weight' => 0],
                ['question' => 'Жители', 'answer' => 'Inhabitants, residents', 'weight' => 0],
                ['question' => 'Обеспокоенность, опасения', 'answer' => 'Concerns, worries', 'weight' => 0],
                ['question' => 'Определённый, уверенный; определённо', 'answer' => 'Certain, certainly', 'weight' => 0],
                ['question' => 'Психические заболевания', 'answer' => 'Mental illness, mental disorders', 'weight' => 0],
                ['question' => 'Надоело, достало', 'answer' => 'To be sick of', 'weight' => 0],
                ['question' => 'Приобретать, получать; достигать цели', 'answer' => 'Acquire, achieve', 'weight' => 0],
                ['question' => 'Отношение', 'answer' => 'Attitude', 'weight' => 0],
                ['question' => 'Казаться', 'answer' => 'To seem', 'weight' => 0],
                ['question' => 'Появляться, казаться', 'answer' => 'To appear', 'weight' => 0],
                ['question' => 'Конкретный, определённый, особенный', 'answer' => 'Particular', 'weight' => 0],
                ['question' => 'Натощак', 'answer' => 'On an empty stomach', 'weight' => 0],
                ['question' => 'Головокружение', 'answer' => 'Dizziness', 'weight' => 0],
                ['question' => 'Пещера', 'answer' => 'Cave', 'weight' => 0],
                ['question' => 'Восприятие пространства', 'answer' => 'Spatial perception', 'weight' => 0],
                ['question' => 'Перебивать, прерывать', 'answer' => 'Interrupt', 'weight' => 0],
                ['question' => 'Относиться к чему-то, быть связанным с чем-то', 'answer' => 'Related to, connected with', 'weight' => 0],
                ['question' => 'Изобретать', 'answer' => 'Invent', 'weight' => 0],
                ['question' => 'Оснащать, оборудовать', 'answer' => 'To equip', 'weight' => 0],
                ['question' => 'Способность', 'answer' => 'Ability', 'weight' => 0],
                ['question' => 'Бросить пить кофе, перестать пить кофе', 'answer' => 'Give up coffee, go off coffee', 'weight' => 0],
                ['question' => 'Ладить с кем-то', 'answer' => 'Get on with someone', 'weight' => 0],
                ['question' => 'Стать седым', 'answer' => 'Go grey', 'weight' => 0],
                ['question' => 'Исключение', 'answer' => 'Exclusion, exception', 'weight' => 0],
                ['question' => 'Наибольшее беспокойство, главная тревога', 'answer' => 'Greatest concern', 'weight' => 0],
                ['question' => 'Быть удовлетворённым, довольным', 'answer' => 'To be content, to be contented', 'weight' => 0],
                ['question' => 'Усилия', 'answer' => 'Efforts', 'weight' => 0],
                ['question' => 'Получить, добыть, здобути щось', 'answer' => 'Obtain, acquire', 'weight' => 0],
                ['question' => 'Есть в ресторане, питаться вне дома', 'answer' => 'Eat out', 'weight' => 0],
                ['question' => 'Присматривать за кем-то, заботиться о ком-то', 'answer' => 'Look after', 'weight' => 0],
                ['question' => 'По сей день, до настоящего времени', 'answer' => 'Up to the present, to this day', 'weight' => 0],
                ['question' => 'Студия звукозаписи', 'answer' => 'Recording studio', 'weight' => 0],
                ['question' => 'Запрос', 'answer' => 'Query, request', 'weight' => 0],
                ['question' => 'Целевой язык', 'answer' => 'Target language', 'weight' => 0],
                ['question' => 'Контакт, воздействие, погружение в язык', 'answer' => 'Exposure', 'weight' => 0],
                ['question' => 'Улучшать, усовершенствовать', 'answer' => 'To improve, to enhance', 'weight' => 0],
                ['question' => 'Правильный английский', 'answer' => 'Proper English', 'weight' => 0],
                ['question' => 'Я не могу сказать это точно', 'answer' => 'I can\'t say exactly, I can\'t say that for sure', 'weight' => 0],
                ['question' => 'Наставник', 'answer' => 'Mentor', 'weight' => 0],
                ['question' => 'Совет', 'answer' => 'Advice', 'weight' => 0],
                ['question' => 'Экологически чистый', 'answer' => 'Environmentally friendly', 'weight' => 0],
                ['question' => 'Финансирование', 'answer' => 'Funding', 'weight' => 0],
                ['question' => 'Упоминать, вспомнить в разговоре', 'answer' => 'To mention, mentioned', 'weight' => 0],
                ['question' => 'Вежливый', 'answer' => 'Polite', 'weight' => 0],
                ['question' => 'Вежливость', 'answer' => 'Politeness', 'weight' => 0],
                ['question' => 'Послушный', 'answer' => 'Obedient', 'weight' => 0],
                ['question' => 'Случай, повод', 'answer' => 'Occasion', 'weight' => 0],
                ['question' => 'В главной роли, с участием', 'answer' => 'Starring', 'weight' => 0],
                ['question' => 'Смущённый, неловко себя чувствующий; тревожный человек', 'answer' => 'Embarrassed, anxious person', 'weight' => 0],
                ['question' => 'Смущающий, неловкий; тревожиться', 'answer' => 'Embarrassing, to be anxious, to worry', 'weight' => 0],
                ['question' => 'Совершать, брать на себя обязательство', 'answer' => 'To commit', 'weight' => 0],
                ['question' => 'Становиться', 'answer' => 'Become', 'weight' => 0],
                ['question' => 'Казаться', 'answer' => 'To seem', 'weight' => 0],
                ['question' => 'Ехать вдоль', 'answer' => 'To drive along', 'weight' => 0],
                ['question' => 'Нарочно, специально', 'answer' => 'On purpose', 'weight' => 0],
                ['question' => 'Дразнить', 'answer' => 'To tease', 'weight' => 0],
                ['question' => 'Готовая вещь, готовый', 'answer' => 'Ready-made', 'weight' => 0],
                ['question' => 'Следить за новостями, быть в курсе', 'answer' => 'Keep up to date with', 'weight' => 0],
                ['question' => 'Отрывки', 'answer' => 'Excerpts', 'weight' => 0],
                ['question' => 'Человечество', 'answer' => 'Mankind, humanity', 'weight' => 0],
                ['question' => 'Прыжок, скачок', 'answer' => 'Leap', 'weight' => 0],
                ['question' => 'Гигантский, гигант', 'answer' => 'Giant', 'weight' => 0],
                ['question' => 'Появляется, кажется', 'answer' => 'Appears', 'weight' => 0],
                ['question' => 'Без сознания', 'answer' => 'Unconscious', 'weight' => 0],
                ['question' => 'Посвящать', 'answer' => 'Dedicate', 'weight' => 0],
                ['question' => 'Был убит, убит в результате покушения', 'answer' => 'Assassinated', 'weight' => 0],
                ['question' => 'Толпа', 'answer' => 'Crowd', 'weight' => 0],
                ['question' => 'Сомнение', 'answer' => 'Doubt', 'weight' => 0],
                ['question' => 'Делать вывод, заключать', 'answer' => 'Conclude, draw a conclusion', 'weight' => 0],
                ['question' => 'До сих пор, пока что; поскольку, насколько', 'answer' => 'So far, up to now; insofar as', 'weight' => 0],
                ['question' => 'Город грехов', 'answer' => 'Sin City', 'weight' => 0],
                ['question' => 'Вывод, заключение', 'answer' => 'Conclusion', 'weight' => 0],
                ['question' => 'Преданный делу, приверженный; совершённый', 'answer' => 'Committed', 'weight' => 0],
                ['question' => 'Возглавлять, вести', 'answer' => 'Lead', 'weight' => 0],
                ['question' => 'Возглавил, вёл', 'answer' => 'Led', 'weight' => 0],
                ['question' => 'Осудить, приговорить; приговор', 'answer' => 'Sentence', 'weight' => 0],
                ['question' => 'Беглец', 'answer' => 'Fugitive', 'weight' => 0],
                ['question' => 'Жестокий, насильственный; жестокость, насилие', 'answer' => 'Violent, violence', 'weight' => 0],
                ['question' => 'Несчастный случай, авария', 'answer' => 'Accident', 'weight' => 0],
                ['question' => 'Попытка, пытаться', 'answer' => 'Attempt', 'weight' => 0],
                ['question' => 'Заставили, вынужденный', 'answer' => 'Forced', 'weight' => 0],
                ['question' => 'Передать, вручить', 'answer' => 'Hand over', 'weight' => 0],
                ['question' => 'Грузовик, британский вариант', 'answer' => 'Lorry, truck', 'weight' => 0],
                ['question' => 'Очевидец', 'answer' => 'Eyewitness', 'weight' => 0],
                ['question' => 'Значения, определения', 'answer' => 'Definitions', 'weight' => 0],
                ['question' => 'Воры; злодеи', 'answer' => 'Thieves, villains', 'weight' => 0],
                ['question' => 'Налёт, рейд', 'answer' => 'Raid', 'weight' => 0],
                ['question' => 'Поведение', 'answer' => 'Behaviour, behavior', 'weight' => 0],
                ['question' => 'Неподвижный; всё ещё', 'answer' => 'Still', 'weight' => 0],
                ['question' => 'Оставаться; покидать', 'answer' => 'Stay, leave', 'weight' => 0],
                ['question' => 'Кульминация шутки, финальная реплика', 'answer' => 'Punch line', 'weight' => 0],
                ['question' => 'Выгореть эмоционально, перегореть, сгореть в переносном смысле', 'answer' => 'Burn out', 'weight' => 0],
                ['question' => 'Повторяющийся', 'answer' => 'Repetitive', 'weight' => 0],
                ['question' => 'Ложный; ложь', 'answer' => 'False, lie', 'weight' => 0],
                ['question' => 'Смущённый; тревожно', 'answer' => 'Embarrassed, anxious', 'weight' => 0],
                ['question' => 'Портить', 'answer' => 'Spoil', 'weight' => 0],
                ['question' => 'Последовательность; секвенсор', 'answer' => 'Sequence, sequencer', 'weight' => 0],
                ['question' => 'Меня с кем-то перепутали', 'answer' => 'Mistook me for someone else', 'weight' => 0],
                ['question' => 'Бармен', 'answer' => 'Barkeeper, bartender', 'weight' => 0],
                ['question' => 'Я полагаю, думаю', 'answer' => 'I guess', 'weight' => 0],
                ['question' => 'Очень важный, необходимый', 'answer' => 'Essential', 'weight' => 0],
                ['question' => 'Без сомнений, точно', 'answer' => 'For sure', 'weight' => 0],
                ['question' => 'Например', 'answer' => 'For instance, for example', 'weight' => 0],
                ['question' => 'Такой как, например', 'answer' => 'Such as', 'weight' => 0],
                ['question' => 'Захватывающий, увлекательный; компилирование', 'answer' => 'Compelling, fascinating; compiling', 'weight' => 0],
                ['question' => 'Очередь, черёд, ход', 'answer' => 'Queue, turn', 'weight' => 0],
                ['question' => 'Указать вниз', 'answer' => 'Point down', 'weight' => 0],
                ['question' => 'Иметь влияние на что-то', 'answer' => 'To have an influence on, to influence', 'weight' => 0],
                ['question' => 'Зарабатывать на жизнь таксистом', 'answer' => 'Make a living as a taxi driver', 'weight' => 0],
                ['question' => 'Справляться с плотным движением', 'answer' => 'To cope with heavy traffic', 'weight' => 0],
                ['question' => 'Иметь дело с трудными пассажирами', 'answer' => 'Deal with difficult passengers', 'weight' => 0],
                ['question' => 'Иметь стабильный доход', 'answer' => 'Earn a steady income', 'weight' => 0],
                ['question' => 'Быть за рулём, быть в дороге весь день', 'answer' => 'Be on the road all day', 'weight' => 0],
                ['question' => 'Пробки, заторы, перегруженное движение', 'answer' => 'Traffic congestion', 'weight' => 0],
                ['question' => 'Час пик', 'answer' => 'Rush hour', 'weight' => 0],
                ['question' => 'Кража', 'answer' => 'Theft', 'weight' => 0],
                ['question' => 'Осознавать, понимать, усвідомлювати', 'answer' => 'Realize', 'weight' => 0],
                ['question' => 'Преувеличивать', 'answer' => 'Exaggerate', 'weight' => 0],
                ['question' => 'Храбрый; храбрость', 'answer' => 'Brave, bravery', 'weight' => 0],
                ['question' => 'Раскрылось, выяснилось; превратились', 'answer' => 'Revealed, turned into', 'weight' => 0],
                ['question' => 'Человек, который откладывает дела', 'answer' => 'Procrastinator', 'weight' => 0],
                ['question' => 'Мудрый', 'answer' => 'Wise', 'weight' => 0],
                ['question' => 'Мудро', 'answer' => 'Wisely', 'weight' => 0],
                ['question' => 'Отвлекаться', 'answer' => 'To get distracted', 'weight' => 0],
                ['question' => 'Значения, определения', 'answer' => 'Definitions', 'weight' => 0],
                ['question' => 'Обращать внимание; привлекать внимание', 'answer' => 'Pay attention, attract attention', 'weight' => 0],
                ['question' => 'Получить, добыть', 'answer' => 'Obtain', 'weight' => 0],
                ['question' => 'Продолжать, приступить к делу; ладить', 'answer' => 'Get on with', 'weight' => 0],
                ['question' => 'Быть в раздумьях, сомневаться между двумя вариантами', 'answer' => 'Be in two minds', 'weight' => 0],
                ['question' => 'Расслабиться, развеяться; распустить волосы', 'answer' => 'Let your hair down', 'weight' => 0],
                ['question' => 'Разрядить обстановку, растопить лёд', 'answer' => 'Break the ice', 'weight' => 0],
                ['question' => 'Учить на память', 'answer' => 'Learn by heart', 'weight' => 0],
                ['question' => 'Ходить по магазинам без покупки, смотреть витрины', 'answer' => 'Go window shopping', 'weight' => 0],
                ['question' => 'Сразу, немедленно', 'answer' => 'Straight away', 'weight' => 0],
                ['question' => 'Доводить дела до конца, добиваться результата', 'answer' => 'Get things done', 'weight' => 0],
                ['question' => 'Мудрый', 'answer' => 'Wise', 'weight' => 0],
                ['question' => 'Уложиться в сроки', 'answer' => 'To meet the deadline', 'weight' => 0],
                ['question' => 'Нырять с аквалангом', 'answer' => 'Scuba diving', 'weight' => 0],
                ['question' => 'Путешествовать с рюкзаком', 'answer' => 'To backpack around', 'weight' => 0],
                ['question' => 'Окружающая среда, окружение', 'answer' => 'Environment', 'weight' => 0],
                ['question' => 'Предугадать, предсказать', 'answer' => 'Predict', 'weight' => 0],
                ['question' => 'Живая ткань', 'answer' => 'Living tissue', 'weight' => 0],
                ['question' => 'Засухи', 'answer' => 'Droughts', 'weight' => 0],
                ['question' => 'Наводнение', 'answer' => 'Flood', 'weight' => 0],
                ['question' => 'Существовать', 'answer' => 'Exist', 'weight' => 0],
                ['question' => 'Прогноз, предсказание', 'answer' => 'Prediction', 'weight' => 0],
                ['question' => 'Непредсказуемый', 'answer' => 'Unpredictable', 'weight' => 0],
                ['question' => 'Гарнитура, наушники с микрофоном', 'answer' => 'Headset', 'weight' => 0],
                ['question' => 'Ударный, акцентированный; в стрессе', 'answer' => 'Stressed', 'weight' => 0],
                ['question' => 'Влиять на что-то, иметь влияние', 'answer' => 'To affect, to have an effect on', 'weight' => 0],
                ['question' => 'Я ничего из этого не понял', 'answer' => 'I didn\'t catch any of that', 'weight' => 0],
                ['question' => 'Скобки', 'answer' => 'Brackets', 'weight' => 0],
                ['question' => 'Упоминать', 'answer' => 'To mention', 'weight' => 0],
                ['question' => 'Удалённый, дистанционный', 'answer' => 'Remote', 'weight' => 0],
                ['question' => 'Искусственный интеллект', 'answer' => 'Artificial intelligence', 'weight' => 0],
                ['question' => 'Сесть за учёбу, начать серьёзно учиться', 'answer' => 'Hit the books', 'weight' => 0],
                ['question' => 'Выдать секрет, проболтаться', 'answer' => 'To spill the beans', 'weight' => 0],
                ['question' => 'Очень редко', 'answer' => 'Once in a blue moon', 'weight' => 0],
                ['question' => 'Чувствовать себя плохо, быть не в форме', 'answer' => 'Under the weather', 'weight' => 0],
                ['question' => 'Очень дорого стоить', 'answer' => 'To cost an arm and a leg', 'weight' => 0],
                ['question' => 'Что-то хорошее, что сначала казалось плохим', 'answer' => 'A blessing in disguise', 'weight' => 0],
                ['question' => 'Что-то хорошее, что вначале казалось плохим', 'answer' => 'A blessing in disguise', 'weight' => 0],
                ['question' => 'Твой ход, решение за тобой', 'answer' => 'The ball is in your court', 'weight' => 0],
                ['question' => 'Засиживаться допоздна за работой или учёбой', 'answer' => 'Burn the midnight oil', 'weight' => 0],
                ['question' => 'Время на исходе', 'answer' => 'Running out of time', 'weight' => 0],
                ['question' => 'Переполненный людьми', 'answer' => 'Overcrowded', 'weight' => 0],

            ];