<?php


return [

    ['question' => 'Автоматический выключатель', 'answer' => 'Breaker', 'weight' => 0],
    ['question' => 'Термостат', 'answer' => 'Thermostat', 'weight' => 0],
    ['question' => 'Электрическая цепь', 'answer' => 'Circuit', 'weight' => 0],
    ['question' => 'Розетка', 'answer' => 'Outlet', 'weight' => 0],
    ['question' => 'Труба', 'answer' => 'Conduit', 'weight' => 0],
    ['question' => 'Проводка', 'answer' => 'Wiring', 'weight' => 0],
    ['question' => 'Потолочный вентилятор', 'answer' => 'Ceiling fan', 'weight' => 0],
    ['question' => 'Фильтр', 'answer' => 'Filter', 'weight' => 0],
    ['question' => 'Медная труба', 'answer' => 'Copper pipe', 'weight' => 0],
    ['question' => 'Радиатор', 'answer' => 'Radiator', 'weight' => 0],
    ['question' => 'Утеплитель', 'answer' => 'Insulation', 'weight' => 0],
    ['question' => 'Вытяжной вентилятор', 'answer' => 'Exhaust fan', 'weight' => 0],
    ['question' => 'Розетка с защитой от утечек', 'answer' => 'GFCI (Ground Fault Circuit Interrupter)', 'weight' => 0],
    ['question' => 'Чердак', 'answer' => 'Attic', 'weight' => 0],
    ['question' => 'Воздуховод', 'answer' => 'Ductwork', 'weight' => 0],
    ['question' => 'Система отопления, вентиляции и кондиционирования', 'answer' => 'HVAC (Heating, Ventilation, and Air Conditioning)', 'weight' => 0],
    ['question' => 'Осветительный прибор', 'answer' => 'Fixture', 'weight' => 0],
    ['question' => 'Давление воды', 'answer' => 'Water pressure', 'weight' => 0],
    ['question' => 'Электрическая коробка', 'answer' => 'Electrical box', 'weight' => 0],
    ['question' => 'Тестер', 'answer' => 'Tester', 'weight' => 0],
    ['question' => 'Сантехника', 'answer' => 'Plumbing', 'weight' => 0],
    ['question' => 'Напряжение', 'answer' => 'Voltage', 'weight' => 0],
    ['question' => 'Предохранитель', 'answer' => 'Fuse', 'weight' => 0],
    ['question' => 'Электрический щиток', 'answer' => 'Panel', 'weight' => 0],
    ['question' => 'Заземляющий провод', 'answer' => 'Ground wire', 'weight' => 0],
    ['question' => 'Термостат', 'answer' => 'Thermostat', 'weight' => 0],
    ['question' => 'Утечка', 'answer' => 'Leak', 'weight' => 0],
    ['question' => 'Защита от перенапряжения', 'answer' => 'Surge protector', 'weight' => 0],
    ['question' => 'Соединительная коробка', 'answer' => 'Junction box', 'weight' => 0],
    ['question' => 'Фазный провод', 'answer' => 'Hot wire', 'weight' => 0],
    ['question' => 'Нулевой провод', 'answer' => 'Neutral wire', 'weight' => 0],
    ['question' => 'Щиток автоматов', 'answer' => 'Breaker panel', 'weight' => 0],
    ['question' => 'Кабель CAT6 для интернета', 'answer' => 'Cat6 cable', 'weight' => 0],
    ['question' => 'Вентиляция', 'answer' => 'Ventilation', 'weight' => 0],
    ['question' => 'Кран', 'answer' => 'Faucet', 'weight' => 0],
    ['question' => 'Плинтусный обогреватель', 'answer' => 'Baseboard heater', 'weight' => 0],
    ['question' => 'Поток воздуха', 'answer' => 'Airflow', 'weight' => 0],
    ['question' => 'Герметик', 'answer' => 'Caulking', 'weight' => 0],
    ['question' => 'Водонагреватель', 'answer' => 'Water heater', 'weight' => 0],
    ['question' => 'Дренаж', 'answer' => 'Drainage', 'weight' => 0],
    ['question' => 'Насос для откачки воды', 'answer' => 'Sump pump', 'weight' => 0],
    ['question' => 'Конденсатор', 'answer' => 'Condenser', 'weight' => 0],
    ['question' => 'Компрессор', 'answer' => 'Compressor', 'weight' => 0],
    ['question' => 'Испаритель', 'answer' => 'Evaporator', 'weight' => 0],
    ['question' => 'Хладагент', 'answer' => 'Refrigerant', 'weight' => 0],
    ['question' => 'Утеплитель для воздуховодов', 'answer' => 'Duct insulation', 'weight' => 0],
    ['question' => 'Поддон для слива', 'answer' => 'Drain pan', 'weight' => 0],
    ['question' => 'Водопроводная линия', 'answer' => 'Water line', 'weight' => 0],
    ['question' => 'Смягчитель воды', 'answer' => 'Softener', 'weight' => 0],
    ['question' => 'Канализационная линия', 'answer' => 'Sewer line', 'weight' => 0],
    ['question' => 'Газовый клапан', 'answer' => 'Gas valve', 'weight' => 0],
    ['question' => 'Слив раковины', 'answer' => 'Sink drain', 'weight' => 0],
    ['question' => 'Слив душа', 'answer' => 'Shower drain', 'weight' => 0],
    ['question' => 'Унитаз', 'answer' => 'Toilet', 'weight' => 0],
    ['question' => 'Вентиляция', 'answer' => 'Ventilation', 'weight' => 0],
    ['question' => 'Система радиационного отопления', 'answer' => 'Radiant heating', 'weight' => 0],
    ['question' => 'Подогрев пола', 'answer' => 'Radiant floor', 'weight' => 0],
    ['question' => 'Гидравлическая система', 'answer' => 'Hydronic system', 'weight' => 0],
    ['question' => 'Система фильтрации воздуха', 'answer' => 'Air filtration', 'weight' => 0],
    ['question' => 'Осушитель воздуха', 'answer' => 'Dehumidifier', 'weight' => 0],
    ['question' => 'Увлажнитель воздуха', 'answer' => 'Humidifier', 'weight' => 0],
    ['question' => 'Детектор угарного газа', 'answer' => 'Carbon monoxide detector', 'weight' => 0],
    ['question' => 'Дымовая сигнализация', 'answer' => 'Smoke alarm', 'weight' => 0],
    ['question' => 'Система безопасности', 'answer' => 'Security system', 'weight' => 0],
    ['question' => 'Дверной звонок', 'answer' => 'Doorbell', 'weight' => 0],
    ['question' => 'Видеозвонок', 'answer' => 'Video doorbell', 'weight' => 0],
    ['question' => 'Система домофона', 'answer' => 'Intercom system', 'weight' => 0],
    ['question' => 'Плинтус', 'answer' => 'Baseboard', 'weight' => 0],
    ['question' => 'Электрическая труба', 'answer' => 'Electrical conduit', 'weight' => 0],
    ['question' => 'Крышка розетки', 'answer' => 'Outlet cover', 'weight' => 0],
    ['question' => 'Вентиляция сушилки', 'answer' => 'Dryer vent', 'weight' => 0],
    ['question' => 'Газовая линия', 'answer' => 'Gas line', 'weight' => 0],
    ['question' => 'Посудомоечная машина', 'answer' => 'Dishwasher', 'weight' => 0],
    ['question' => 'Воздуховоды', 'answer' => 'Air ducts', 'weight' => 0],
    ['question' => 'Система освещения', 'answer' => 'Lighting system', 'weight' => 0],
    ['question' => 'Встраиваемое освещение', 'answer' => 'Recessed lighting', 'weight' => 0],
    ['question' => 'Направляющие отверстия', 'answer' => 'Pilot holes', 'weight' => 0],
    ['question' => 'Обрешетка', 'answer' => 'Flashing', 'weight' => 0],
    ['question' => 'Балка', 'answer' => 'Joist', 'weight' => 0],
    ['question' => 'Опора', 'answer' => 'Beam', 'weight' => 0],
    ['question' => 'Укрепление', 'answer' => 'Bracing', 'weight' => 0],
    ['question' => 'Штукатурка', 'answer' => 'Plaster', 'weight' => 0],
    ['question' => 'Винты', 'answer' => 'Screws', 'weight' => 0],
    ['question' => 'Болты', 'answer' => 'Bolts', 'weight' => 0],
    ['question' => 'Гвозди', 'answer' => 'Nails', 'weight' => 0],
    ['question' => 'Арматура', 'answer' => 'Rebar', 'weight' => 0],
    ['question' => 'Леса', 'answer' => 'Scaffolding', 'weight' => 0],
    ['question' => 'Фундамент', 'answer' => 'Foundation', 'weight' => 0],
    ['question' => 'Плита', 'answer' => 'Slab', 'weight' => 0],
    ['question' => 'Шлифовка', 'answer' => 'Sanding', 'weight' => 0],
    ['question' => 'Уровень', 'answer' => 'Level', 'weight' => 0],
    ['question' => 'Затирка', 'answer' => 'Grouting', 'weight' => 0],
    ['question' => 'Фанера', 'answer' => 'Plywood', 'weight' => 0],
    ['question' => 'Герметик', 'answer' => 'Sealant', 'weight' => 0],
    ['question' => 'Гидроизоляция', 'answer' => 'Waterproofing', 'weight' => 0],
    ['question' => 'Грунтовка', 'answer' => 'Primer', 'weight' => 0],
    ['question' => 'Герметик', 'answer' => 'Caulk', 'weight' => 0],
    ['question' => 'Люминесцентный светильник', 'answer' => 'Fluorescent light', 'weight' => 0],
    ['question' => 'Система зонирования', 'answer' => 'Zoning system', 'weight' => 0],
    ['question' => 'Резервный генератор', 'answer' => 'Backup generator', 'weight' => 0],
    ['question' => 'Вентилятор для всего дома', 'answer' => 'Whole-house fan', 'weight' => 0],
    ['question' => 'Насос для бассейна', 'answer' => 'Pool pump', 'weight' => 0],
    ['question' => 'Полотенцесушитель', 'answer' => 'Towel warmer', 'weight' => 0],
    ['question' => 'Вентилятор на чердаке', 'answer' => 'Attic fan', 'weight' => 0],
    ['question' => 'Осушитель для подвала', 'answer' => 'Basement dehumidifier', 'weight' => 0],
    ['question' => 'Газовые соединения', 'answer' => 'Gas connections', 'weight' => 0],
    ['question' => 'Осветительные приборы', 'answer' => 'Lighting fixtures', 'weight' => 0],
    ['question' => 'Инвертор солнечных батарей', 'answer' => 'Solar panel inverter', 'weight' => 0],
    ['question' => 'Трансформатор дверного звонка', 'answer' => 'Doorbell transformer', 'weight' => 0],
    ['question' => 'Система полива', 'answer' => 'Sprinkler system', 'weight' => 0],
    ['question' => 'Открывалка для гаражных ворот', 'answer' => 'Garage door opener', 'weight' => 0],
    ['question' => 'Замыкания на землю', 'answer' => 'Ground faults', 'weight' => 0],
    ['question' => 'Аварийное освещение', 'answer' => 'Emergency exit lights', 'weight' => 0],
    ['question' => 'Мотор вентилятора на чердаке', 'answer' => 'Attic fan motor', 'weight' => 0],
    ['question' => 'Ванна джакузи', 'answer' => 'Jacuzzi tub', 'weight' => 0],
    ['question' => 'Панель управления умным домом', 'answer' => 'Smart home control', 'weight' => 0],
    ['question' => 'Гидроизоляция подвала', 'answer' => 'Basement waterproofing', 'weight' => 0],
    ['question' => 'Внешние прожекторы', 'answer' => 'Exterior floodlights', 'weight' => 0],
    ['question' => 'Резервный насос для откачки воды', 'answer' => 'Backup sump pump', 'weight' => 0],
    ['question' => 'Нагревательный мат под полом', 'answer' => 'Underfloor heating mat', 'weight' => 0],
    ['question' => 'Кронштейн для телевизора', 'answer' => 'TV bracket', 'weight' => 0],
    ['question' => 'Уплотнитель', 'answer' => 'Weather stripping', 'weight' => 0],
    ['question' => 'Черепица', 'answer' => 'Shingles', 'weight' => 0],
    ['question' => 'Подкладка', 'answer' => 'Underlayment', 'weight' => 0],
    ['question' => 'Облицовка', 'answer' => 'Siding', 'weight' => 0],
    ['question' => 'Поручни', 'answer' => 'Railing', 'weight' => 0],
    ['question' => 'Балка пола', 'answer' => 'Floor joists', 'weight' => 0],
    ['question' => 'Фонари', 'answer' => 'Flashlights', 'weight' => 0],
    ['question' => 'Утеплительный материал', 'answer' => 'Insulation material', 'weight' => 0],
    ['question' => 'Воздухораспределитель', 'answer' => 'Air handler', 'weight' => 0],
    ['question' => 'Проводка', 'answer' => 'Wiring harness', 'weight' => 0],
    ['question' => 'Тестер цепей', 'answer' => 'Circuit tester', 'weight' => 0],
    ['question' => 'Термопара', 'answer' => 'Thermocouple', 'weight' => 0],
    ['question' => 'Сливной клапан', 'answer' => 'Drain valve', 'weight' => 0],
    ['question' => 'Слив пола', 'answer' => 'Floor drain', 'weight' => 0],
    ['question' => 'Вентиляционная труба', 'answer' => 'Vent pipe', 'weight' => 0],
    ['question' => 'Вытяжная вентиляция', 'answer' => 'Exhaust vent', 'weight' => 0],
    ['question' => 'Датчик потока воздуха', 'answer' => 'Airflow sensor', 'weight' => 0],
    ['question' => 'Пленум', 'answer' => 'Plenum', 'weight' => 0],
    ['question' => 'Нагревательный элемент', 'answer' => 'Heating element', 'weight' => 0],
    ['question' => 'Прессостат', 'answer' => 'Pressure switch', 'weight' => 0],
    ['question' => 'Расширительный бак', 'answer' => 'Expansion tank', 'weight' => 0],
    ['question' => 'Управление зажиганием', 'answer' => 'Ignition control', 'weight' => 0],
    ['question' => 'Конденсатор', 'answer' => 'Capacitor', 'weight' => 0],
    ['question' => 'Реле', 'answer' => 'Relay switch', 'weight' => 0],
    ['question' => 'Трансформатор', 'answer' => 'Transformer', 'weight' => 0],
    ['question' => 'Панель управления', 'answer' => 'Control board', 'weight' => 0],
    ['question' => 'Мотор индуктора', 'answer' => 'Inducer motor', 'weight' => 0],
    ['question' => 'Мотор вентилятора', 'answer' => 'Blower motor', 'weight' => 0],
    ['question' => 'Газовая горелка', 'answer' => 'Gas burner', 'weight' => 0],
    ['question' => 'Датчик пламени', 'answer' => 'Flame sensor', 'weight' => 0],
    ['question' => 'Ограничительный выключатель', 'answer' => 'Limit switch', 'weight' => 0],
    ['question' => 'Терморезистор', 'answer' => 'Thermistor', 'weight' => 0],
    ['question' => 'Датчик потока', 'answer' => 'Flow sensor', 'weight' => 0],
    ['question' => 'Обратный клапан', 'answer' => 'Check valve', 'weight' => 0],
    ['question' => 'Термостатический клапан', 'answer' => 'Thermostatic valve', 'weight' => 0],
    ['question' => 'Насос для конденсата', 'answer' => 'Condensate pump', 'weight' => 0],
    ['question' => 'Слив конденсата', 'answer' => 'Condensate drain', 'weight' => 0],
    ['question' => 'Утеплительная лента', 'answer' => 'Insulation tape', 'weight' => 0],
    ['question' => 'Теплообменник', 'answer' => 'Heat exchanger', 'weight' => 0],
    ['question' => 'Заслонка вентиляции', 'answer' => 'Vent damper', 'weight' => 0],
    ['question' => 'Кольцо воздуховода', 'answer' => 'Duct collar', 'weight' => 0],
    ['question' => 'Реле вентилятора', 'answer' => 'Fan relay', 'weight' => 0],
    ['question' => 'Схема проводки', 'answer' => 'Wiring diagram', 'weight' => 0],
    ['question' => 'Панель управления', 'answer' => 'Control panel', 'weight' => 0],
    ['question' => 'Дифференциальное давление', 'answer' => 'Differential pressure', 'weight' => 0],
    ['question' => 'Клапан управления потоком', 'answer' => 'Flow control valve', 'weight' => 0],
    ['question' => 'Мембранный клапан', 'answer' => 'Diaphragm valve', 'weight' => 0],
    ['question' => 'Запальная горелка', 'answer' => 'Pilot burner', 'weight' => 0],
    ['question' => 'Газовый регулятор', 'answer' => 'Gas regulator', 'weight' => 0],
    ['question' => 'Расширительный клапан', 'answer' => 'Expansion valve', 'weight' => 0],
    ['question' => 'Вывод термопары', 'answer' => 'Thermocouple lead', 'weight' => 0],
    ['question' => 'Клемма проводки', 'answer' => 'Wiring terminal', 'weight' => 0],
    ['question' => 'Выброс пламени', 'answer' => 'Flame rollout', 'weight' => 0],
    ['question' => 'Ловушка конденсата', 'answer' => 'Condensate trap', 'weight' => 0],
    ['question' => 'Вакуумный выключатель', 'answer' => 'Vacuum switch', 'weight' => 0],
    ['question' => 'Индуктор тяги', 'answer' => 'Draft inducer', 'weight' => 0],
    ['question' => 'Воспламенитель пламени', 'answer' => 'Flame ignitor', 'weight' => 0],
    ['question' => 'Зарядка хладагента', 'answer' => 'Refrigerant charge', 'weight' => 0],
    ['question' => 'Клапан сброса давления', 'answer' => 'Pressure relief valve', 'weight' => 0],
    ['question' => 'Тепловой насос', 'answer' => 'Heat pump', 'weight' => 0],
    ['question' => 'Термостатический расширительный клапан', 'answer' => 'Thermostatic expansion valve', 'weight' => 0],
    ['question' => 'Теплоизоляционное покрывало', 'answer' => 'Insulation blanket', 'weight' => 0],
    ['question' => 'Башмак воздуховода', 'answer' => 'Duct boot', 'weight' => 0],
    ['question' => 'Управляющий трансформатор', 'answer' => 'Control transformer', 'weight' => 0],
    ['question' => 'Конденсационный блок', 'answer' => 'Condensing unit', 'weight' => 0],
    ['question' => 'Испарительная катушка', 'answer' => 'Evaporator coil', 'weight' => 0],
    ['question' => 'Плата размораживания', 'answer' => 'Defrost board', 'weight' => 0],
    ['question' => 'Колесо вентилятора', 'answer' => 'Blower wheel', 'weight' => 0],
    ['question' => 'Вытяжной кожух', 'answer' => 'Vent hood', 'weight' => 0],
    ['question' => 'Настенная розетка', 'answer' => 'Wall jack', 'weight' => 0],
    ['question' => 'Кабельные зажимы', 'answer' => 'Cable clips', 'weight' => 0],
    ['question' => 'Устройство защиты от перенапряжений', 'answer' => 'Surge suppressor', 'weight' => 0],
    ['question' => 'Заземляющий стержень', 'answer' => 'Ground rod', 'weight' => 0],
    ['question' => 'Коробка автоматов', 'answer' => 'Breaker box', 'weight' => 0],
    ['question' => 'Распределительный щит', 'answer' => 'Distribution board', 'weight' => 0],
    ['question' => 'Защита от перегрузок', 'answer' => 'Overcurrent protector', 'weight' => 0],
    ['question' => 'Последовательный предохранитель', 'answer' => 'In-line fuse', 'weight' => 0],
    ['question' => 'Тестер розетки с защитой от утечек', 'answer' => 'GFCI tester', 'weight' => 0],
    ['question' => 'Тестер напряжения', 'answer' => 'Voltage tester', 'weight' => 0],
    ['question' => 'Устройство прерывания цепи при замыкании на землю', 'answer' => 'Ground fault interrupter', 'weight' => 0],
    ['question' => 'Линейное напряжение', 'answer' => 'Line voltage', 'weight' => 0],
    ['question' => 'Низкое напряжение', 'answer' => 'Low voltage', 'weight' => 0],
    ['question' => 'Падение напряжения', 'answer' => 'Voltage drop', 'weight' => 0],
    ['question' => 'Омметр', 'answer' => 'Ohmmeter', 'weight' => 0],
    ['question' => 'Трансформатор тока', 'answer' => 'Current transformer', 'weight' => 0],
    ['question' => 'Центр нагрузки', 'answer' => 'Load center', 'weight' => 0],
    ['question' => 'Выключатель разъединения', 'answer' => 'Disconnect switch', 'weight' => 0],
    ['question' => 'Клеммный блок', 'answer' => 'Terminal block', 'weight' => 0],
    ['question' => 'Кабельный ввод', 'answer' => 'Cable gland', 'weight' => 0],
    ['question' => 'Прерыватель цепи', 'answer' => 'Circuit interrupter', 'weight' => 0],
    ['question' => 'Резистор нагрузки', 'answer' => 'Load resistor', 'weight' => 0],
    ['question' => 'Шина заземления', 'answer' => 'Grounding bus', 'weight' => 0],
    ['question' => 'Клемма нагрузки', 'answer' => 'Load terminal', 'weight' => 0],
    ['question' => 'Ответвленная цепь', 'answer' => 'Branch circuit', 'weight' => 0],
    ['question' => 'Короткое замыкание', 'answer' => 'Short circuit', 'weight' => 0],
    ['question' => 'Электрический скачок', 'answer' => 'Electrical surge', 'weight' => 0],
    ['question' => 'Регулятор напряжения', 'answer' => 'Voltage regulator', 'weight' => 0],
    ['question' => 'Стабилизатор питания', 'answer' => 'Power conditioner', 'weight' => 0],
    ['question' => 'Анализатор цепи', 'answer' => 'Circuit analyzer', 'weight' => 0],
    ['question' => 'Тестер фаз', 'answer' => 'Phase tester', 'weight' => 0],
    ['question' => 'Кабельные стяжки', 'answer' => 'Cable ties', 'weight' => 0],
    ['question' => 'Трубогиб для проводов', 'answer' => 'Conduit bender', 'weight' => 0],
    ['question' => 'Съемник изоляции', 'answer' => 'Insulation stripper', 'weight' => 0],
    ['question' => 'Термоусадочная трубка', 'answer' => 'Heat shrink tubing', 'weight' => 0],
    ['question' => 'Кабельный лоток', 'answer' => 'Cable tray', 'weight' => 0],
    ['question' => 'Электрическая розетка', 'answer' => 'Power outlet', 'weight' => 0],
    ['question' => 'Коробка розетки', 'answer' => 'Receptacle box', 'weight' => 0],
    ['question' => 'Жгут проводов', 'answer' => 'Wiring loom', 'weight' => 0],
    ['question' => 'Термический предохранитель', 'answer' => 'Thermal fuse', 'weight' => 0],
    ['question' => 'Клеммная колодка', 'answer' => 'Wiring block', 'weight' => 0],
    ['question' => 'Соединительная гайка', 'answer' => 'Wire nut', 'weight' => 0],
    ['question' => 'Разъемный болт', 'answer' => 'Split bolt', 'weight' => 0],
    ['question' => 'Соединитель проводов', 'answer' => 'Wire connector', 'weight' => 0],
    ['question' => 'Термофен', 'answer' => 'Heat gun', 'weight' => 0],
    ['question' => 'Обжимной инструмент', 'answer' => 'Crimping tool', 'weight' => 0],
    ['question' => 'Обжимщик проводов', 'answer' => 'Wire crimper', 'weight' => 0],
    ['question' => 'Катушка кабеля', 'answer' => 'Cable spool', 'weight' => 0],
    ['question' => 'Сверло', 'answer' => 'Drill bit', 'weight' => 0],
    ['question' => 'Корончатое сверло', 'answer' => 'Hole saw', 'weight' => 0],
    ['question' => 'Тестер кабеля', 'answer' => 'Cable tester', 'weight' => 0],
    ['question' => 'Электрическая лента', 'answer' => 'Electrical tape', 'weight' => 0],
    ['question' => 'Теплоизоляционная гильза', 'answer' => 'Insulation sleeve', 'weight' => 0],
    ['question' => 'Ограничитель тока', 'answer' => 'Current limiter', 'weight' => 0],
    ['question' => 'Уловитель перенапряжений', 'answer' => 'Surge arrestor', 'weight' => 0],
    ['question' => 'Защита от перегрузок', 'answer' => 'Overload protector', 'weight' => 0],
    ['question' => 'Датчик тепла', 'answer' => 'Heat detector', 'weight' => 0],
    ['question' => 'Датчик дыма', 'answer' => 'Smoke sensor', 'weight' => 0],
    ['question' => 'Электрическая труба', 'answer' => 'Electrical conduit', 'weight' => 0],
    ['question' => 'Сетевой фильтр', 'answer' => 'Power strip', 'weight' => 0],
    ['question' => 'Падение напряжения', 'answer' => 'Voltage dropper', 'weight' => 0],
    ['question' => 'Перемещение изоляции', 'answer' => 'Insulation displacement', 'weight' => 0],
    ['question' => 'Дуговое замыкание', 'answer' => 'Arc fault', 'weight' => 0],
    ['question' => 'Прерыватель цепи при дуговом замыкании', 'answer' => 'Arc fault circuit interrupter', 'weight' => 0],
    ['question' => 'Фазный проводник', 'answer' => 'Phase conductor', 'weight' => 0],
    ['question' => 'Заземляющий электрод', 'answer' => 'Grounding electrode', 'weight' => 0],
    ['question' => 'Система заземления', 'answer' => 'Earthing system', 'weight' => 0],
    ['question' => 'Уловитель молний', 'answer' => 'Lightning arrester', 'weight' => 0],
    ['question' => 'Скачок напряжения', 'answer' => 'Power surge', 'weight' => 0],
    ['question' => 'Датчик тока', 'answer' => 'Current sensor', 'weight' => 0],
    ['question' => 'Электрический счетчик', 'answer' => 'Electrical meter', 'weight' => 0],
    ['question' => 'Энергомонитор', 'answer' => 'Power meter', 'weight' => 0],
    ['question' => 'Монитор энергопотребления', 'answer' => 'Energy monitor', 'weight' => 0],
    ['question' => 'Защита от замыканий на землю', 'answer' => 'Ground fault protection', 'weight' => 0],
    ['question' => 'Электрическое соединение', 'answer' => 'Electrical bonding', 'weight' => 0],
    ['question' => 'Вращение фаз', 'answer' => 'Phase rotation', 'weight' => 0],
    ['question' => 'Изоляционный трансформатор', 'answer' => 'Isolation transformer', 'weight' => 0],
    ['question' => 'Инвертор напряжения', 'answer' => 'Power inverter', 'weight' => 0],
    ['question' => 'Двигатель постоянного тока', 'answer' => 'DC motor', 'weight' => 0],
    ['question' => 'Двигатель переменного тока', 'answer' => 'AC motor', 'weight' => 0],
    ['question' => 'Схема электропроводки', 'answer' => 'Electrical wiring diagram', 'weight' => 0],
    ['question' => 'Реле управления', 'answer' => 'Relay control', 'weight' => 0],
    ['question' => 'Автоматический выключатель', 'answer' => 'Power breaker', 'weight' => 0],
    ['question' => 'Петля заземления', 'answer' => 'Ground loop', 'weight' => 0],
    ['question' => 'Стабилизатор напряжения', 'answer' => 'Voltage stabilizer', 'weight' => 0],
    ['question' => 'Передача по силовой линии', 'answer' => 'Power line carrier', 'weight' => 0],
    ['question' => 'Защита цепи', 'answer' => 'Circuit protection', 'weight' => 0],
    ['question' => 'Усилитель мощности', 'answer' => 'Power amplifier', 'weight' => 0],
    ['question' => 'Разветвитель мощности', 'answer' => 'Power splitter', 'weight' => 0],
    ['question' => 'Тепловой автоматический выключатель', 'answer' => 'Thermal circuit breaker', 'weight' => 0],
    ['question' => 'Реле питания', 'answer' => 'Power relay', 'weight' => 0],
    ['question' => 'Электрическое реле', 'answer' => 'Electrical relay', 'weight' => 0],
    ['question' => 'Энергосчетчик', 'answer' => 'Energy meter', 'weight' => 0],
    ['question' => 'Защитное устройство от перенапряжений', 'answer' => 'Surge protective device', 'weight' => 0],
    ['question' => 'Маршрутизация кабеля', 'answer' => 'Cable routing', 'weight' => 0],
    ['question' => 'Крепление для кабельных стяжек', 'answer' => 'Cable tie mount', 'weight' => 0],
    ['question' => 'Удерживающий зажим', 'answer' => 'Insulation clamp', 'weight' => 0],
    ['question' => 'Кабельный зажим', 'answer' => 'Cable clip', 'weight' => 0],
    ['question' => 'Электрический сплайс', 'answer' => 'Electrical splice', 'weight' => 0],
    ['question' => 'Калибр провода', 'answer' => 'Wire gauge', 'weight' => 0],
    ['question' => 'Перегрузка по току', 'answer' => 'Current overload', 'weight' => 0],
    ['question' => 'Энергосистема', 'answer' => 'Power grid', 'weight' => 0],
    ['question' => 'Токовая нагрузка', 'answer' => 'Current load', 'weight' => 0],
    ['question' => 'Автоматический выключатель цепи', 'answer' => 'Circuit breaker', 'weight' => 0],
    ['question' => 'Защита от короткого замыкания', 'answer' => 'Short circuit protection', 'weight' => 0],
    ['question' => 'Распределение электроэнергии', 'answer' => 'Power distribution', 'weight' => 0],
    ['question' => 'Балансировка нагрузки', 'answer' => 'Load balancing', 'weight' => 0],
    ['question' => 'Распределение энергосистемы', 'answer' => 'Power grid distribution', 'weight' => 0],
    ['question' => 'Номинал напряжения', 'answer' => 'Voltage rating', 'weight' => 0],


    ['question' => 'Выключите питание на автомате.', 'answer' => 'Turn off the power at the breaker.', 'weight' => 0],
    ['question' => 'Установите светильник.', 'answer' => 'Install the light fixture.', 'weight' => 0],
    ['question' => 'Проверьте давление воды.', 'answer' => 'Check the water pressure.', 'weight' => 0],
    ['question' => 'Закрепите электрическую коробку.', 'answer' => 'Secure the electrical box.', 'weight' => 0],
    ['question' => 'Проверьте розетку тестером.', 'answer' => 'Test the outlet with a tester.', 'weight' => 0],
    ['question' => 'Пропустите проводку через трубу.', 'answer' => 'Run the wiring through the conduit.', 'weight' => 0],
    ['question' => 'Установите потолочный вентилятор.', 'answer' => 'Mount the ceiling fan.', 'weight' => 0],
    ['question' => 'Замените воздушный фильтр.', 'answer' => 'Replace the air filter.', 'weight' => 0],
    ['question' => 'Подключите медные трубы.', 'answer' => 'Connect the copper pipes.', 'weight' => 0],
    ['question' => 'Выпустите воздух из радиатора.', 'answer' => 'Bleed the radiator.', 'weight' => 0],
    ['question' => 'Установите новый термостат.', 'answer' => 'Install the new thermostat.', 'weight' => 0],
    ['question' => 'Проверьте сантехнику на наличие утечек.', 'answer' => 'Check for leaks in the plumbing.', 'weight' => 0],
    ['question' => 'Замените автоматический выключатель.', 'answer' => 'Replace the circuit breaker.', 'weight' => 0],
    ['question' => 'Заклейте воздуховоды скотчем.', 'answer' => 'Seal the ductwork with tape.', 'weight' => 0],
    ['question' => 'Установите дымовой извещатель.', 'answer' => 'Install the smoke detector.', 'weight' => 0],
    ['question' => 'Проверьте розетку с защитой от утечек.', 'answer' => 'Test the GFCI outlet.', 'weight' => 0],
    ['question' => 'Проверьте утеплитель на чердаке.', 'answer' => 'Check the insulation in the attic.', 'weight' => 0],
    ['question' => 'Установите вытяжной вентилятор.', 'answer' => 'Install the exhaust fan.', 'weight' => 0],
    ['question' => 'Проведите сантехнику для раковины.', 'answer' => 'Run the plumbing for the sink.', 'weight' => 0],
    ['question' => 'Проверьте систему отопления и вентиляции.', 'answer' => 'Test the HVAC system.', 'weight' => 0],
    ['question' => 'Установите электрическую розетку.', 'answer' => 'Install the electrical outlet.', 'weight' => 0],
    ['question' => 'Замените кран.', 'answer' => 'Replace the faucet.', 'weight' => 0],
    ['question' => 'Закрепите настенный обогреватель.', 'answer' => 'Mount the wall heater.', 'weight' => 0],
    ['question' => 'Утеплите водопроводные трубы.', 'answer' => 'Insulate the water pipes.', 'weight' => 0],
    ['question' => 'Установите водонагреватель.', 'answer' => 'Install the water heater.', 'weight' => 0],
    ['question' => 'Проведите вентиляцию для сушилки.', 'answer' => 'Run the vent for the dryer.', 'weight' => 0],
    ['question' => 'Подключите газовую линию к плите.', 'answer' => 'Connect the gas line to the stove.', 'weight' => 0],
    ['question' => 'Установите посудомоечную машину.', 'answer' => 'Install the dishwasher.', 'weight' => 0],
    ['question' => 'Проверьте воздушные каналы на наличие правильного потока воздуха.', 'answer' => 'Test the air ducts for proper airflow.', 'weight' => 0],
    ['question' => 'Установите подсветку под шкафами.', 'answer' => 'Install the under-cabinet lighting.', 'weight' => 0],
    ['question' => 'Закрепите обогреватель плинтуса.', 'answer' => 'Secure the baseboard heater.', 'weight' => 0],
    ['question' => 'Проложите кабель CAT6 для интернета.', 'answer' => 'Run the CAT6 cable for internet.', 'weight' => 0],
    ['question' => 'Подключите систему отопления и вентиляции к термостату.', 'answer' => 'Connect the HVAC to the thermostat.', 'weight' => 0],
    ['question' => 'Установите вытяжку на кухне.', 'answer' => 'Install the kitchen hood vent.', 'weight' => 0],
    ['question' => 'Замените измельчитель отходов.', 'answer' => 'Replace the garbage disposal.', 'weight' => 0],
    ['question' => 'Проверьте электрический щиток на наличие неисправностей.', 'answer' => 'Check the breaker panel for faults.', 'weight' => 0],
    ['question' => 'Установите встроенные светильники.', 'answer' => 'Install the recessed lighting.', 'weight' => 0],
    ['question' => 'Установите настенную розетку над столешницей.', 'answer' => 'Mount the wall outlet above the counter.', 'weight' => 0],
    ['question' => 'Установите систему подогрева пола.', 'answer' => 'Install the floor heating system.', 'weight' => 0],
    ['question' => 'Замените душевую лейку.', 'answer' => 'Replace the showerhead.', 'weight' => 0],
    ['question' => 'Проверьте целостность проводов.', 'answer' => 'Check the continuity of the wires.', 'weight' => 0],
    ['question' => 'Установите программируемый термостат.', 'answer' => 'Install the programmable thermostat.', 'weight' => 0],
    ['question' => 'Проложите трубы ПВХ для дренажа.', 'answer' => 'Run the PVC pipes for drainage.', 'weight' => 0],
    ['question' => 'Установите потолочные плитки.', 'answer' => 'Install the ceiling tiles.', 'weight' => 0],
    ['question' => 'Замените старую проводку на новую.', 'answer' => 'Replace the old wiring with new.', 'weight' => 0],
    ['question' => 'Проверьте смягчитель воды.', 'answer' => 'Test the water softener.', 'weight' => 0],
    ['question' => 'Установите плоский экран телевизора с скрытыми проводами.', 'answer' => 'Mount the flat-screen TV with hidden wires.', 'weight' => 0],
    ['question' => 'Установите диммерный выключатель.', 'answer' => 'Install the dimmer switch.', 'weight' => 0],
    ['question' => 'Проверьте вентиляцию для печи.', 'answer' => 'Check the venting for the furnace.', 'weight' => 0],
    ['question' => 'Проложите линию горячей воды в ванную комнату.', 'answer' => 'Run the hot water line to the bathroom.', 'weight' => 0],
    ['question' => 'Запечатайте окна герметиком.', 'answer' => 'Seal the windows with caulking.', 'weight' => 0],


    ['question' => 'Смотри под ноги!', 'answer' => 'Watch your step!', 'weight' => 0],
    ['question' => 'Нам нужно выровнять эту область.', 'answer' => 'We need to level this area.', 'weight' => 0],
    ['question' => 'Где чертежи?', 'answer' => 'Where are the blueprints?', 'weight' => 0],
    ['question' => 'Установите гипсокартон здесь.', 'answer' => 'Install the drywall here.', 'weight' => 0],
    ['question' => 'Убедитесь, что все по уровню.', 'answer' => 'Make sure everything is square.', 'weight' => 0],
    ['question' => 'Бетон должен застыть.', 'answer' => 'The concrete needs to cure.', 'weight' => 0],
    ['question' => 'Проверьте измерения еще раз.', 'answer' => 'Check the measurements again.', 'weight' => 0],
    ['question' => 'Передайте мне гаечный ключ, пожалуйста.', 'answer' => 'Pass me the wrench, please.', 'weight' => 0],
    ['question' => 'Нам нужно больше материалов.', 'answer' => 'We need more materials.', 'weight' => 0],
    ['question' => 'Защитное снаряжение обязательно.', 'answer' => 'The safety gear is mandatory.', 'weight' => 0],
    ['question' => 'Следуйте правилам безопасности.', 'answer' => 'Follow the safety guidelines.', 'weight' => 0],
    ['question' => 'Держите лестницу устойчиво.', 'answer' => 'Hold the ladder steady.', 'weight' => 0],
    ['question' => 'Мерьте дважды, режьте один раз.', 'answer' => 'Measure twice, cut once.', 'weight' => 0],
    ['question' => 'Не забудьте про винты.', 'answer' => 'Don’t forget the screws.', 'weight' => 0],
    ['question' => 'Нам нужно залить фундамент.', 'answer' => 'We need to pour the foundation.', 'weight' => 0],
    ['question' => 'Соберите леса.', 'answer' => 'Assemble the scaffolding.', 'weight' => 0],
    ['question' => 'Тщательно перемешайте бетон.', 'answer' => 'Mix the concrete thoroughly.', 'weight' => 0],
    ['question' => 'Держите рабочую площадку в чистоте.', 'answer' => 'Keep the worksite clean.', 'weight' => 0],
    ['question' => 'Нам нужно уложиться в срок.', 'answer' => 'We need to meet the deadline.', 'weight' => 0],
    ['question' => 'Можете передать мне молоток?', 'answer' => 'Can you hand me the hammer?', 'weight' => 0],
    ['question' => 'Где ближайшая розетка?', 'answer' => 'Where is the nearest power outlet?', 'weight' => 0],
    ['question' => 'Обрежьте дерево до этой длины.', 'answer' => 'Cut the wood to this length.', 'weight' => 0],
    ['question' => 'Просверлите отверстие здесь.', 'answer' => 'Drill a hole here.', 'weight' => 0],
    ['question' => 'Выровняйте балки правильно.', 'answer' => 'Align the beams correctly.', 'weight' => 0],
    ['question' => 'Загрузите материалы в грузовик.', 'answer' => 'Load the materials into the truck.', 'weight' => 0],
    ['question' => 'Затяните те болты.', 'answer' => 'Tighten those bolts.', 'weight' => 0],
    ['question' => 'Подметите территорию перед началом работы.', 'answer' => 'Sweep the area before we start.', 'weight' => 0],
    ['question' => 'Нам нужно установить проводку.', 'answer' => 'We need to install the wiring.', 'weight' => 0],
    ['question' => 'Надежно закрепите груз.', 'answer' => 'Secure the load properly.', 'weight' => 0],
    ['question' => 'Начнем с каркаса.', 'answer' => 'Let’s start with the framing.', 'weight' => 0],
    ['question' => 'Всегда носите каску.', 'answer' => 'Wear your hard hat at all times.', 'weight' => 0],
    ['question' => 'Осторожно с кабелями.', 'answer' => 'Watch out for the cables.', 'weight' => 0],
    ['question' => 'Покрасьте стены в этот цвет.', 'answer' => 'Paint the walls this color.', 'weight' => 0],
    ['question' => 'Мы отстаем от графика.', 'answer' => 'We’re behind schedule.', 'weight' => 0],
    ['question' => 'Можете принести ящик с инструментами?', 'answer' => 'Can you fetch the toolbox?', 'weight' => 0],
    ['question' => 'Нам нужно больше гвоздей.', 'answer' => 'We need more nails.', 'weight' => 0],
    ['question' => 'Это нужно сделать водонепроницаемым.', 'answer' => 'This needs to be waterproofed.', 'weight' => 0],
    ['question' => 'Обрежьте плитку точно.', 'answer' => 'Cut the tiles precisely.', 'weight' => 0],
    ['question' => 'Нам понадобится разрешение на это.', 'answer' => 'We’ll need a permit for that.', 'weight' => 0],
    ['question' => 'Закрепите лестницу перед подъемом.', 'answer' => 'Secure the ladder before climbing.', 'weight' => 0],
    ['question' => 'Пожалуйста, тише.', 'answer' => 'Keep the noise down, please.', 'weight' => 0],
    ['question' => 'Равномерно укладывайте кирпичи.', 'answer' => 'Lay the bricks evenly.', 'weight' => 0],
    ['question' => 'Давайте еще раз пройдемся по плану.', 'answer' => 'Let’s go over the plan again.', 'weight' => 0],
    ['question' => 'Убедитесь, что дверь подходит к раме.', 'answer' => 'Make sure the door fits the frame.', 'weight' => 0],
    ['question' => 'Нам нужно укрепить конструкцию.', 'answer' => 'We need to brace the structure.', 'weight' => 0],
    ['question' => 'Отшлифуйте поверхность перед покраской.', 'answer' => 'Sand the surface before painting.', 'weight' => 0],
    ['question' => 'Нам понадобится кран для этого.', 'answer' => 'We’ll need a crane for that.', 'weight' => 0],
    ['question' => 'Где ближайший строительный магазин?', 'answer' => 'Where’s the nearest hardware store?', 'weight' => 0],
    ['question' => 'Устанавливайте окна аккуратно.', 'answer' => 'Install the windows carefully.', 'weight' => 0],
    ['question' => 'Это нужно утеплить.', 'answer' => 'This needs to be insulated.', 'weight' => 0],
    ['question' => 'Не блокируйте пожарные выходы.', 'answer' => 'Don’t block the fire exits.', 'weight' => 0],
    ['question' => 'Постелите брезент.', 'answer' => 'Lay down the tarp.', 'weight' => 0],
    ['question' => 'Начните с углового элемента.', 'answer' => 'Start with the corner piece.', 'weight' => 0],
    ['question' => 'Проверьте выравнивание дважды.', 'answer' => 'Double-check the alignment.', 'weight' => 0],
    ['question' => 'Уберите мусор.', 'answer' => 'Clean up the debris.', 'weight' => 0],
    ['question' => 'Нам нужно больше бетонной смеси.', 'answer' => 'We need more concrete mix.', 'weight' => 0],
    ['question' => 'Закрепите балки.', 'answer' => 'Secure the joists.', 'weight' => 0],
    ['question' => 'Используйте уровень для проверки.', 'answer' => 'Use the spirit level to check.', 'weight' => 0],
    ['question' => 'Потолок нужно укрепить.', 'answer' => 'The ceiling needs to be reinforced.', 'weight' => 0],
    ['question' => 'Проверьте чертежи на наличие деталей.', 'answer' => 'Check the blueprints for details.', 'weight' => 0],
    ['question' => 'У нас закончилась древесина.', 'answer' => 'We’re out of lumber.', 'weight' => 0],
    ['question' => 'Осторожно разгружайте грузовик.', 'answer' => 'Unload the truck carefully.', 'weight' => 0],
    ['question' => 'Заполните щели герметиком.', 'answer' => 'Fill in the gaps with caulk.', 'weight' => 0],
    ['question' => 'Соберите каркас.', 'answer' => 'Assemble the framework.', 'weight' => 0],
    ['question' => 'Проверьте несущую способность.', 'answer' => 'Check the load-bearing capacity.', 'weight' => 0],
    ['question' => 'Используйте правильное сверло.', 'answer' => 'Use the right drill bit.', 'weight' => 0],
    ['question' => 'Эту стену нужно снести.', 'answer' => 'This wall needs to be demolished.', 'weight' => 0],
    ['question' => 'Нам нужно больше наждачной бумаги.', 'answer' => 'We need more sandpaper.', 'weight' => 0],
    ['question' => 'Равномерно укладывайте пол.', 'answer' => 'Lay the flooring evenly.', 'weight' => 0],
    ['question' => 'Закрепите леса.', 'answer' => 'Secure the scaffolding.', 'weight' => 0],
    ['question' => 'Смешайте гипс.', 'answer' => 'Mix the plaster.', 'weight' => 0],
    ['question' => 'Проводку нужно переделать.', 'answer' => 'The wiring needs to be redone.', 'weight' => 0],
    ['question' => 'У нас заканчиваются запасы.', 'answer' => 'We’re running low on supplies.', 'weight' => 0],
    ['question' => 'Измерьте ширину дверного проема.', 'answer' => 'Measure the width of the doorway.', 'weight' => 0],
    ['question' => 'Где автоматический выключатель?', 'answer' => 'Where’s the circuit breaker?', 'weight' => 0],
    ['question' => 'Установите светильники.', 'answer' => 'Install the light fixtures.', 'weight' => 0],
    ['question' => 'Заклейте края скотчем.', 'answer' => 'Seal the edges with tape.', 'weight' => 0],
    ['question' => 'Выровняйте стойки по меткам.', 'answer' => 'Align the studs with the marks.', 'weight' => 0],
    ['question' => 'Нам понадобится электрик для этого.', 'answer' => 'We’ll need an electrician for that.', 'weight' => 0],
    ['question' => 'Сначала удалите старую краску.', 'answer' => 'Remove the old paint first.', 'weight' => 0],
    ['question' => 'Установите петли здесь.', 'answer' => 'Install the hinges here.', 'weight' => 0],
    ['question' => 'Затяните винты.', 'answer' => 'Tighten the screws.', 'weight' => 0],
    ['question' => 'Уложите трубу под фундаментом.', 'answer' => 'Lay the pipe under the foundation.', 'weight' => 0],
    ['question' => 'Крыша нуждается в новой черепице.', 'answer' => 'The roof needs new shingles.', 'weight' => 0],
    ['question' => 'Используйте домкрат для подъема.', 'answer' => 'Use the jack to lift it.', 'weight' => 0],
    ['question' => 'Пол нужно выровнять.', 'answer' => 'The floor needs to be leveled.', 'weight' => 0],
    ['question' => 'Установите стойки в бетон.', 'answer' => 'Set the posts in concrete.', 'weight' => 0],
    ['question' => 'Установите поручни.', 'answer' => 'Install the handrails.', 'weight' => 0],
    ['question' => 'Где удлинитель?', 'answer' => 'Where’s the extension cord?', 'weight' => 0],
    ['question' => 'Надежно закрепите кронштейны.', 'answer' => 'Attach the brackets securely.', 'weight' => 0],
    ['question' => 'Заполните трещины шпаклевкой.', 'answer' => 'Fill in the cracks with putty.', 'weight' => 0],
    ['question' => 'Нам нужно разрешение на раскопки.', 'answer' => 'We need a permit for excavation.', 'weight' => 0],
    ['question' => 'Не перегружайте цепь.', 'answer' => 'Don’t overload the circuit.', 'weight' => 0],
    ['question' => 'Используйте монтировку, чтобы удалить это.', 'answer' => 'Use the pry bar to remove it.', 'weight' => 0],
    ['question' => 'Установите водостоки вдоль края.', 'answer' => 'Install the gutters along the edge.', 'weight' => 0],
    ['question' => 'Фундамент нуждается в укреплении.', 'answer' => 'The foundation needs reinforcement.', 'weight' => 0],
    ['question' => 'Утеплите окна от протечек.', 'answer' => 'Seal the windows against leaks.', 'weight' => 0],
    ['question' => 'Закрепите дверную раму.', 'answer' => 'Mount the door frame.', 'weight' => 0],
    ['question' => 'Уложите блоки фундамента.', 'answer' => 'Lay the foundation blocks.', 'weight' => 0],
    ['question' => 'Обрежьте утеплитель по размеру.', 'answer' => 'Cut the insulation to fit.', 'weight' => 0],
    ['question' => 'Закрепите плитку клеем.', 'answer' => 'Set the tiles with adhesive.', 'weight' => 0],
    ['question' => 'Установите стропила крыши.', 'answer' => 'Install the roof trusses.', 'weight' => 0],
    ['question' => 'Измерьте глубину отверстия.', 'answer' => 'Measure the depth of the hole.', 'weight' => 0],
    ['question' => 'Проверьте, нет ли ослабленных винтов.', 'answer' => 'Check for any loose screws.', 'weight' => 0],
    ['question' => 'Половые доски нужно отшлифовать.', 'answer' => 'The floorboards need sanding.', 'weight' => 0],
    ['question' => 'Выровняйте дверь по петлям.', 'answer' => 'Align the door with the hinges.', 'weight' => 0],
    ['question' => 'Нам нужно укрепить балки.', 'answer' => 'We need to reinforce the joists.', 'weight' => 0],
    ['question' => 'Нанесите грунтовку перед покраской.', 'answer' => 'Apply the primer before painting.', 'weight' => 0],
    ['question' => 'У нас закончились винты.', 'answer' => 'We’re out of screws.', 'weight' => 0],
    ['question' => 'Уложите сантехнику под полом.', 'answer' => 'Install the plumbing under the floor.', 'weight' => 0],
    ['question' => 'Стена нуждается в ремонте.', 'answer' => 'The wall needs to be patched up.', 'weight' => 0],
    ['question' => 'Закрепите гипсокартон на стойках.', 'answer' => 'Attach the drywall to the studs.', 'weight' => 0],
    ['question' => 'Покрасьте отделку маленькой кистью.', 'answer' => 'Paint the trim with a small brush.', 'weight' => 0],
    ['question' => 'Нам нужно больше гвоздей для крыши.', 'answer' => 'We need more nails for the roofing.', 'weight' => 0],
    ['question' => 'Проверьте несущую стену.', 'answer' => 'Check the load-bearing wall.', 'weight' => 0],
    ['question' => 'Утеплитель нужно заменить.', 'answer' => 'The insulation needs to be replaced.', 'weight' => 0],
    ['question' => 'Постелите листы фанеры.', 'answer' => 'Lay down the plywood sheets.', 'weight' => 0],
    ['question' => 'Установите вентиляционное отверстие на крыше.', 'answer' => 'Install the vent on the roof.', 'weight' => 0],
    ['question' => 'Используйте дрель для создания направляющих отверстий.', 'answer' => 'Use the drill to make pilot holes.', 'weight' => 0],
    ['question' => 'Отшлифуйте грубые края.', 'answer' => 'Sand down the rough edges.', 'weight' => 0],
    ['question' => 'Нам нужно заказать больше материалов.', 'answer' => 'We need to order more materials.', 'weight' => 0],
    ['question' => 'Установите выключатели света здесь.', 'answer' => 'Install the light switches here.', 'weight' => 0],
    ['question' => 'Проверьте проводку на наличие коротких замыканий.', 'answer' => 'Check the wiring for shorts.', 'weight' => 0],
    ['question' => 'Запечатайте крышу смолой.', 'answer' => 'Seal the roof with tar.', 'weight' => 0],
    ['question' => 'Надежно закрепите шкафы.', 'answer' => 'Mount the cabinets securely.', 'weight' => 0],
    ['question' => 'Пол нужно натереть воском.', 'answer' => 'The floor needs to be waxed.', 'weight' => 0],
    ['question' => 'Уложите бетонную плиту.', 'answer' => 'Lay down the concrete slab.', 'weight' => 0],
    ['question' => 'Потолочные плитки нужно заменить.', 'answer' => 'The ceiling tiles need replacing.', 'weight' => 0],
    ['question' => 'Нам нужно укрепить стены.', 'answer' => 'We need to brace the walls.', 'weight' => 0],
    ['question' => 'Сначала покрасьте потолок.', 'answer' => 'Paint the ceiling first.', 'weight' => 0],
    ['question' => 'Используйте мастерок для нанесения раствора.', 'answer' => 'Use the trowel to spread mortar.', 'weight' => 0],
    ['question' => 'Дека нуждается в покраске.', 'answer' => 'The deck needs to be stained.', 'weight' => 0],
    ['question' => 'Затяните болты на каркасе.', 'answer' => 'Tighten the bolts on the frame.', 'weight' => 0],
    ['question' => 'Нам нужно перенаправить трубы.', 'answer' => 'We’ll need to reroute the pipes.', 'weight' => 0],
    ['question' => 'Обрежьте арматуру по размеру.', 'answer' => 'Cut the rebar to size.', 'weight' => 0],
    ['question' => 'Установите плинтусы.', 'answer' => 'Install the baseboards.', 'weight' => 0],
    ['question' => 'Где рулетка?', 'answer' => 'Where’s the tape measure?', 'weight' => 0],
    ['question' => 'Фундамент нужно проверить.', 'answer' => 'The foundation needs to be checked.', 'weight' => 0],
    ['question' => 'Установите световой люк на крыше.', 'answer' => 'Install the skylight in the roof.', 'weight' => 0],
    ['question' => 'Стена нуждается в утеплении.', 'answer' => 'The wall needs to be insulated.', 'weight' => 0],
    ['question' => 'Закрепите поручни на лестнице.', 'answer' => 'Attach the railing to the stairs.', 'weight' => 0],
    ['question' => 'Заполните трещины эпоксидом.', 'answer' => 'Fill the cracks with epoxy.', 'weight' => 0],
    ['question' => 'Лестницу нужно отшлифовать.', 'answer' => 'The stairs need to be sanded.', 'weight' => 0],
    ['question' => 'Выровняйте дверь по замку.', 'answer' => 'Align the door with the lock.', 'weight' => 0],
    ['question' => 'Используйте лобзик, чтобы распилить дерево.', 'answer' => 'Use the jigsaw to cut the wood.', 'weight' => 0],
    ['question' => 'Установите душевые принадлежности.', 'answer' => 'Install the shower fixtures.', 'weight' => 0],
    ['question' => 'Оконная рама нуждается в ремонте.', 'answer' => 'The window frame needs repair.', 'weight' => 0],
    ['question' => 'Нам нужно больше бетонной смеси.', 'answer' => 'We need more concrete mix.', 'weight' => 0],
    ['question' => 'Постелите ковер в этой комнате.', 'answer' => 'Lay the carpet in this room.', 'weight' => 0],
    ['question' => 'Установите розетки вдоль стены.', 'answer' => 'Install the outlets along the wall.', 'weight' => 0],
    ['question' => 'Проверьте балку на наличие трещин.', 'answer' => 'Check the beam for cracks.', 'weight' => 0],
    ['question' => 'Закрепите раму к стене.', 'answer' => 'Secure the frame to the wall.', 'weight' => 0],
    ['question' => 'Используйте угловую шлифовальную машину для этого разреза.', 'answer' => 'Use the angle grinder for that cut.', 'weight' => 0],
    ['question' => 'Трубу нужно утеплить.', 'answer' => 'The pipe needs to be insulated.', 'weight' => 0],
    ['question' => 'Установите внешнюю облицовку.', 'answer' => 'Install the exterior siding.', 'weight' => 0],
    ['question' => 'Водосток нуждается в чистке.', 'answer' => 'The gutter needs cleaning.', 'weight' => 0],
    ['question' => 'Закрепите черепицу на крыше.', 'answer' => 'Secure the roofing tiles.', 'weight' => 0],
    ['question' => 'Окну нужны новые уплотнения.', 'answer' => 'The window needs new seals.', 'weight' => 0],
    ['question' => 'Уложите плитку по диагонали.', 'answer' => 'Lay the tile in a diagonal pattern.', 'weight' => 0],
    ['question' => 'Закрепите зеркало на стене.', 'answer' => 'Mount the mirror on the wall.', 'weight' => 0],
    ['question' => 'Потолочный вентилятор нужно установить.', 'answer' => 'The ceiling fan needs installing.', 'weight' => 0],
    ['question' => 'Затяните фитинги на трубе.', 'answer' => 'Tighten the pipe fittings.', 'weight' => 0],
    ['question' => 'Установите лампочки.', 'answer' => 'Install the lightbulbs.', 'weight' => 0],
    ['question' => 'Дека нуждается в новых досках.', 'answer' => 'The deck needs new boards.', 'weight' => 0],
    ['question' => 'Закрепите окно винтами.', 'answer' => 'Secure the window with screws.', 'weight' => 0],
    ['question' => 'Отделку нужно перекрасить.', 'answer' => 'The trim needs repainting.', 'weight' => 0],
    ['question' => 'Уложите кирпичи в прямую линию.', 'answer' => 'Lay the bricks in a straight line.', 'weight' => 0],
    ['question' => 'Установите новый дверной замок.', 'answer' => 'Install the new door lock.', 'weight' => 0],
    ['question' => 'Стена нуждается в перекраске.', 'answer' => 'The wall needs to be repainted.', 'weight' => 0],
    ['question' => 'Проверьте пол на ровность.', 'answer' => 'Check the floor for level.', 'weight' => 0],
    ['question' => 'Балка нуждается в поддержке.', 'answer' => 'The beam needs support.', 'weight' => 0],
    ['question' => 'Установите балки пола.', 'answer' => 'Install the floor joists.', 'weight' => 0],
    ['question' => 'Крыше нужна новая обрешетка.', 'answer' => 'The roof needs new flashing.', 'weight' => 0],
    ['question' => 'Затяните гайки на болтах.', 'answer' => 'Tighten the nuts on the bolts.', 'weight' => 0],
    ['question' => 'Трубы нужно перенаправить.', 'answer' => 'The pipes need to be rerouted.', 'weight' => 0],
    ['question' => 'Установите жалюзи на окнах.', 'answer' => 'Install the window blinds.', 'weight' => 0],
    ['question' => 'Половые плитки нужно затереть.', 'answer' => 'The floor tiles need grouting.', 'weight' => 0],
    ['question' => 'Раковине нужна новая сантехника.', 'answer' => 'The sink needs new plumbing.', 'weight' => 0],
    ['question' => 'Установите душевую лейку.', 'answer' => 'Install the showerhead.', 'weight' => 0],
    ['question' => 'Стена нуждается в герметизации.', 'answer' => 'The wall needs to be sealed.', 'weight' => 0],
    ['question' => 'Закрепите поручни деки.', 'answer' => 'Secure the deck railing.', 'weight' => 0],
    ['question' => 'Уложите тротуарные плитки елочкой.', 'answer' => 'Lay the pavers in a herringbone pattern.', 'weight' => 0],
    ['question' => 'Забору нужны новые стойки.', 'answer' => 'The fence needs new posts.', 'weight' => 0],
    ['question' => 'Проводка нуждается в заземлении.', 'answer' => 'The wiring needs to be grounded.', 'weight' => 0],
    ['question' => 'Установите вытяжку.', 'answer' => 'Install the range hood.', 'weight' => 0],
    ['question' => 'Гипсокартон нуждается в ремонте.', 'answer' => 'The drywall needs patching.', 'weight' => 0],
    ['question' => 'Закрепите светильник.', 'answer' => 'Secure the light fixture.', 'weight' => 0],
    ['question' => 'Гаражные ворота нуждаются в регулировке.', 'answer' => 'The garage door needs adjustment.', 'weight' => 0],
    ['question' => 'Установите водонагреватель.', 'answer' => 'Install the water heater.', 'weight' => 0],
    ['question' => 'Плитку нужно повторно затереть.', 'answer' => 'The tiles need to be re-grouted.', 'weight' => 0],
    ['question' => 'Проверьте давление воды.', 'answer' => 'Check the water pressure.', 'weight' => 0],
    ['question' => 'Автоматический выключатель нужно заменить.', 'answer' => 'The circuit breaker needs replacing.', 'weight' => 0],
    ['question' => 'Установите каминную вставку.', 'answer' => 'Install the fireplace insert.', 'weight' => 0],
    ['question' => 'Фундамент нуждается в гидроизоляции.', 'answer' => 'The foundation needs waterproofing.', 'weight' => 0],
    ['question' => 'Закрепите балки болтами.', 'answer' => 'Secure the beams with bolts.', 'weight' => 0],
    ['question' => 'Крыша нуждается в осмотре.', 'answer' => 'The roof needs to be inspected.', 'weight' => 0],
    ['question' => 'Утеплите чердак.', 'answer' => 'Install the insulation in the attic.', 'weight' => 0],
    ['question' => 'Пол нужно установить.', 'answer' => 'The flooring needs to be installed.', 'weight' => 0],
    ['question' => 'Закрепите кронштейн для телевизора на стене.', 'answer' => 'Mount the TV bracket on the wall.', 'weight' => 0],
    ['question' => 'Забор нужно покрасить.', 'answer' => 'The fence needs to be painted.', 'weight' => 0],
    ['question' => 'Проверьте систему отопления и вентиляции.', 'answer' => 'Check the HVAC system.', 'weight' => 0],
    ['question' => 'Чердак нуждается в вентиляции.', 'answer' => 'The attic needs ventilation.', 'weight' => 0],
    ['question' => 'Установите панели забора.', 'answer' => 'Install the fence panels.', 'weight' => 0],
    ['question' => 'Черепицу нужно заменить.', 'answer' => 'The shingles need to be replaced.', 'weight' => 0],
    ['question' => 'Закрепите калитку забора.', 'answer' => 'Secure the fence gate.', 'weight' => 0],
    ['question' => 'Установите потолочные плитки.', 'answer' => 'Install the ceiling tiles.', 'weight' => 0],
    ['question' => 'Трубе нужен новый клапан.', 'answer' => 'The pipe needs a new valve.', 'weight' => 0],
    ['question' => 'Стены нуждаются в новом гипсокартоне.', 'answer' => 'The walls need new drywall.', 'weight' => 0],
    ['question' => 'Закрепите столб с бетоном.', 'answer' => 'Secure the post with concrete.', 'weight' => 0],
    ['question' => 'Установите новые столешницы.', 'answer' => 'Install the new countertops.', 'weight' => 0],
    ['question' => 'Пол нуждается в доработке.', 'answer' => 'The floor needs refinishing.', 'weight' => 0],
    ['question' => 'Закрепите стеллаж на стене.', 'answer' => 'Mount the shelving unit.', 'weight' => 0],
    ['question' => 'Крыше нужна новая подкладка.', 'answer' => 'The roof needs new underlayment.', 'weight' => 0],
    ['question' => 'Закрепите половые доски винтами.', 'answer' => 'Secure the floorboards with screws.', 'weight' => 0],
    ['question' => 'Гаражу нужно больше освещения.', 'answer' => 'The garage needs more lighting.', 'weight' => 0],
    ['question' => 'Установите утеплитель крыши.', 'answer' => 'Install the roof insulation.', 'weight' => 0],
    ['question' => 'Оконные стекла нужно заменить.', 'answer' => 'The window panes need replacing.', 'weight' => 0],
    ['question' => 'Установите дверные ручки.', 'answer' => 'Install the door handles.', 'weight' => 0],
    ['question' => 'Забору нужны дополнительные опоры.', 'answer' => 'The fence needs more supports.', 'weight' => 0],
    ['question' => 'Закрепите лестницу к стене.', 'answer' => 'Secure the ladder to the wall.', 'weight' => 0],
    ['question' => 'Дека нуждается в герметизации.', 'answer' => 'The deck needs to be sealed.', 'weight' => 0],
    ['question' => 'Установите уплотнители.', 'answer' => 'Install the weather stripping.', 'weight' => 0],
    ['question' => 'Крыше нужны новые вентиляционные отверстия.', 'answer' => 'The roof needs new vents.', 'weight' => 0],
    ['question' => 'Закрепите забор кронштейнами.', 'answer' => 'Secure the fence with brackets.', 'weight' => 0],
    ['question' => 'Плитку нужно загерметизировать.', 'answer' => 'The tiles need sealing.', 'weight' => 0],
    ['question' => 'Установите светильники в ванной.', 'answer' => 'Install the light fixtures in the bathroom.', 'weight' => 0],
    ['question' => 'Сантехника нуждается в обновлении.', 'answer' => 'The plumbing needs an upgrade.', 'weight' => 0],
    ['question' => 'Установите заднюю дверь.', 'answer' => 'Install the back door.', 'weight' => 0],
    ['question' => 'Гаражу нужна новая проводка.', 'answer' => 'The garage needs new wiring.', 'weight' => 0],
    ['question' => 'Закрепите деку болтами.', 'answer' => 'Secure the deck with bolts.', 'weight' => 0],
    ['question' => 'Гипсокартон нужно отшлифовать.', 'answer' => 'The drywall needs sanding.', 'weight' => 0],
    ['question' => 'Установите новый почтовый ящик.', 'answer' => 'Install the new mailbox.', 'weight' => 0],
    ['question' => 'Подвал нуждается в гидроизоляции.', 'answer' => 'The basement needs waterproofing.', 'weight' => 0],
    ['question' => 'Закрепите ступени на крыльце.', 'answer' => 'Secure the steps to the porch.', 'weight' => 0],
    ['question' => 'Двери нужны новые петли.', 'answer' => 'The door needs new hinges.', 'weight' => 0],
    ['question' => 'Установите наружное освещение.', 'answer' => 'Install the outdoor lighting.', 'weight' => 0],
    ['question' => 'Пол нужно подмести.', 'answer' => 'The floor needs to be swept.', 'weight' => 0],
    ['question' => 'Закрепите крышу гвоздями.', 'answer' => 'Secure the roofing with nails.', 'weight' => 0],
    ['question' => 'Чердаку нужно больше утеплителя.', 'answer' => 'The attic needs more insulation.', 'weight' => 0],
    ['question' => 'Установите новый дверной звонок.', 'answer' => 'Install the new doorbell.', 'weight' => 0],
    ['question' => 'Лестнице нужны новые поручни.', 'answer' => 'The stairs need new handrails.', 'weight' => 0],
    ['question' => 'Закрепите окна замками.', 'answer' => 'Secure the windows with locks.', 'weight' => 0],
    ['question' => 'Водостоку нужны новые клипсы.', 'answer' => 'The gutter needs new clips.', 'weight' => 0],
    ['question' => 'Установите черепицу на крыше.', 'answer' => 'Install the roof shingles.', 'weight' => 0],
    ['question' => 'Подвалу нужен дренажный насос.', 'answer' => 'The basement needs a sump pump.', 'weight' => 0],
    ['question' => 'Закрепите облицовку к стене.', 'answer' => 'Secure the siding to the wall.', 'weight' => 0],
    ['question' => 'Сантехнику нужно утеплить.', 'answer' => 'The plumbing needs to be insulated.', 'weight' => 0],
    ['question' => 'Установите дверные петли.', 'answer' => 'Install the door hinges.', 'weight' => 0],
    ['question' => 'Чердаку нужен новый вентиляционный люк.', 'answer' => 'The attic needs a new vent.', 'weight' => 0],
    ['question' => 'Закрепите пол с помощью винтов.', 'answer' => 'Secure the floor with screws.', 'weight' => 0],
    ['question' => 'Забор нуждается в покраске.', 'answer' => 'The fence needs painting.', 'weight' => 0],
    ['question' => 'Установите дымовые датчики.', 'answer' => 'Install the smoke detectors.', 'weight' => 0],
    ['question' => 'Стене нужен новый слой штукатурки.', 'answer' => 'The wall needs new plaster.', 'weight' => 0],
    ['question' => 'Закрепите окна кронштейнами.', 'answer' => 'Secure the windows with brackets.', 'weight' => 0],
    ['question' => 'Дека нуждается в новой лестнице.', 'answer' => 'The deck needs new stairs.', 'weight' => 0],
    ['question' => 'Установите вентиляционные отверстия на крыше.', 'answer' => 'Install the roof vents.', 'weight' => 0],
    ['question' => 'Облицовка нуждается в ремонте.', 'answer' => 'The siding needs repair.', 'weight' => 0],
    ['question' => 'Закрепите поручни на лестнице.', 'answer' => 'Secure the handrails to the stairs.', 'weight' => 0],
    ['question' => 'Сантехнику нужно проверить.', 'answer' => 'The plumbing needs inspection.', 'weight' => 0],
    ['question' => 'Установите автоматические ворота.', 'answer' => 'Install the garage door opener.', 'weight' => 0],
    ['question' => 'Дорога нуждается в новом покрытии.', 'answer' => 'The driveway needs repaving.', 'weight' => 0],
    ['question' => 'Закрепите стойки деки бетоном.', 'answer' => 'Secure the deck posts with concrete.', 'weight' => 0],
    ['question' => 'Чердак нуждается в чистке.', 'answer' => 'The attic needs cleaning.', 'weight' => 0],
    ['question' => 'Установите столбы забора.', 'answer' => 'Install the fence posts.', 'weight' => 0],
    ['question' => 'Водосток нуждается в ремонте.', 'answer' => 'The gutter needs repair.', 'weight' => 0],
    ['question' => 'Закрепите крышу винтами.', 'answer' => 'Secure the roof with screws.', 'weight' => 0],
    ['question' => 'Пол нуждается в новой плитке.', 'answer' => 'The floor needs new tiles.', 'weight' => 0],
    ['question' => 'Установите новую душевую дверь.', 'answer' => 'Install the new shower door.', 'weight' => 0],
    ['question' => 'Сантехнику нужно проверить.', 'answer' => 'The plumbing needs to be checked.', 'weight' => 0],
    ['question' => 'Закрепите оконные рамы.', 'answer' => 'Secure the window frames.', 'weight' => 0],
    ['question' => 'Лестнице нужны новые ступени.', 'answer' => 'The stairs need new treads.', 'weight' => 0],
    ['question' => 'Установите накладки на крышу.', 'answer' => 'Install the roof flashing.', 'weight' => 0],
    ['question' => 'Стене нужна новая краска.', 'answer' => 'The wall needs new paint.', 'weight' => 0],
    ['question' => 'Закрепите деку винтами.', 'answer' => 'Secure the deck with screws.', 'weight' => 0],
    ['question' => 'Чердаку нужен новый утеплитель.', 'answer' => 'The attic needs new insulation.', 'weight' => 0],
    ['question' => 'Установите новые ворота.', 'answer' => 'Install the new fence gate.', 'weight' => 0],
    ['question' => 'Пол нуждается в новом ковре.', 'answer' => 'The floor needs new carpeting.', 'weight' => 0],
    ['question' => 'Закрепите черепицу на крыше гвоздями.', 'answer' => 'Secure the roof tiles with nails.', 'weight' => 0],
    ['question' => 'Подвалу нужен новый пол.', 'answer' => 'The basement needs new flooring.', 'weight' => 0],
    ['question' => 'Установите дверные замки.', 'answer' => 'Install the door locks.', 'weight' => 0],
    ['question' => 'Дорога нуждается в герметизации.', 'answer' => 'The driveway needs sealing.', 'weight' => 0],
    ['question' => 'Закрепите забор гвоздями.', 'answer' => 'Secure the fence with nails.', 'weight' => 0],
    ['question' => 'Гаражу нужна новая дверь.', 'answer' => 'The garage needs a new door.', 'weight' => 0],
    ['question' => 'Установите светильники.', 'answer' => 'Install the light fixtures.', 'weight' => 0],
    ['question' => 'Сантехнике нужны новые трубы.', 'answer' => 'The plumbing needs new pipes.', 'weight' => 0],
    ['question' => 'Закрепите облицовку гвоздями.', 'answer' => 'Secure the siding with nails.', 'weight' => 0],
    ['question' => 'Крыше нужны новые плитки.', 'answer' => 'The roof needs new tiles.', 'weight' => 0],
    ['question' => 'Установите новые окна.', 'answer' => 'Install the new windows.', 'weight' => 0],
    ['question' => 'Дека нуждается в новых досках.', 'answer' => 'The deck needs new boards.', 'weight' => 0],
    ['question' => 'Закрепите панели забора.', 'answer' => 'Secure the fence panels.', 'weight' => 0],
    ['question' => 'Стене нужен новый гипсокартон.', 'answer' => 'The wall needs new drywall.', 'weight' => 0],
    ['question' => 'Уложите напольную плитку.', 'answer' => 'Install the floor tiles.', 'weight' => 0],
    ['question' => 'Потолку нужна новая краска.', 'answer' => 'The ceiling needs new paint.', 'weight' => 0],
    ['question' => 'Закрепите крышу кронштейнами.', 'answer' => 'Secure the roof with brackets.', 'weight' => 0],
    ['question' => 'Подвалу нужно новое освещение.', 'answer' => 'The basement needs new lights.', 'weight' => 0],
    ['question' => 'Установите новые сантехнические принадлежности.', 'answer' => 'Install the new plumbing fixtures.', 'weight' => 0],
    ['question' => 'Лестнице нужен новый поручень.', 'answer' => 'The stairs need new railing.', 'weight' => 0],
    ['question' => 'Закрепите деку гвоздями.', 'answer' => 'Secure the deck with nails.', 'weight' => 0],
    ['question' => 'Чердаку нужна новая лестница.', 'answer' => 'The attic needs a new ladder.', 'weight' => 0],
    ['question' => 'Уложите черепицу на крыше.', 'answer' => 'Install the roof tiles.', 'weight' => 0],
    ['question' => 'Подвалу нужна новая дверь.', 'answer' => 'The basement needs a new door.', 'weight' => 0],
    ['question' => 'Закрепите пол с помощью гвоздей.', 'answer' => 'Secure the floor with nails.', 'weight' => 0],
    ['question' => 'Дорога нуждается в новом бетоне.', 'answer' => 'The driveway needs new concrete.', 'weight' => 0],
    ['question' => 'Установите оконные ставни.', 'answer' => 'Install the window shutters.', 'weight' => 0],
    ['question' => 'Стене нужен новый слой краски.', 'answer' => 'The wall needs a new coat of paint.', 'weight' => 0],
    ['question' => 'Закрепите лестницу винтами.', 'answer' => 'Secure the stairs with screws.', 'weight' => 0],
    ['question' => 'Крыше нужен новый герметик.', 'answer' => 'The roof needs a new sealant.', 'weight' => 0],
    ['question' => 'Установите забор с помощью бетона.', 'answer' => 'Install the fence with concrete.', 'weight' => 0],
    ['question' => 'Чердаку нужны новые окна.', 'answer' => 'The attic needs new windows.', 'weight' => 0],
    ['question' => 'Закрепите крышу гвоздями.', 'answer' => 'Secure the roof with nails.', 'weight' => 0],
    ['question' => 'Подвалу нужно новое освещение.', 'answer' => 'The basement needs a new light.', 'weight' => 0],
    ['question' => 'Установите новый потолочный вентилятор.', 'answer' => 'Install the new ceiling fan.', 'weight' => 0],
    ['question' => 'Лестнице нужно заново постелить ковер.', 'answer' => 'The stairs need to be re-carpeted.', 'weight' => 0],
    ['question' => 'Закрепите облицовку винтами.', 'answer' => 'Secure the siding with screws.', 'weight' => 0],
    ['question' => 'Дороге нужны новые ворота.', 'answer' => 'The driveway needs a new gate.', 'weight' => 0],
    ['question' => 'Установите новые петли для ворот.', 'answer' => 'Install the new gate hinges.', 'weight' => 0],
    ['question' => 'Крыше нужна новая изоляция.', 'answer' => 'The roof needs new insulation.', 'weight' => 0],
    ['question' => 'Закрепите забор с помощью бетона.', 'answer' => 'Secure the fence with concrete.', 'weight' => 0],
    ['question' => 'Чердаку нужно новое освещение.', 'answer' => 'The attic needs a new light.', 'weight' => 0],
    ['question' => 'Установите новые сантехнические клапаны.', 'answer' => 'Install the new plumbing valves.', 'weight' => 0],
    ['question' => 'Дека нуждается в новом поручне.', 'answer' => 'The deck needs a new railing.', 'weight' => 0],
    ['question' => 'Закрепите лестницу кронштейнами.', 'answer' => 'Secure the stairs with brackets.', 'weight' => 0],
    ['question' => 'Подвалу нужен новый вентиляционный люк.', 'answer' => 'The basement needs a new vent.', 'weight' => 0],
    ['question' => 'Установите вентиляционные колпаки на крыше.', 'answer' => 'Install the roof vent caps.', 'weight' => 0],
    ['question' => 'Стене нужен новый утеплитель.', 'answer' => 'The wall needs new insulation.', 'weight' => 0],
    ['question' => 'Закрепите пол с помощью бетона.', 'answer' => 'Secure the floor with concrete.', 'weight' => 0],
    ['question' => 'Гаражу нужна новая крыша.', 'answer' => 'The garage needs a new roof.', 'weight' => 0],
    ['question' => 'Установите новую дверную раму.', 'answer' => 'Install the new door frame.', 'weight' => 0],
    ['question' => 'Дека нуждается в новой покраске.', 'answer' => 'The deck needs a new paint job.', 'weight' => 0],
    ['question' => 'Закрепите забор кронштейнами.', 'answer' => 'Secure the fence with brackets.', 'weight' => 0],
    ['question' => 'Чердаку нужна новая лестница.', 'answer' => 'The attic needs a new ladder.', 'weight' => 0],
    ['question' => 'Уложите подложку на крышу.', 'answer' => 'Install the roof underlayment.', 'weight' => 0],
    ['question' => 'Подвалу нужен новый потолок.', 'answer' => 'The basement needs a new ceiling.', 'weight' => 0],
    ['question' => 'Закрепите черепицу на крыше винтами.', 'answer' => 'Secure the roof tiles with screws.', 'weight' => 0],
    ['question' => 'Стене нужна новая рама.', 'answer' => 'The wall needs a new frame.', 'weight' => 0],
    ['question' => 'Установите потолочные плитки.', 'answer' => 'Install the ceiling tiles.', 'weight' => 0],
    ['question' => 'Дорога нуждается в новом герметике.', 'answer' => 'The driveway needs a new sealant.', 'weight' => 0],
    ['question' => 'Закрепите забор винтами.', 'answer' => 'Secure the fence with screws.', 'weight' => 0],
    ['question' => 'Чердаку нужен новый пол.', 'answer' => 'The attic needs new flooring.', 'weight' => 0],
    ['question' => 'Установите новый дверной звонок.', 'answer' => 'Install the new doorbell.', 'weight' => 0],
    ['question' => 'Крыше нужна новая черепица.', 'answer' => 'The roof needs new shingles.', 'weight' => 0],
    ['question' => 'Закрепите деку с помощью бетона.', 'answer' => 'Secure the deck with concrete.', 'weight' => 0],
    ['question' => 'Подвалу нужен новый насос.', 'answer' => 'The basement needs a new pump.', 'weight' => 0],
    ['question' => 'Установите новый водонагреватель.', 'answer' => 'Install the new water heater.', 'weight' => 0],
    ['question' => 'Дорога нуждается в новом покрытии.', 'answer' => 'The driveway needs a new surface.', 'weight' => 0],
    ['question' => 'Закрепите облицовку кронштейнами.', 'answer' => 'Secure the siding with brackets.', 'weight' => 0],
    ['question' => 'Чердаку нужен новый утеплитель.', 'answer' => 'The attic needs new insulation.', 'weight' => 0],
    ['question' => 'Установите новые сантехнические трубы.', 'answer' => 'Install the new plumbing pipes.', 'weight' => 0],
    ['question' => 'Дека нуждается в новом освещении.', 'answer' => 'The deck needs new lighting.', 'weight' => 0],
    ['question' => 'Закрепите крышу гвоздями.', 'answer' => 'Secure the roof with nails.', 'weight' => 0],


];
